### ISSUE TITLE
Duplicate participant after participant reconnect

### ISSUE THREAD

**Issue by maybepete** [livekit/livekit#1022]
I'm curious to see if anyone else ran into this issue we've stumbled upon while doing some testing. The issue we're having is that it's possible to have the same participant (unique sid, same identity) presented twice on the egress client.

Very loosely described we're setting one participant in some kind of reconnecting state and while the LiveKit server decides what to do with this client we join again with the same identity and this results in the egress client to stumble into this weird state. This happens regardless if we join the room with the same token or freshly signed for this same identity. By the looks of it the iOS SDK and the example.livekit.io clients do not behave the same way as the egress client does when this issue occurs and its only the egress client which presents this participant twice. Using the `livekit-cli list-participants` before and after reproducing this state I get the same output and nothing is hinting at two clients being connected to this room:
```
$ livekit-cli list-participants ...
lvsuser:{"uid":"1","showId":"ztZLD7U3RAoarXuhFOEe","ci":-1} (ACTIVE)	 tracks: 2
template_test (ACTIVE)	 tracks: 0
```

Steps to reproduce:
* Set up a LiveKit room
* Sign token for a participant
* Run `livekit-cli test-egress-template ...` using the template-default egress client found here: https://github.com/livekit/egress/tree/main/template-default
* Create iOS app based on documentation as described at https://github.com/livekit/client-sdk-swift#installation
* Run app and join LiveKit room
* Turn on airplane mode on iOS device
* Force quit app
* Turn off airplane mode on iOS device
* Run app again in an timely fashion, before participants is discarded from server

Result: You now have two participants (with the same identity) showing the same AV tracks in the egress client and you can see the React code giving a warning that two children are rendered with the same key (identity).

Screenshot when this occurring:
<img width="1398" alt="Screenshot 2022-09-14 at 16 31 20" src="https://user-images.githubusercontent.com/2319341/190183484-5e8d1d87-8c70-4768-a0bb-8179baecef73.png">

Let me know if you're having problems reproducing and I'll try and dive deeper in my current setup.

**Comment by davidzhao** [comment]
This has been fixed in v1.4.0 by #1495
