### ISSUE TITLE
Question ws ip port

### ISSUE THREAD

**Issue by SudoDios** [livekit/livekit#1034]
How to change ip and port for ws?

**Comment by SudoDios** [comment]
How test with my custom ip and port in local network??
please help !!!

**Comment by SudoDios** [comment]
How to change bindAddresses to my custom ip ?

**Comment by davidzhao** [comment]
https://github.com/livekit/livekit/blob/master/config-sample.yaml#L1

`livekit-server --help`

**Comment by SudoDios** [comment]
Why can't I connect to the server when I bind to the wifi ip?
