### ISSUE TITLE
End to end encryption

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit#1035]
This issue tracks support for end to end encryption in LiveKit ecosystem. The design goals are:

* Consistent support across all LiveKit SDKs
* Protocol to communicate metadata about Tracks' encryption status
* Standard set of encryption algorithms (i.e. AEC-GCM)
* API to support simple shared key encryption
* Flexible API to allow clients to use more advanced key exchange techniques (i.e. double ratcheting algorithm)

Open issues
* Firefox does not support RTCRtpScriptTransform. [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1631263)

**Comment by NOT-HAL9000** [comment]
> Flexible API to allow clients to use more advanced key exchange techniques (i.e. double ratcheting algorithm)

This is exactly what I'm looking to do right now in a react native app. [Jitsi has a recent blog](https://jitsi.org/blog/a-stepping-stone-towards-end-to-end-encryption-on-mobile/) about their journey to e2ee with react native and how their flexible client api's works here. FYI, I'm planning on using Matrix's [vodozemac](https://github.com/matrix-org/vodozemac) olm rust implementation, which is what Jitsi mentioned at the bottom of the article referenced above (they are planning to migrate to it).

I was planning to use Livekit until I realized that an e2ee api wasn't supported yet. In the other issue, you mentioned this was on the roadmap, but since I wasn't able to find it publicly, would you be able to provide me with an estimate as to when you expect to address this as the top priority? I would much prefer to use this over mediasoup.

**Comment by davidzhao** [comment]
We are currently working on this! It's one of the highest priority features for the team. There isn't a release date yet.

**Comment by NOT-HAL9000** [comment]
@davidzhao Thank you so much! Looking forward to it. The developer experience with Livekit is good enough that I will wait for e2ee support

**Comment by davidzhao** [comment]
Max from the community has a fork of the JS SDK that implements E2EE: https://github.com/invisv-privacy/client-sdk-js/

**Comment by davidzhao** [comment]
E2EE has just been merged in [JS](https://github.com/livekit/client-sdk-js/pull/557). It's also available in Flutter. Other platforms will follow shortly!

**Comment by NOT-HAL9000** [comment]
> E2EE has just been merged in [JS](https://github.com/livekit/client-sdk-js/pull/557). It's also available in Flutter. Other platforms will follow shortly!

Thank you so much! This is really exciting :) Would love to see some information/guides/examples about how to use it in the docs!

**Comment by davidzhao** [comment]
PRs for native SDKs:
* [Android](https://github.com/livekit/client-sdk-android/pull/238)
* [Swift](https://github.com/livekit/client-sdk-swift/pull/226)

**Comment by davidzhao** [comment]
An update on this, E2EE is available in all of our SDKs except for react-native. Given the general availability of the feature, I'm closing this issue. Will open a new issue under react-native

**Comment by davidzhao** [comment]
https://github.com/livekit/client-sdk-react-native/issues/96 for tracking React-Native implementation

**Comment by castig** [comment]
@davidzhao Hi! Thanks for all the great work here! 

1) Does E2EE for Livekit mean that the video itself is encrypted? 

2) If the React Native SDK isn't available. How do you decide which rooms/users are using E2EE?

**Comment by davidzhao** [comment]
Hi @castig 

1. Yes! each frame is encrypted on the client before getting sent over.
2. For folks that don't use react-native, this would be straight forward. If you are using react-native, you could look to see [if the track is encrypted](https://github.com/livekit/client-sdk-js/blob/main/src/room/track/TrackPublication.ts#L94) and notify the other side to disable encryption

**Comment by Gulianrdgd** [comment]
Can we get some documentation for how E2EE works? Or at least some more examples, for instance there is no example for when everyone has their own key.

I am getting it to work and it looks great! But I am having some bugs and without documentation it is difficult to debug

**Comment by royatanu94** [comment]
@davidzhao Can we get some documentation for how E2EE works & how to configure?

**Comment by bcherry** [comment]
Sorry for the delay but we just published new docs on E2EE, although it doesn't yet include an example with per-participant-keys https://docs.livekit.io/home/client/tracks/encryption/

**Comment by aehlke** [comment]
Any plans to extend this to text?

**Comment by boks1971** [comment]
> Any plans to extend this to text?

Data channel (which is used to transport arbitrary data including text) is being planned. No ETA on that yet though.

**Comment by aehlke** [comment]
@boks1971 amazing thank you
