### ISSUE TITLE
WHIP Support

### ISSUE THREAD

**Issue by anupriya17** [livekit/livekit#1083]
Is WHIP going to be supported in near future in LiveKit?

https://www.ietf.org/archive/id/draft-ietf-wish-whip-03.html

**Comment by davidzhao** [comment]
WHIP is on our radar. I'm curious what is your use case with it. Is there an app that you are trying to ingest from that supports WHIP?

**Comment by osmanhomek** [comment]
To date, the open source [Meedoze](https://github.com/medooze/media-server) WebRTC Media Server, [Janus](https://janus.conf.meetecho.com/) WebRTC Server and [Millicast](https://millicast.com/]) WebRTC PaaS have implemented WHIP. If you are interested in more technical details about the [Medooze implementation](https://medium.com/@medooze/86772eba8ae7), or the [Janus implementation](https://github.com/lminiero/simple-whip-client), you can read those great blog posts by their respective authors.

from
https://millicast.medium.com/whip-the-magic-bullet-for-webrtc-media-ingest-57c2b98fb285

**Comment by davidzhao** [comment]
WHIP is a good move for the industry, and we do plan to support it.

My question is trying to understand the use cases that you are trying to achieve today, and how critical is WHIP to those use cases.

**Comment by davidzhao** [comment]
That's good to know. Which sources are you ingesting from?

**Comment by llspalex** [comment]
WHIP has made it's way into [OBS](https://github.com/obsproject/obs-studio/pull/7192) (albeit not an official release, yet). Would be really awesome to stream from OBS to LiveKit using WHIP.

**Comment by necrodome** [comment]
Gstreamer now supports [WHIP](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/835), which makes ingesting any kind of source very easy using the Gstreamer pipeline. My use case is ingesting camera feeds (mostly with RTSP) into a room.

**Comment by davidzhao** [comment]
We are looking into WHIP support now as part of our upcoming Ingress component. Will update here when we have news to share :)

**Comment by davidzhao** [comment]
OBS Studio has [a PR](https://github.com/obsproject/obs-studio/pull/7926) open now for WHIP support.

**Comment by bdrtc** [comment]
then, will livekit support [WHEP ](https://www.ietf.org/id/draft-murillo-whep-01.html):>

**Comment by davidzhao** [comment]
> then, will livekit support [WHEP ](https://www.ietf.org/id/draft-murillo-whep-01.html)? :>

We are going to start with WHIP! and then see where it takes us :)

**Comment by bdrtc** [comment]
[WHEP](https://www.ietf.org/id/draft-murillo-whep-01.html) define HTTP-based protocol that allow WebRTC-based viewers to watch content from streaming services.

VolcEngineRTC WTN team opensource the [`WHIP/WHEP`](https://github.com/volcengine/VolcengineWTN/blob/main/README_en.md) client which support both web and native mobile client(industry first
support WHIP/WHEP in mobile) , welcome to test.

**Comment by johan149** [comment]
Following this Larix already supports WHIP to ingest.

https://www.youtube.com/watch?v=FVhRJQDwimo&ab_channel=Softvelum

**Comment by brynrichards** [comment]
@davidzhao please would it be possible to get an update on WHIP status ( and when it would be supported in Livekit Cloud )?  We are keen to switch from our webrtc datachannel solution to WHIP and avoid a long running process.      I've seen some recent commits that suggest an implementation exists / is in the works; if it does exist how do we go about using it via the egress API? 

Many thanks!

**Comment by davidzhao** [comment]
WHIP support will be shipping soon! The development will be taking place in our [Ingress](https://github.com/livekit/ingress) module

**Comment by davidzhao** [comment]
We now have full WHIP support in Ingress. Docs: https://docs.livekit.io/server/ingress/
