### ISSUE TITLE
Log level ignored in LiveKit config

### ISSUE THREAD

**Issue by trey-hakanson-skydio** [livekit/livekit#1103]
**Describe the bug**
Setting logging level in config does not have the desired behavior; the default level of info is not overriden.

**Server**
- Version: [1.2.3]
- Environment: [EKS]

**Client**
N/A

**To Reproduce**
1. Include the following in the LiveKit server's configuration:
```
logging:
    level: warning
    json: true  # included to make sure the logging config is being read
log_level: warning # I also tried the legacy param
```
2. Restart LiveKit
3. Verify config is loaded, in my case with:
```
kubectl exec -it livekit-server-<pod_id> -n livekit -- printenv LIVEKIT_CONFIG
```
4. Observe info level logs (expecting warning)

Really I want to see debug logs, but the easiest way to prove the issue was to use the warning level since there are info logs on startup, which I'm still seeing. I know the config is being loaded because they're in the specified `json` format:

```
➜  ~ kubectl logs -f service/livekit-server -n livekit
{"level":"info","ts":1666107912.3246357,"logger":"livekit","caller":"service/wire_gen.go:186","msg":"using multi-node routing via redis","sentinel":false,"addr":"<redacted>"}
{"level":"info","ts":1666107912.483665,"logger":"livekit","caller":"service/turn.go:127","msg":"Starting TURN server","turn.relay_range_start":30000,"turn.relay_range_end":40000,"turn.portTLS":443,"turn.externalTLS":false,"turn.portUDP":443}
{"level":"info","ts":1666107912.5094275,"logger":"livekit","caller":"service/server.go:211","msg":"starting LiveKit server","portHttp":7880,"nodeID":"ND_h3GkpvHq","nodeIP":"<redacted>","version":"1.2.3","rtc.portTCP":7881,"rtc.portICERange":[50000,60000]}
```

**Expected behavior**
For the `level`/`log_level` config to be reflected on startup.

**Additional context**
Happy to provide any other relevant context. Thanks in advance for the help!

**Comment by davidzhao** [comment]
Log level should actually be `warn` instead of `warning`. Sorry I see that the config file is indicating this incorrectly. I'll update.

**Comment by trey-hakanson-skydio** [comment]
Thanks for the quick reply; `warn` is working!
