### ISSUE TITLE
Room does not get deleted after empty timeout

### ISSUE THREAD

**Issue by imredobos** [livekit/livekit#1109]
**Describe the bug**
I can see lots of rooms on my server to which I have not joined, and these rooms have not been deleted after the default empty timeout - custom has not been provided.

**Server**
- Version: [1.2.4] (and before)
- Environment: [local dev, EKS]
- multiregion setup

**To Reproduce**
1. create a room through the API
2. do not join to the room
3. wait more than the empty timeout
4. list the rooms, the room will be still there

**Expected behavior**
Room has to be deleted.

**Comment by jibon57** [comment]
At present room will be treated as active after a user will join. So, if you create a room & don't join then it will remain in redis/storage. As a work around you can run scheduler to close old rooms.

**Comment by imredobos** [comment]
@jibon57 If you are right then the documentation (https://docs.livekit.io/guides/server-api/#createroom) which says **number of seconds to keep the room open if no one joins** seems to be wrong, as well as the code here: https://github.com/livekit/livekit/blob/master/pkg/rtc/room.go#L529, it says it will close room after 20 sec if there were any participant and the last one has left the room, anyways if no one joined, the room should be deleted after the the empty timeout expires
