### ISSUE TITLE
Livekit sends ParticipantLeft webhook event without ParticipantJoined webhook event if RTC connection wasn't successfull

### ISSUE THREAD

**Issue by blombosi** [livekit/livekit#1130]
**Describe the bug**
If there was some error in the RTCConnection and the participant couldn't join to the session livekit still sends ParticipantLeft but didn't send ParticipantJoined webhook event.

I tried to debug the issue and found these:
https://github.com/livekit/livekit/blob/1019faa0e691955f0db4f56a96d3e9ad2bf64f24/pkg/rtc/room.go#L264
ParticipantJoined webhook event will be sent only if the participant state will be changed to ACTIVE, but ParticipantLeft webhook event will be sent even when the state will be changed to DISCONNECTED. 
https://github.com/livekit/protocol/blob/main/livekit/livekit_models.pb.go#L345
So if the ICE connection won't be established the state will change in the following order: JOINING -> JOINED -> DISCONNECTED and joined event won't be sent but left will be.

**Server**
- Version: 1.2.5
- Environment: local dev, EKS

**Expected behavior**
I expect to always have a Join webhook event before a Left.

**Comment by jibon57** [comment]
I'm experiencing same issue too. This typically occurs when a user has a poor connection. When a person joins plugNmeet, we increase the count, and when they leave, we decrease it, but because of this issue, the total number count turned negative sometime :-D

**Comment by davidzhao** [comment]
Good point.. if it hasn't successfully joined, it makes sense that it shouldn't send a LEAVE event either.
