### ISSUE TITLE
Interrupts and reconnects with Firefox participants

### ISSUE THREAD

**Issue by nkonev** [livekit/livekit#1143]
**Describe the bug**
There are interrupts and reconnects when one of participants uses Firefox. If all of them use Chrome - all is ok.

**Server**
- Version: Centos Linux 7
- Environment: docker-swarm its config https://github.com/nkonev/videochat/blob/f6e163d06b5ecded6e5e2f923b621e941cb34e2f/deploy/docker-compose-infra.template.yml#L79
- livekit/livekit-server:v1.2.4 its config https://github.com/nkonev/videochat/blob/f6e163d06b5ecded6e5e2f923b621e941cb34e2f/deploy/livekit/livekit.yaml

**Client**
- JavaScript SDK: "livekit-client": "1.4.3"

**To Reproduce**
1. Two desktop Linux Firefox clients and one mobile Android Chrome and are connected to room
2. Wait 30-60 sec
3. Sometimes I have in livekit-server's log
```
2022-11-03T12:09:23.212Z	ERROR	livekit.turn	v2@v2.0.8/server.go:184	error when handling datagram: failed to handle Allocate-request from 172.18.0.1:27592: relay already allocated for 5-TUPLE
github.com/pion/turn/v2.(*Server).readLoop
	/go/pkg/mod/github.com/pion/turn/v2@v2.0.8/server.go:184
github.com/pion/turn/v2.NewServer.func1
	/go/pkg/mod/github.com/pion/turn/v2@v2.0.8/server.go:85
```
4. This particular message looks like heisenbug. Those steps don't lead to this particular message every time
5. There are stable and persist interrupts and reconnects if we have at least one Firefox client

**Additional context**
[Untitled Document 1.txt](https://github.com/livekit/livekit/files/9928189/Untitled.Document.1.txt)

My thoughts (not necessary correct):
1. turn has a some commits after 2.0.8 https://github.com/pion/turn/compare/v2.0.8...HEAD
2. There is some PR https://github.com/pion/turn/pull/247 which sets some kind timeout
3. There is a commit https://github.com/livekit/livekit/commit/dd30808e5e1c462e19528c8d7c44c06dd9341f01, not sure is it related or not
4. IP 172.18.0.1:27592 in log looks like non-desired IP from browser. In general, it would be good to find some way not to send ips from docker networks on client's machine to the server

Hmm, I see https://github.com/livekit/livekit/issues/975 but it's still doesn't resolved

---
UPD: Just noticed, that livekit/livekit-server:v1.2.5 works better, the reconnects still persists, but clients connect eventually after hangs

UPD2: Also, If we force all Firefox participants to use Chrome, there are no reconnects

UPD3: I tried my custom build of latest main of livekit 34fd1a02 with fork of pion/turn with applied https://github.com/pion/turn/pull/247 but it doesn't help

UPD4: Firefox users seems works without interrputs with configs with enabled UDP and disabled [ICE Lite](https://github.com/livekit/livekit/pull/784), but I'm still testing
```livekit.yaml
port: 7880
rtc:
    udp_port: 7882
    #tcp_port: 7881
    tcp_port: 0
    use_external_ip: true
    #use_ice_lite: true
    use_ice_lite: false
    #port_range_start: 35200
    #port_range_end: 35400
    #force_tcp: true
    allow_tcp_fallback: false
#room:
#    enabled_codecs:
#        - mime: audio/opus
#        - mime: video/h264

turn:
    enabled: true
    udp_port: 3478

```

```docker-swarm.yaml
    image: livekit/livekit-server:v1.2.5
    ...
    ports:
      # turn udp port
      - target: 3478
        published: 3478
        protocol: udp
        mode: host

      # turn tls port
#      - target: 5349
#        published: 5349
#        protocol: tcp
#        mode: host

      # webrtc udp port
      - target: 7882
        published: 7882
        protocol: udp
        mode: host

      # webrtc tcp port
#      - target: 7881
#        published: 7881
#        protocol: tcp
#        mode: host
```
UPD5: I found ICE Lite bug in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1034964 and issue in [mediasoup](https://github.com/versatica/mediasoup/issues/650)

**Comment by nkonev** [comment]
Closed because disabling ICE lite helped. (It was occasionally enabled in my configs, but it is already disabled [by default](https://github.com/livekit/livekit/pull/784))

**Comment by davidzhao** [comment]
thanks for the thorough report @nkonev!

we haven't had issues with Firefox and ICELite in our server environment. I'm wondering if there are other differences in the setup. LiveKit supports aggressive renomination as well.

**Comment by nkonev** [comment]
So my configs are there
- Environment: docker-swarm its config https://github.com/nkonev/videochat/blob/f6e163d06b5ecded6e5e2f923b621e941cb34e2f/deploy/docker-compose-infra.template.yml#L79
- livekit/livekit-server:v1.2.4 its config https://github.com/nkonev/videochat/blob/f6e163d06b5ecded6e5e2f923b621e941cb34e2f/deploy/livekit/livekit.yaml

Issues and reconnects are not appear immediately, we need to wait 30-60 seconds.
