### ISSUE TITLE
Problem with connecting to LiveKit

### ISSUE THREAD

**Issue by derubanov** [livekit/livekit#1156]
Some providers  including in China or on the mobile Internet, do not connect to the LiveKit for some reason. The onConnected event fails in this case.

While using a VPN helps to connect within the current network.

livekit-server: v1.2.1 or v1.3.0
livekit-client: 0.18.6
livekit-react: 0.9.2

**Comment by jibon57** [comment]
If you're accessing from Mainland China & your server is hosted outside of China then this scenario is very common because China firewall. Make sure that the server where livekit is hosted isn't blacklisted in China firewall. Also internet in China is very unstable specially when you're accessing servers outside of China. Not sure if there is any way to detect such scenario in livekit.

**Comment by derubanov** [comment]
> If you're accessing from Mainland China & your server is hosted outside of China then this scenario is very common because of China firewall. Make sure that the server where livekit is hosted isn't blacklisted in China firewall. Also internet in China is very unstable especially when you're accessing servers outside of China. Not sure if there is any way to detect such scenario in livekit.

Thank you for reply, but we meeet the same issue in Russia and some other countries. Please support in this case.

**Comment by berrfott** [comment]
> Thank you for reply, but we meeet the same issue in Russia and some other countries. Please support in this case.
Let me guess: North Korea, Turkmenistan, Iran, Belarus, Turkey, Oman, Pakistan, United Arab Emirates, and Eritrea? (Sorry for hijacking this thread)

**Comment by davidzhao** [comment]
@derubanov you may need to host your own STUN servers and provide it in the server config. By default we will use Google's public STUN servers; which may be blocked in China.

If you have a specific network that can reproduce this, please reopen the ticket and provide client-side logs and a dump of `chrome://webrtc-internals`. that'll help us to diagnose it further.
