### ISSUE TITLE
Livekit  Kubernetes deployment model, has some strange operational limitations and security concerns.

### ISSUE THREAD

**Issue by cdeshapriya** [livekit/livekit#1161]
**How to make Livekit a first class citizen in Kubernetes**

I am sure you have already written your name in gold letters in the history of communication by developing Livekit as an open source solution, which will be the next destructive solution in the communication industry. But we still have one major issue to address, as WebRTC is not yet a first-class citizen in Kubernetes. 

The recommended method for installing LiveKit in Kubernetes is to deploy the media servers into the Kubernetes nodes' host-network namespace (hostNetwork: true). This deployment model, on the other hand, has some strange operational limitations and security concerns.

No worries, we have a solution here, and I have already tested it, and it works perfectly with livekit:  My solution for this serious drawback is at

https://github.com/l7mp/stunner/tree/main/examples/livekit

With this solution, not only livekit but any other WebRTC solution can function as a first-class citizen in Kubernetes. They did an excellent job, just as you did with Livekit: Here's the main page: https://l7mp.io/

For the multi-cloud overlay network you may consider my solution at
https://github.com/netbirdio/netbird, which is a low-latency VPN Mesh that uses PION, making gRPC and webRTC an ideal solution for real-time communication overlay networks with multi-cloud provider-agnostic connectivity.  

I would like to join your community and contribute and share my years of experience in complex cloud design and deployments to improve cloud deployment architecture.

**Comment by davidzhao** [comment]
Kudos on your OSS work and sharing it. I believe someone from your team is already in the community discussing this.

We'd welcome you to keep developing it. However, this doesn't quite fit as an issue here; it feels too much like a blatant promotion for your product. 

Moreover, It's already possible to not use host networking mode with LiveKit today via UDP single port. However, it comes with some limitations wrt throughput. This is why we do not recommended it for production setups.

**Comment by rg0now** [comment]
Hi @davidzhao, we'd like to make it absolutely clear from the side of the l7mp/stunner team that we have nothing to do with this issue. Not that we thought the Kubernetes+WebRTC story is solved (it isn't) or that STUNner is not a good fit for LiveKit (it is), or we don't want to shamelessly promote our own tool as well (we want), but we think a github issue is not necessarily the best way to do that.
BTW netbird Indeed seems quite an interesting project...
