### ISSUE TITLE
WebRTC connection lost if public IP is changed

### ISSUE THREAD

**Issue by berrfott** [livekit/livekit#1170]
I use NGINX for port 7880, and a DNS A record points to my public IP-address. My ISP changed my IP-address, so I updated the DNS A record. Livekit still reported that ports 50000-60000 was behind a firewall even though the ports were open - thus no WebRTC connection. The fix for the issue was to restart Livekit for it to acknowledge that the IP-address was changed. Is this restart really needed? Shouldn't Livekit sort out the issue by it self without the need for a restart?

Edit: Is this somehow connected to #1111 and #1160 ? (I'm on version 1.2.4 and using Docker)

**Comment by cnderrauber** [comment]
> Is this restart really needed?
If you enabled the `use_external_ip`, you need restart it, livekit only solve public ip when starting.

> Is this somehow connected to https://github.com/livekit/livekit/issues/1111 and https://github.com/livekit/livekit/issues/1160 ? (I'm on version 1.2.4 and using Docker)
I think they are different issues.

**Comment by davidzhao** [comment]
That's a bit out of scope for us. Closing as not planned.
