### ISSUE TITLE
Feature Request: RTCP Stat in prometheus support filter by Room ID

### ISSUE THREAD

**Issue by khmak3** [livekit/livekit#1189]
Existing RTCP Metric support overall stats only.  It will be helpful if those stats can be filter by Room ID. It can help narrow down issue for particular Room for investigation.

**Expected behavior**
Beside filtered by in coming and out going. Room ID should be information to keep

**Comment by khmak3** [comment]
https://github.com/livekit/livekit/blob/master/pkg/telemetry/prometheus/packets.go#L121

**Comment by davidzhao** [comment]
While I agree it'll be useful, Prometheus metrics do not do very well with high cardinality labels. The usage pattern of the request is more akin to a database than Prometheus
