### ISSUE TITLE
Loadbalancer & Port issues for self-hosted dev deployment

### ISSUE THREAD

**Issue by levanter-dev** [livekit/livekit#1204]
**Describe the bug**
I couldn't find any way to contact. I'm self-hosting the server on my CentOS7 server, it has Apache and redis installed. Using the production's config with new settings work, but using the sample dev doesn't. 

I have opened ports 7880 and 7881 and the UDP range of 50000 to 60000. When I execute the `--dev` flag, i get "tcp [::1]:7880: bind: cannot assign requested address". 

Not to mention that there's no documentation of the load-balancer config when using a self-hosted solution. Could you please guide me? I'm missing the link between the issue and my setup. I need a recommended config of the load-balancer along with a possible solution for the mentioned issue of the port. I have FirewallID installed.

Your help is appreciated.

**Server**
- Version: 1.3.1
- Environment: local
- VPS - CentOS7 - Apache

**To Reproduce**
1. Install
2. Run dev

**Expected behavior**
Dev server runs

**Additional context**

**Comment by davidzhao** [comment]
can you try to override the bind address manually? pass in `--bind 0.0.0.0` for example.
