### ISSUE TITLE
track_published webhook event works incorrectly

### ISSUE THREAD

**Issue by hiddein** [livekit/livekit#1254]
**Describe the bug**
It is necessary to publish audio and video tracks in the system always, even if the microphone is muted at the entrance, and then, depending on the state, mute the track. Implemented subscription to the RoomEvent.LocalTrackPublished event, inside the handler - mute tracks depending on the state. Case: in state - mute microphone and video. So, the webhook receives information that the audio track is published, but the video track does not reach.

**Server**
- Version: [1.1.0]
- Environment: local env

**Client**
- SDK: JS
- Version: [1.4.3]

**To Reproduce**
1. Client join the conference with audio: false, video:false state
2. Backend recieve webhook track_published event

**Expected behavior**
webhook sends information about the publication of audio and video tracks

My guess is that the message processing for the hook happens after the RoomEvent.LocalTrackPublished event is dispatched. Have to hack with settimeout to mute a track after publishing

**Comment by davidzhao** [comment]
It's not possible for livekit to receive a muted track, due to the way pion handles incoming tracks. filed #1434 to keep track instead.
