### ISSUE TITLE
SRTP optimizations to improve CPU utilization

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit#129]
@jech has identified a couple of areas that would have a significant improvement on CPU performance. These are in Pion's SRTP stack.

https://github.com/pion/srtp/pull/76
https://github.com/pion/srtp/pull/77

It would be great to have them merged and then for us to utilize these optimizations.

**Comment by TheBeachMaster** [comment]
One merged https://github.com/pion/srtp/pull/197 is waiting 🤞🏿

**Comment by davidzhao** [comment]
both have been merged. Great work @jech!
