### ISSUE TITLE
SIP Support

### ISSUE THREAD

**Issue by duiniuluantanqin** [livekit/livekit#1394]
Do we have any plans to support sip, which for make calls to plain old telephones over webrtc。
In my knowledge, we just act as sip clients, and work with the [FreeSWITCH](https://github.com/signalwire/freeswitch) to implement it.

Looking forward to your reply.

**Comment by neurosys-zero** [comment]
So how would this design/architecture work exactly? Any concepts in mind?

**Comment by neurosys-zero** [comment]
> Do we have any plans to support sip, which for make calls to plain old telephones over webrtc。 In my knowledge, we just act as sip clients, and work with the [FreeSWITCH](https://github.com/signalwire/freeswitch) to implement it.
> 
> Looking forward to your reply.

So how would this design/architecture work exactly? Any concepts in mind?

**Comment by davidzhao** [comment]
We do plan to support SIP. Currently the plan is to have a gateway module that's similar to Ingress and Egress that integrates with LiveKit. audio mixing and transcoding will take place in that SIP module. It has a few dependencies that we are working on first. But we should be able to get to it later this year.

**Comment by justin0mcateer** [comment]
I would be very interested in this. Please let me know if there is anything I could donto help. Testing, use cases, etc.

**Comment by shrikant-inextrix** [comment]
@davidzhao Any good news on this ?

Please let us know its very helpful.

**Comment by Kellykinyama12** [comment]
I would like to integrate livekit with our telephone system.

**Comment by shrikant-inextrix** [comment]
Good day.
    - We are trying to connect freeswitch with livekit.io using WSS (WSS URL - wss://unifyai-h*****5a.livekit.cloud)
    - We have installed the - libwebsockets for websocket connection
    - Also manage the module called mod_livekit for call the WSS server for call coonection.
    - Scenario is like - When calls comes to freeswitch that should connect to livekit.io room
    - But we are facing the issue as following.
        - Freeswitch is trying to connect WSS and WSS returns with - 200
        - But freeswitch needs 101 to establishing connection
        - Response received - lws_client_ws_upgrade: got bad HTTP response '200'
        - Please find the logs in patebin URL - https://pastebin.com/1bsb3L3G

**Comment by areski** [comment]
@shrikant-inextrix could you give some information about the freeswitch module that you are using `mod_livekit`?

**Comment by shrikant-inextrix** [comment]
Good day.

Sure, I will share the information ASAP with detail.

Thanks, and regards
================
Shrikant Thakar

Inextrix Technologies Pvt. Ltd.

https://www.inextrix.com<https://www.inextrix.com/>

https://www.astppbilling.org<https://www.astppbilling.org/>

https://www.icallify.com<https://www.icallify.com/>


Disclaimer:

The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking action in reliance on the contents of this information is strictly prohibited and may be unlawful. Please notify the sender immediately and destroy all copies of this message and any attachments contained in it.

________________________________

**Comment by Hollymingyi** [comment]
> We do plan to support SIP. Currently the plan is to have a gateway module that's similar to Ingress and Egress that integrates with LiveKit. audio mixing and transcoding will take place in that SIP module. It has a few dependencies that we are working on first. But we should be able to get to it later this year.

hello mr zhao,when exactly will the sip support be released? thank you !

**Comment by philipfrontend** [comment]
I have been waiting for the SIP support since 2021. When will this be available?

**Comment by thejoew** [comment]
Very curious if there are any updates on this?

 Also, is there a branch or feature where this is being worked on so I can attempt to help with implementation based on the architecture you mentioned above with an egress/ingress type of service.

**Comment by davidzhao** [comment]
We are actively working on this! Should have something in a couple of months

**Comment by davidzhao** [comment]
the SIP repo is now public and ready for anyone to try: https://github.com/livekit/sip

closing this issue.

**Comment by Perondas** [comment]
Thats awsome, thank you!

**Comment by areski** [comment]
@Shrikant-Inextrix Do you think you can share more information?
