### ISSUE TITLE
get video from track published by participant from opencv

### ISSUE THREAD

**Issue by anhtu-phan** [livekit/livekit#1416]
Hello,

I am creating an application in which the room is created by python-server and then sends back the access token to a mobile app (flutter) to access the room and publish the track (video) from the mobile camera.

Now from the python-server, I would like to use open-cv to access the track (video) from a mobile camera. Is there any solution for this case? Or could we have some callback function in the python-server when creating a room to receive frames from video from the mobile app?  

Thank you so much for your support.

**Comment by davidzhao** [comment]
It's not simple to interop with Python right now. If you don't mind messing with some Python/Rust bindings, you could leverage with our [Rust SDK](https://github.com/livekit/client-sdk-rust), which currently receives video from LiveKit servers
