### ISSUE TITLE
Streaming to RTMP with Auto Egress seem not work

### ISSUE THREAD

**Issue by anhtu-phan** [livekit/livekit#1431]
Hello, 

I am trying to create Auto Egress when I create a room via post request from python such as below:

`reUrl = "{livekit_cloud_url}/twirp/livekit.RoomService/CreateRoom"`
`headers={"Authorization": f"Bearer {token}", 'Content-Type': 'application/json'}`
`payload = json.dumps({`
`                "name": roomName,`
`                "egress": {`
`                    "stream": {`
`                        "urls": [f"rtmp://{host_ip}:{port}/live/{roomName}"]`
`                    }`
`                }`
`            })`
`response = requests.request("POST", reUrl, headers=headers, data=payload)`

The response_code is 200 and in livekit_clould, I see the room is created but the egress field is nothing [image](https://imgur.com/a/ewzQXFL). And also the video is not streaming successfully to the RTMP server.

Am I doing something wrong? Could you help me with this situation?

Thank you so much for your help.

**Comment by frostbyte73** [comment]
The `egress` field in CreateRoomRequest contains `room` with a room composite request, and `tracks` with auto track egress. For example:
```
payload = json.dumps({
                "name": roomName,
                "egress": {
                    "room": {
                        "room_name": roomName,
                        "layout": layout,
                        "stream": {
                            "urls": [f"rtmp://{host_ip}:{port}/live/{roomName}"]
                        }
                    }
                }
            })
```

**Comment by anhtu-phan** [comment]
@frostbyte73  thanks for the answer.

I have modified the payload as you suggest. it seems that streaming still doesn't work. Below is the log from `egress service`

`2023-02-17T14:21:47.416Z	INFO	egress	service/service_deprecated.go:65	request accepted	{"nodeID": "NE_JvPxjewER6Qd", "egressID": "EG_ANS4YcPrteMF", "requestID": "RPC_bwzmXmrw3Y2Z", "senderID": "ND_YlhDy3NV"}`
`2023-02-17T14:21:47.467Z	DEBUG	egress	server/main.go:150	handler launched	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:47.468Z	INFO	egress	redis/redis.go:82	connecting to redis	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF", "simple": true, "addr": "192.168.65.2:6379"}`
`2023-02-17T14:21:47.485Z	DEBUG	egress	web/source.go:58	launching xvfb	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF", "display": ":1627195973", "dims": "1920x1080x24"}`
`2023-02-17T14:21:47.485Z	DEBUG	egress	web/source.go:93	launching chrome	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF", "url": "https://egress-composite.livekit.io?layout=&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY3MzAxMDcsImlzcyI6ImRldmtleSIsIm5iZiI6MTY3NjY0MzcwNywic3ViIjoiRUdfQU5TNFljUHJ0ZU1GIiwidmlkZW8iOnsiY2FuUHVibGlzaCI6ZmFsc2UsImNhblB1Ymxpc2hEYXRhIjpmYWxzZSwiY2FuU3Vic2NyaWJlIjp0cnVlLCJoaWRkZW4iOnRydWUsInJlY29yZGVyIjp0cnVlLCJyb29tIjoiYTU2Njg5Y2UtOWE1Yi00ZDgyLWIxOGUtNTMzOTY5YzdjMjE4Iiwicm9vbUpvaW4iOnRydWV9fQ.06Fhkat8CSASZHDZKwpHVcOgGLWtffAkUH2b5uZ77zM&url=ws%3A%2F%2F192.168.65.2%3A7880"}`
`2023-02-17T14:21:48.481Z	DEBUG	egress	web/source.go:158	chrome log	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF", "args": [{"type":"string","value":"START_RECORDING"}], "executionContextId": 2, "timestamp": 1676643708480, "stackTrace": {"callFrames":[{"columnNumber":436562,"functionName":"startRecording","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":3965,"functionName":"","lineNumber":0,"scriptId":"7","url":"https://egress-composite.livekit.io/static/js/main.bd136baf.chunk.js"},{"columnNumber":559447,"functionName":"Xs","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":579850,"functionName":"ku","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":576491,"functionName":"","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":603445,"functionName":"S","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":603979,"functionName":"N","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":608518,"functionName":"","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":608633,"functionName":"l","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":607578,"functionName":"n","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"}]}, "type": "log"}`
`2023-02-17T14:21:48.488Z	DEBUG	egress	web/source.go:158	chrome log	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF", "args": [{"type":"string","value":"END_RECORDING"}], "executionContextId": 2, "timestamp": 1676643708488, "stackTrace": {"callFrames":[{"columnNumber":436627,"functionName":"endRecording","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":160841,"functionName":"Yi.emit","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":354483,"functionName":"value","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":350994,"functionName":"value","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":336153,"functionName":"","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":611571,"functionName":"l","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":611359,"functionName":"","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":612000,"functionName":"","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":4252,"functionName":"h","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"},{"columnNumber":4491,"functionName":"s","lineNumber":1,"scriptId":"8","url":"https://egress-composite.livekit.io/static/js/2.79eb0991.chunk.js"}]}, "type": "log"}`
`2023-02-17T14:21:48.495Z	INFO	egress	service/handler_deprecated.go:156	egress updated	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF", "egressID": "EG_ANS4YcPrteMF", "request_type": "room_composite", "output_type": "stream", "status": "EGRESS_ENDING"}`
`2023-02-17T14:21:48.496Z	DEBUG	egress	pipeline/pipeline.go:471	sending EOS to pipeline	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.500Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue_QTTY6bSVSvPV: A new thread needs to be created	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.500Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from flvmux0: A new thread needs to be created	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.500Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue3: A new thread needs to be created	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.500Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue4: A new thread needs to be created	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.500Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue2: A new thread needs to be created	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.500Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue0: A new thread needs to be created	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.500Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue3: A thread has entered its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.500Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue_QTTY6bSVSvPV: A thread has entered its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.500Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from flvmux0: A thread has entered its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue2: A thread has entered its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue4: A thread has entered its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from pulsesrc0: A new thread needs to be created	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue0: A thread has entered its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue1: A new thread needs to be created	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from ximagesrc0: A new thread needs to be created	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from pulsesrc0: A thread has entered its loop functio{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue1: A thread has entered its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[pipeline] NEW-CLOCK - Got a new clock	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.501Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from ximagesrc0: A thread has entered its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.503Z	DEBUG	egress	pipeline/pipeline.go:374	[audiosrcringbuffer0] STREAM-STATUS - Stream status from pulsesrc0: A thread has entered its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.503Z	DEBUG	egress	pipeline/pipeline.go:374	[pulsesrc0] LATENCY - Element's latency has changed	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:21:48.505Z	DEBUG	egress	pipeline/pipeline.go:374	[x264enc0] LATENCY - Element's latency has changed	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`

`2023-02-17T14:22:18.496Z	ERROR	egress	pipeline/pipeline.go:473	pipeline frozen	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`github.com/livekit/egress/pkg/pipeline.(*Pipeline).SendEOS.func1.1.1`
`	/workspace/pkg/pipeline/pipeline.go:473`
`2023-02-17T14:22:18.496Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue_QTTY6bSVSvPV: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.496Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from flvmux0: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.496Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue3: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.496Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue4: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.497Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue2: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.497Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue0: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.497Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from pulsesrc0: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.497Z	DEBUG	egress	pipeline/pipeline.go:374	[audiosrcringbuffer0] STREAM-STATUS - Stream status from pulsesrc0: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.497Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from queue1: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.497Z	DEBUG	egress	pipeline/pipeline.go:374	[src] STREAM-STATUS - Stream status from ximagesrc0: A thread has left its loop function	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.498Z	DEBUG	egress	pipeline/pipeline.go:643	pipeline stopped	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF"}`
`2023-02-17T14:22:18.516Z	WARN	egress	service/handler_deprecated.go:144	egress failed	{"nodeID": "NE_JvPxjewER6Qd", "handlerID": "EGH_VpkbQRjVV8mF", "egressID": "EG_ANS4YcPrteMF", "egressID": "EG_ANS4YcPrteMF", "request_type": "room_composite", "output_type": "stream", "error": "pipeline frozen"}`

**Comment by frostbyte73** [comment]
there's an `END_RECORDING` log 7ms after it started - it's a bug caused by spotty connection when only recording one person, see https://github.com/livekit/egress/issues/210
