### ISSUE TITLE
 listen tcp :443: bind: address already in use

### ISSUE THREAD

**Issue by zeteticl** [livekit/livekit#1452]
**Describe the bug**

**Server**
- Version: docker livekit 3.9
- Environment: rocky linux 9, vps
- any other information about your deployment setup
Using  The Apache HTTP Server

**To Reproduce**
1.   > sh init_script.sh
2. > systemctl start livekit-docker
3. > systemctl status livekit-docker
4.  error
Error: loading initial config: loading new config: layer4 app module: start: listen tcp :443: bind: address already in use

**Expected behavior**
Runing normal

**Screenshots**
![image](https://user-images.githubusercontent.com/23254376/220527937-a0450619-1033-41d8-a4a0-8a87ab0cc58a.png)

**Additional context**

**Comment by davidzhao** [comment]
By default, the deployment script uses 443. please ensure you don't have any other applications running that occupies that port.
