### ISSUE TITLE
Minimum required go version is now 1.19

### ISSUE THREAD

**Issue by typetetris** [livekit/livekit#1455]
**Describe the bug**
Mainly README.md lags behind. As `atomic.Bool` is used, the minimum required go version
to build this, is now 1.19.

**To Reproduce**
1. Install go 1.18
2. Try to build from master or v1.3.4

**Expected behavior**
The build should succeed.

**Screenshots**
```
       > pkg/rtc/subscriptionmanager.go:572:27: undefined: atomic.Bool
       > pkg/rtc/subscriptionmanager.go:573:27: undefined: atomic.Int32
       > pkg/rtc/subscriptionmanager.go:578:22: undefined: atomic.Pointer
```

**Comment by davidzhao** [comment]
fixed in #1479
