### ISSUE TITLE
crash with 'panic: runtime error: index out of range [-1]'

### ISSUE THREAD

**Issue by zk1173168848** [livekit/livekit#1467]
Describe the bug
crash with 'panic: runtime error: index out of range [-1]' once during 25 people call,

Server
Version: [1.3.4]
Environment: [ Red Hat 4.8.5-11]

Client
SDK: [js,ios,android]
Version: [1.3.2]

To Reproduce
25 client is connected to room
crash...
it's repeat 100%.
log:
panic: runtime error: index out of range [-1]
goroutine 61667741 [running]:
github.com/livekit/livekit-server/pkg/sfu.(*Forwarder).BandwidthRequested(0x1d?, {{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0}, {0x285113, ...}})
	/workspace/pkg/sfu/forwarder.go:607 +0x125
github.com/livekit/livekit-server/pkg/sfu.(*DownTrack).BandwidthRequested(0xc0191ba2c0)
	/workspace/pkg/sfu/downtrack.go:949 +0xa5
github.com/livekit/livekit-server/pkg/sfu.(*Track).BandwidthRequested(...)
	/workspace/pkg/sfu/streamallocator.go:1454
github.com/livekit/livekit-server/pkg/sfu.(*StreamAllocator).getExpectedBandwidthUsage(0x2?)
	/workspace/pkg/sfu/streamallocator.go:1041 +0x45
github.com/livekit/livekit-server/pkg/sfu.(*StreamAllocator).initProbe(0xc005edf0e0, 0xde993)
	/workspace/pkg/sfu/streamallocator.go:1070 +0x66
github.com/livekit/livekit-server/pkg/sfu.(*StreamAllocator).maybeProbeWithPadding(0x0?)
	/workspace/pkg/sfu/streamallocator.go:1183 +0xa9
github.com/livekit/livekit-server/pkg/sfu.(*StreamAllocator).maybeProbe(0xc005edf0e0)
	/workspace/pkg/sfu/streamallocator.go:1147 +0xa5
github.com/livekit/livekit-server/pkg/sfu.(*StreamAllocator).handleSignalPeriodicPing(0xc0020abf90?, 0xc0020abf01?)
	/workspace/pkg/sfu/streamallocator.go:567 +0xc9
github.com/livekit/livekit-server/pkg/sfu.(*StreamAllocator).handleEvent(0x49bae325e4d7?, 0x1b512a0?)
	/workspace/pkg/sfu/streamallocator.go:510 +0x4c
github.com/livekit/livekit-server/pkg/sfu.(*StreamAllocator).processEvents(0xc005edf0e0)
	/workspace/pkg/sfu/streamallocator.go:479 +0x7c
created by github.com/livekit/livekit-server/pkg/sfu.(*StreamAllocator).Start
	/workspace/pkg/sfu/streamallocator.go:194 +0x5a
[log.txt](https://github.com/livekit/livekit/files/10823049/log.txt)
config:
port: 7880
rtc:
    #udp_port: 7882
    port_range_start: 40000
    port_range_end: 50000
    tcp_port: 7881
    use_external_ip: false
keys:
    API85Y8nrcTM2Ew: NkAeLxiqGnNOsihTksTXuPPF6eTEcRSPlCj3BAvKFLV
logging:
    json: false
    level: info
prometheus_port: 6789
webhook:
  api_key: API85Y8nrcTM2Ew

**Comment by boks1971** [comment]
Apologise for this. This has been fixed. You can use latest in `master` to get the fix.

**Comment by zk1173168848** [comment]
thank you
