### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by zeteticl** [livekit/livekit#1480]
**Describe the bug**

**Server**
- Version: docker livekit 3.9
- Environment: rocky linux 9, vps
- any other information about your deployment setup
Using  The Apache HTTP Server and Cloudflare

**To Reproduce**
1.   > sh init_script.sh
2. > systemctl start livekit-docker
3. >  use https://livekit.io/connection-test and got `Internal error`

**Expected behavior**
Runing normal

**Screenshots**
![image](https://user-images.githubusercontent.com/23254376/221803020-6702012d-71ad-4ed4-b4b4-5faea620219f.png)

**Additional context**

**Comment by davidzhao** [comment]
livekit does not have version 3.9 (the latest is 1.5.6).

Please refer to [troubleshooting guide](https://docs.livekit.io/oss/deployment/vm/#troubleshooting) if it's a problem with setup.
