### ISSUE TITLE
Any Plan for Participant & Room Change Webhook Event?

### ISSUE THREAD

**Issue by calvin-seo** [livekit/livekit#1501]
In case of running multiple servers to control and listen LiveKit, one server could change metadata of rooms or participants via sdk, yet, the other servers cannot be notified via webhook now.

If livekit support Room & Participant change Webhook, I could remove the extra cost of sending action between my servers.

**Comment by davidzhao** [comment]
Currently there are no changes for LiveKit to rebroadcast actions that are coming from your server SDK.
