### ISSUE TITLE
livekit-server --version has exit code 1 in v1.3.5

### ISSUE THREAD

**Issue by Jake-Gather** [livekit/livekit#1513]
**Describe the bug**
After installing version `1.3.5` via homebrew, running
```
livekit-server --version
```
or
```
livekit-server --help
```
exits with code `1` instead of `0`.

**Server**
- Version: [1.3.5]

**Client**
- SDK: [e.g. js, ios]
- Version: [0.x.x]

**To Reproduce**
1. Run `brew install livekit`
2. Run `livekit-server --version` or `livekit-server --help`
3. Notice the failure exit code `1`

**Expected behavior**
Exit code `0`

**Screenshots**

**Additional context**

**Comment by ekharisma** [comment]
Hi @Jake-Gather , I do not have a mac machine. But, I try to reproduce it with a binary release and docker image and it works. Here is the screenshot.

![image](https://user-images.githubusercontent.com/65415399/224870558-4735bc5a-5850-4e27-8637-12fd29a09aa5.png)

**Comment by Jake-Gather** [comment]
I am on an M1 Mac and others on my team have reproduced the issue on their M1 Macs.

**Comment by davidzhao** [comment]
Looks like it does return 1 in this version. Thanks for the report. This appears to be a change in behavior in the CLI package that we are using (urfave/cli/v2)

```
% livekit-server --version
livekit-server version 1.3.5

% echo $?
1
```
