### ISSUE TITLE
Is it possible to support custom RTP extension headers?

### ISSUE THREAD

**Issue by CensorKo** [livekit/livekit#1558]
We attempted to add a custom RTP extension header in the SDP, but after capturing packets, we discovered that the added RTP extension header did not appear as expected in the RTP extension header. 

Therefore, we would like to know if LiveKit has its own custom extension header format. For example, a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/Custom-Data, the "Custom-Data" can be customized through the API to add a string that is included in the extension header of all outgoing RTP packets. 

Of course, it would also be possible to retrieve the corresponding "Custom-Data" through the API from incoming RTP packets.

But I think this could be an issue with the client SDK. RTP already has extension fields, but the default does not handle custom extension fields. LiveKit needs to specify the format and handle it in the client SDK.

@davidzhao @davidliu

**Comment by davidzhao** [comment]
We do not support custom RTP extensions. libwebrtc does not expose extensions to us.

What is your use case?

**Comment by CensorKo** [comment]
> 

We need to forward and distribute RTP packets at the edge node based on different RTP extension headers.

**Comment by davidzhao** [comment]
I'm not quite sure how that could be accomplished within LiveKit. You are welcome to try it in a fork though. I'd be happy to discuss if there's a generalizable approach that could benefit everyone. Closing as not planned for now.
