### ISSUE TITLE
LiveKit sometimes terminates during Redis Sentinel HA events

### ISSUE THREAD

**Issue by andwilde** [livekit/livekit#1559]
LiveKit server sometimes terminates within 30 seconds after Redis master switchover when connected to a Redis Sentinel setup. Can be reproduced with an idle LiveKit server, or one processing traffic.

The problem seems to be that sometimes a Redis Sentinel switchover to a new master does not take effect (even though logs indicate that it does) and LiveKit keeps trying to send keepalive messages to the former master. Eventually (within 30s) there is a timeout resulting in livekit-server termination.

Environment:
- Running Redis 7.0.9 and LiveKit 1.3.5 in a Kubernetes cluster (Rancher Desktop, others attempted as well with the same result)
- Redis has 3 data nodes and 3 sentinel nodes
- Running with a single livekit-server pod

Procedure to reproduce:
- Deploy the Redis Sentinel cluster
- Deploy LiveKit
- Observe which Redis node is the master
- Delete the pod which is the master
- Observe what LiveKit loses connection, and reconnects to the new master within a few seconds
- Repeat until the livekit-server terminates within 30 seconds after a switchover
- Observe that the newly restarted livekit-server pod can successfully connect to the master

Providing the following logs:
- livekit.log: the log from the initial livekit-server instance which terminates after a while
- livekit_restarted.log: the log from the restarted pod
- redis-0/1/2.log: logs from the last instances of the Redis data nodes

Noting down all steps with references to the logs below.

The part which I find odd is that before the final switchover to redis-0 (step 3 below), there is no log in redis-0.log which indicates that livekit-server actually connects to it (there should normally be a set of logs like "Accepted 10.42.0.1:46614"). Also, the log when the terminating livekit server tries to set itself in drain mode, it evidently tries to do that to the former master i.e. redis-1 which had IP address 10.42.0.112. So for some reason the last switchover to redis-0 did not take effect and left livekit in a state where it can't send and receive keepalive messages to itself (although there are no error logs). On some occasions I saw this log:

			logger.Errorw("status update delayed, possible deadlock", nil,

The logs show the following events:

1. livekit-server starts up and connects to redis-0 which is the current master.
livekit.log:
redis: 2023/03/29 15:36:41 sentinel.go:685: sentinel: new master="mymaster" addr="redis-0.redis.redis-sentinel.svc.cluster.local:6379"

2. Delete (using kubectl delete pod) the current master i.e. redis-0, after which redis-1 becomes master
livekit.log shows some error logs and successful reconnection to redis-1:
redis: 2023/03/29 15:37:26 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2023/03/29 15:37:29 sentinel.go:685: sentinel: new master="mymaster" addr="redis-1.redis.redis-sentinel.svc.cluster.local:6379"

3. Delete the new master (redis-1) after which the restarted redis-0 becomes master
livekit.log
redis: 2023/03/29 15:38:18 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis-0.log
1:S 29 Mar 2023 15:38:18.290 # Connection with master lost.
...
1:M 29 Mar 2023 15:38:19.723 * MASTER MODE enabled (user request from 'id=4 addr=10.42.0.114:37196 laddr=10.42.0.117:6379 fd=8 name=sentinel-c250c6b3-cmd age=43 idle=0 flags=x db=0 sub=0 psub=0 ssub=0 multi=4 qbuf=188 qbuf-free=16198 argv-mem=4 multi-mem=169 rbs=2072 rbp=1032 obl=45 oll=0 omem=0 tot-mem=19501 events=r cmd=exec user=default redir=-1 resp=2')
livekit.log:
redis: 2023/03/29 15:38:20 sentinel.go:685: sentinel: new master="mymaster" addr="redis-0.redis.redis-sentinel.svc.cluster.local:6379"

4. Observe how livekit-server terminates
livekit.log
2023-03-29T15:38:40.686Z        INFO    livekit server/main.go:265      exit requested, shutting down   {"signal": "terminated"}
...
2023-03-29T15:38:40.931Z        ERROR   livekit service/server.go:155   could not unregister node       {"error": "dial tcp 10.42.0.112:6379: connect: connection refused"}

5. Observe how the restarted livekit-server pod connects to redis-0
livekit_restarted.log
redis: 2023/03/29 15:38:41 sentinel.go:685: sentinel: new master="mymaster" addr="redis-0.redis.redis-sentinel.svc.cluster.local:6379"
redis-0.log
1:M 29 Mar 2023 15:38:41.461 - Accepted 10.42.0.1:46614
1:M 29 Mar 2023 15:38:41.467 - Accepted 10.42.0.1:46616
1:M 29 Mar 2023 15:38:41.474 - Accepted 10.42.0.1:46618
1:M 29 Mar 2023 15:38:41.477 - Accepted 10.42.0.1:46620
1:M 29 Mar 2023 15:38:41.484 - Accepted 10.42.0.1:46622
1:M 29 Mar 2023 15:38:41.490 - Accepted 10.42.0.1:46624
1:M 29 Mar 2023 15:38:41.494 - Accepted 10.42.0.1:46626
1:M 29 Mar 2023 15:38:41.498 - Accepted 10.42.0.1:46628
1:M 29 Mar 2023 15:38:41.512 - Accepted 10.42.0.1:46630
1:M 29 Mar 2023 15:38:41.525 - Accepted 10.42.0.1:46632
1:M 29 Mar 2023 15:38:41.529 - Accepted 10.42.0.1:46634
1:M 29 Mar 2023 15:38:41.703 - Accepted 10.42.0.1:46636
1:M 29 Mar 2023 15:38:41.719 - Accepted 10.42.0.1:46638

[livekit.log](https://github.com/livekit/livekit/files/11103147/livekit.log)
[livekit_restarted.log](https://github.com/livekit/livekit/files/11103148/livekit_restarted.log)
[redis-0.log](https://github.com/livekit/livekit/files/11103149/redis-0.log)
[redis-1.log](https://github.com/livekit/livekit/files/11103150/redis-1.log)
[redis-2.log](https://github.com/livekit/livekit/files/11103151/redis-2.log)

**Comment by andwilde** [comment]
The issue seems to be caused by a very long default timeout on Redis connection establishment after attempting to reconnect to the new master, i.e. the DialTimeout in the Redis UniversalClient. It seems like this timeout is by default one minute.

The problem I was observing was a race condition triggered by LiveKit publishing a KeepAlive message shortly after the former master went down but before the new master was picked up by go-redis. The publish request would hang to the old master until the TCP DialTimeout expired after 1 minute.

A way to fix could be to request shorter timeouts when calling redis.NewUniversalClient e.g. (in protocol/redis.go):

if len(conf.SentinelAddresses) > 0 {
        logger.Infow("connecting to redis", "sentinel", true, "addr", conf.SentinelAddresses, "masterName", conf.MasterName)
        rcOptions = &redis.UniversalOptions{
            Addrs:            conf.SentinelAddresses,
            SentinelUsername: conf.SentinelUsername,
            SentinelPassword: conf.SentinelPassword,
            MasterName:       conf.MasterName,
            Username:         conf.Username,
            Password:         conf.Password,
            DB:               conf.DB,
            TLSConfig:        tlsConfig,
            DialTimeout: time.Duration(2) * time.Second,
            ReadTimeout: time.Duration(200) * time.Millisecond,
            WriteTimeout: time.Duration(200) * time.Millisecond,
        }

Although ideally configurable.

**Comment by davidzhao** [comment]
Hey Andy, do you want to make a PR against it? We don't use Redis Sentinel here and it'd be difficult to validate which settings work best.

I agree it should be configurable, but if we can pick sane defaults, that'd make it easier for most folks
