### ISSUE TITLE
Connecting to xxx.livekit.cloud occasionally failed

### ISSUE THREAD

**Issue by lawshachMa** [livekit/livekit#1573]
**Describe the bug**
Connecting to livekit.cloud occasionally fails，region: China
<img width="697" alt="image" src="https://user-images.githubusercontent.com/122844706/229440675-b8504950-e5e5-4472-b171-b3ea5f3540e7.png">

It may be related to the server region， any plans to deploy servers in the Asia region?

**Comment by davidzhao** [comment]
We have servers in the asia region, in Singapore and Tokyo (with more coming in the future). I think the problem you are seeing may be related to firewall filtering certain packets out.

Due to the firewall situation in China, we do not have control over the situation unless we deploy within China.
