### ISSUE TITLE
Allow clients without data channels

### ISSUE THREAD

**Issue by w01** [livekit/livekit#1575]
A connection option that does not force a client to establish data channels would be helpful for simple integrations, and required for future WHIP/WHEP support. Currently a participant that fails to establish the reliable/lossy data channels will be disconnected after one minute, because they cannot reach a participant ACTIVE state. This makes it impossible to implement a WHIP endpoint without modifying LiveKit internals, because a generic WHIP client cannot have implementation-specific knowledge.

It may also be helpful to avoid sending data-channel SDP offers to clients marked as lacking data-channel capability. This would simplify future WHEP support. Currently a receive-only client must handle at least two offer/answer negotiations: one for the data channels and one for media. The media offer will not be sent until the data channel offer is answered.  This would be a problem for a generic WHEP client, which can only handle a single offer/answer transaction.  (Note - At the moment only the server-generated offer mode of WHEP could be practically implemented, since LiveKit assumes that the party sending the offer also sends the media.)

**Comment by davidzhao** [comment]
We are indeed adding WHIP/WHEP support. With WHIP, it'll be implemented in our Ingress service; so it will not directly reach livekit-server.

For WHEP support though, this issue would still be relevant. Though we'll need a different signaling endpoint for that.

**Comment by johan149** [comment]
> We are indeed adding WHIP/WHEP support. With WHIP, it'll be implemented in our Ingress service; so it will not directly reach livekit-server.
> 
> For WHEP support though, this issue would still be relevant. Though we'll need a different signaling endpoint for that.

That's really awesome to hear that you guys are adding WHIP soon!
