### ISSUE TITLE
Using Livekite in the production environment without using a domain

### ISSUE THREAD

**Issue by mojtabanpe** [livekit/livekit#1604]
Our project is implemented in the internal environment of the company and we cannot assign a domain to it. How can we use Livekit using IP in the production environment?

**Comment by mojtabanpe** [comment]
I use it like this:
room.connect(wss://my-ip:7880,...);
But the browser cannot establish the web socket connection.

**Comment by jibon57** [comment]
wss require ssl enabled. For your case should be ws.

**Comment by mojtabanpe** [comment]
in our case we have to use ssl certificate with ip and the browser cannot work with http.

**Comment by davidzhao** [comment]
As long as you have the certs figured out, livekit itself does not require any domains. SSL certs are a browser requirement. 

Are you seeing anywhere that requires you to provide a domain?

**Comment by mojtabanpe** [comment]
in livekit document: "The SSL certificate must be signed by a trusted certificate authority; self-signed certs do not work here".
Our problem is that all the nodes do not have Internet, but the server IP must be up with https.

**Comment by davidzhao** [comment]
That's stating a browser requirement. Browsers do not generally trust self-signed certs.
