### ISSUE TITLE
Feature request: Getting the bitrate of published tracks

### ISSUE THREAD

**Issue by Unbreathable** [livekit/livekit#1618]
Hello,
as we all know, no-one wants their traffic on LiveKit Cloud or their own server to be consumed by just a few users. To prevent that you can of course implement a bitrate limit on the client, but what if the user is able to modify the client like in an open-source project (that is hosted by the owner of the project)?

### The problem
The app I'm currently working on is open-source and can be modified by anyone for that matter which means ,as stated before, that I do not have a way to limit the traffic a certain user consumes. A user could just be streaming at 4K 60FPS with a 20k bitrate and the server wouldn't prevent it from what I've seen. 

### The solution
From what I've been able to see there is currently no way to get the bitrate the client publishes on the server or to at least limit it by a certain constant in for example the permissions of the user. For that reason I would like to request a way to get the bitrate of published tracks on the LiveKit server. A (probably) easy solution is to notify the backend of the application by using the webhook system. There is already a webhook for when a track is being published, but the only thing you can retrieve from it is resolution and video quality (low, medium or high). It would be cool if there was a way to also get the bitrate. You could then check if the bitrate is higher than the limit you set in your application and then remove the participant by using the server SDK (or mute their track).

**Comment by davidzhao** [comment]
As discussed in Slack, WebRTC clients are free to publish at any bitrate (and that bitrate is dynamic). This doesn't fit very well as a webhook event.

It's possible to enforce this with the Go SDK, where a bot could watch the stream bitrate and act on that information.
