### ISSUE TITLE
VP9 is disabled in 1.4.1 release but it is enabled in master branch

### ISSUE THREAD

**Issue by itzloop** [livekit/livekit#1627]
**Describe the bug**

Hi, hope you all doing well.
I was trying to enable VP9 in my production setup but sadly i couldn't make it happen. It wasn't showing as an **rtpmap** in **answer** sent by the **server**. Then i tried to test this locally by first going to the master branch and every thing worked as expected. Then i tried the same thing but in **v1.4.1 tag** and couldn't enable VP9. After a short debugging session i came across this code in `pkg/rtc/mediaengine.go`:

```go
func registerCodecs(me *webrtc.MediaEngine, codecs []*livekit.Codec, rtcpFeedback RTCPFeedbackConfig) error {
	...
	for _, codec := range []webrtc.RTPCodecParameters{
		...
		/*
			{
				RTPCodecCapability: webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeVP9, ClockRate: 90000, SDPFmtpLine: "profile-id=0", RTCPFeedback: rtcpFeedback.Video},
				PayloadType:        98,
			},
			{
				RTPCodecCapability: webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeVP9, ClockRate: 90000, SDPFmtpLine: "profile-id=1", RTCPFeedback: rtcpFeedback.Video},
				PayloadType:        100,
			},
		*/
		...
	} {
		if isCodecEnabled(codecs, codec.RTPCodecCapability) {
			if err := me.RegisterCodec(codec, webrtc.RTPCodecTypeVideo); err != nil {
				return err
			}
		}
	}
	return nil
}
```

As you can see VP9 is commented (pr #1004)  but not in the master branch. An explanation on why VP9 was commented and if it's ok for me to just uncomment this would be much appreciated.

Thanks. <3

**Server**
- Version: 1.4.1
- Environment: Bare Metal with docker

**Client**
I was using [Example Client](https://example.livekit.io/)
- SDK: js

**To Reproduce**
1. Switch to v1.4.1 tag
2. Enable VP9 in `RoomConfig`
3. Start the server and connect to a room
4. Debug the remote SDP with chrome's webrtc-internals

**Expected behavior**
I was expecting enabling VP9 had the same effect in master and v1.4.1 and if not a clear explanation to avoid confusion.

**Comment by davidzhao** [comment]
official vp9 support has not been released yet. it should be in place soon. (likely 1.5.0)

**Comment by itzloop** [comment]
Hi again.
Thanks for the quick reply. I have 2 questions:

1- Can you give an estimation on the release date of 1.5.0 and also
2- What are the challenges of enabling it rn by myself?

**Comment by davidzhao** [comment]
1.5 is about a month out. we have not fully tested it end to end, so it's difficult to say what challenges/issues you might run into.
