### ISSUE TITLE
Minimum requirements to run on VM

### ISSUE THREAD

**Issue by pinceladasdaweb** [livekit/livekit#1655]
This is not a bug, I was looking in the documentation for the minimum requirements to run the project in a VM (CPU and Memory) but I didn't find it.

Does anyone know how to inform me? And congratulations for the great work.

**Comment by davidzhao** [comment]
Hi there, there aren't any minimum requirements for LiveKit. It will run on the smallest instance that you are able to get your hands on. (as long as it has more than 30MB of memory). The rest depends on what your workload is.
