### ISSUE TITLE
State of VP9 support

### ISSUE THREAD

**Issue by mikebevz** [livekit/livekit#1662]
What's the current state of VP9 support in LiveKit?

I tried to screenshare using js sdk 1.9.1 and when vp9 is set as a video codec then I see it as simulcasted vp8 stream. Is it expected behavior?

**Comment by davidzhao** [comment]
VP9 SVC support will be coming in 1.4.2. Initially it's not enabled by default though.

**Comment by davidzhao** [comment]
This is fixed [here](https://github.com/livekit/client-sdk-js/pull/731) and included in the latest Client SDK release
