### ISSUE TITLE
How to increase the bitrate?

### ISSUE THREAD

**Issue by onthegit** [livekit/livekit#1713]
After doing some tests with livekit, the received streams from the browser (livekit dev server on localhost), using the examples, I could not find way to increase the bitrate above 300kbps, streamed from both windows and linux platforms. Anything set above 300kbps causes frames to drop.

```
ScreenShareCaptureOptions = {
  audio: true,
  suppressLocalAudioPlayback: true,
  systemAudio: "include",
  resolution: {
    width: 1920,
    height: 1080,
    aspectRatio: 1920 / 1080,
    frameRate: 30,
  },
}

VideoEncoding = {
  maxFramerate: 2_500_000,
  maxBitrate: 30,
}
```

Does not change the bitrate.

How can higher bitrate be set with livekit?

**Comment by onthegit** [comment]
From:
https://stackoverflow.com/questions/57653899/how-to-increase-the-bitrate-of-webrtc

How to set x-google-max-bitrate  with livekit?

**Comment by davidzhao** [comment]
I'm assuming this is Unity Web SDK? You've flipped bitrate and framerate. Try

```
VideoEncoding = {
  maxFramerate: 30,
  maxBitrate: 2_500_000,
}
```

**Comment by onthegit** [comment]
Hello,
thanks for your reply.  Client-sdk-js is used.

Sorry, my mistake for the bitrate! The bitrate is increased but (however the resolution is not the one requested). 

When i use mediarecorder with getdisplaymedia  and send the mediarecorder chunks to websocket server, then the resolution is 1920x1080, however if via livekit the max resolution is 960x540. 

I get the track for both mediarecorder and livekit publishing via client.createScreenTracks with the same constraints for resolution.

**Comment by onthegit** [comment]
There is another problem I am encountering with the oggwriter and that is if the audio is above 96000 kbps it is not playable and between 48000 and 96000 it has invalid CRC 
https://github.com/pion/webrtc/issues/2472

**Comment by btakita** [comment]
@onthegit How did you manage to increase the bitrate?
