### ISSUE TITLE
Participant does not have video track listed for other users even though it is published

### ISSUE THREAD

**Issue by alefebspp** [livekit/livekit#1739]
**Describe the bug**
For some reason, some users (using mobile devices) do not have their video tracks displayed to other users. They can see their videos and other users' videos, but their video tracks are not displayed to others. Their audio tracks are listed correctly. What could be the cause of this?
Edit: The publication of the participant's video track is not recognized in the room's event, only the publication of the audio track

**Server**
- Version: [0.x.x]
- Environment: [e.g. local dev, EKS]
- any other information about your deployment setup

**Client**
- SDK: [e.g. js, ios]
- Version: [0.x.x]

**To Reproduce**
1. The description already explains everything clearly

**Expected behavior**
All users get their video tracks listed to othe participants

**Screenshots**

**Additional context**

**Comment by davidzhao** [comment]
please provide details as requested, including SDK & server version.

> their video tracks are not displayed to others

how is this determined?

**Comment by davidzhao** [comment]
> I dont know if i provided the correct information about server and client on the description of the bug.

you did not. feel free to edit the issue in order to include them.

unfortunately, there is insufficient information for us to be able to help here. `some users tracks aren't available to others` is too vague.

**Comment by HarrisonKeeling** [comment]
I've encountered this same issue.  Firefox Mobile 117.0 on Android 13 when using simulcast and vp8, `TRACK_PUBLISH_REQUESTED` for `CAMERA` is observed but it never publishes.  `MICROPHONE` is fine.

They can subscribe OK to others

**Comment by davidzhao** [comment]
@HarrisonKeeling, are building with JS SDK or react-native?

**Comment by HarrisonKeeling** [comment]
> @HarrisonKeeling, are building with JS SDK or react-native?

JS SDK

**Comment by davidzhao** [comment]
Thanks, my guess is even though the symptoms are the same, you are seeing a different issue compared to what this issue is. Do you mind filing a bug in the [JS SDK repo](https://github.com/livekit/client-sdk-js)?

we'll dig into it.

**Comment by HarrisonKeeling** [comment]
Thanks!  See https://github.com/livekit/client-sdk-js/issues/884
