### ISSUE TITLE
Got [ConnectException] Timed out waiting for EnginePeerStateUpdatedEvent 

### ISSUE THREAD

**Issue by danntee** [livekit/livekit#1758]
Hello.This project is alsome.But when i try use the livekit server deployed on aliyun and client-sdk-flutter which runs on my local machine,these is a problem.

![err](https://github.com/livekit/livekit/assets/24841633/d9a6316e-2860-4c47-bbbf-c4365bc2befb)

Here is the log from client
[client.log](https://github.com/livekit/livekit/files/11609051/client.log)

Here is the log from server
[server.log](https://github.com/livekit/livekit/files/11609072/server.log)

**Comment by davidzhao** [comment]
you need a CA cert and a domain. see [deployment docs](https://docs.livekit.io/oss/deployment/#domain,-ssl-certificates,-and-load-balancer).

for the server to be viable, please refer to the [connection test tool](https://livekit.io/connection-test).

**Comment by hautvfami** [comment]
My connection test is PASS and I can join meet at https://meet.livekit.io/?tab=custom but i'm facing the same error message on flutter client
![image](https://github.com/livekit/livekit/assets/21011312/1db74030-d202-4534-aaff-6518fb41bd21)

**Comment by canaanjin** [comment]
楼主你好 请问你解决这个问题了没有？我也遇到了，但是情况是这样的。
我也部署在阿里云服务器上，现在在ios（无线和流量）以及安卓流量的网络环境下都出现这个问题|

安卓的无线网络倒是没问题

我没有弄域名和https 直接ws:ip:7880 进行连接的

本地内网环境到都是正常的
