### ISSUE TITLE
Using Livekit VM as a TURN Server.

### ISSUE THREAD

**Issue by kaumudpa** [livekit/livekit#1766]
Can we use a deployed LiveKit VM as an Independent Turn Server as well? - May be to use directly with vanilla WEBRTC?

If yes what will be auth credentials for the same?

**Comment by davidzhao** [comment]
That is not a configuration that we support. This is because the TURN service is integrated with the rest of LiveKit for credential exchange. There isn't a way to authenticate with the TURN server unless it's a LiveKit client
