### ISSUE TITLE
FE: Ability to prefix for all redis keys using arbitrary string

### ISSUE THREAD

**Issue by alexeyatbluescape** [livekit/livekit#1777]
**Describe the bug**
Use case: multitenant cluster where each tenant requires livekit component. All tenants share the same cache Redis instance.
Currently, we can separate keys using db index: https://github.com/livekit/livekit/blob/master/config-sample.yaml#LL11C1-L11C1
But this limits us to only 16 tenants and does not allow us to apply the generic Redis prefix strategy we utilize across components globally (the string that contains cluster + tenant + component to ensure no collision of keys).

**Server**
- Version: 1.4.3
- Environment: EKS
- Microservices stack with livekit and turn server as component in the stack on per instances bases.

**Client**
- SDK: 1.6.5
- Version: NA

**To Reproduce**
NA

**Expected behavior**
The ability to add string prefix into the configuration file that will be used to prefix all Redis keys managed by livekit.

**Screenshots**
NA.

**Additional context**
This is a pretty common enterprise-grade use case, other might find it helpful as well.

**Comment by grootgordon** [comment]
This feature relies on go-redis. Look forward to go-redis supporting this.
more discuss: https://github.com/redis/go-redis/issues/607
