### ISSUE TITLE
page load error net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by 277861535** [livekit/livekit#1830]
The following are the questions：
WARN egress service/handler.go:195 egress failed {"nodeID": "NE_CvudFrVEmKEV", "handlerID": "EGH_63aEZWkwDWx8", "clusterID": "", "egressID": "EG_fvdQADkLTBcW", "egressID": "EG_fvdQADkLTBcW", "request_type": "room_composite", "output_type": "stream", "error": "page load error net::ERR_CONNECTION_REFUSED"}
2023-06-27T06:17:23.970Z ERROR egress service/handler.go:216 failed to send update {"nodeID": "NE_CvudFrVEmKEV", "handlerID": "EGH_63aEZWkwDWx8", "clusterID": "", "egressID": "EG_fvdQADkLTBcW", "error": "no response from servers"}

What is the reason and how to solve it.

**Comment by davidzhao** [comment]
please file this issue to the Egress repo with detailed repro steps along with versions used. It's not possible understand how you got into this scenario.
