### ISSUE TITLE
建议支持1to1场景下的P2P模式

### ISSUE THREAD

**Issue by smalldok** [livekit/livekit#1879]
体验了LIVEKIT非常不错，代码很出色，我们有1对1的场景，而且流量带宽也有要求，所以想知道livekit后续是否有支持P2P的计划？
望回复!

**Comment by boks1971** [comment]
> It is very good to experience LIVEKIT, the code is very good, we have a 1-to-1 scenario, and there are also requirements for traffic bandwidth, so I would like to know whether livekit has a plan to support P2P in the future?
Hope to reply!

Thank you for your kind words. There are no plans currently to support p2p.
