### ISSUE TITLE
Can both the internal IP and external IP be used for connections?

### ISSUE THREAD

**Issue by fightroad** [livekit/livekit#1898]
Can both the internal IP and external IP be used for connections? The server is located in a private network (not connected to the Internet) and the corresponding ports are opened through the firewall for Internet access. The internal IP is used for computers within the private network, while the external IP is used for computers outside the network. Jitsi allows customizing the publication of both the internal and external IP addresses. However, with Livekit, when the use_external_ip setting is enabled, only the external IP can be set, which causes issues for computers within the private network.

**Comment by davidzhao** [comment]
LiveKit does not offer both public and private IPs at the moment. 

If they are on separate network interfaces, then we can offer both addresses. Otherwise you could try using TURN to achieve this today. i.e. with `use_external_ip` set to false, and enabling TURN/UDP.

**Comment by f0re1gnKey** [comment]
This is very useful and easy to implement.

Why not ?

**Comment by f0re1gnKey** [comment]
> LiveKit does not offer both public and private IPs at the moment.
> 
> If they are on separate network interfaces, then we can offer both addresses. Otherwise you could try using TURN to achieve this today. i.e. with `use_external_ip` set to false, and enabling TURN/UDP.

This is very useful and easy to implement.

Why not ?

**Comment by fightroad** [comment]
I'm currently using an indirect method to set the external IP to the second network card. This allows me to expose both the internal and external IPs. Unfortunately, it's the only way.

**Comment by amwu** [comment]
@fightroad  Please teach me how it is implemented

**Comment by fightroad** [comment]
把外网固定ip设置到 内网这台服务器的网卡上，让该网卡拥有两个ip。这样livekit可以发布两个ip。内网可以走内网的ip连接上。外网可以走外网的ip连接。
