### ISSUE TITLE
livekit is unable to connect to reids

### ISSUE THREAD

**Issue by salmanqasim67** [livekit/livekit#1901]
#these are the logs
sudo docker-compose logs
can anyone help me to resolve this issue

Attaching to livekit_livekit_1, livekit_redis_1
redis_1    | 1:C 25 Jul 2023 09:05:01.001 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 25 Jul 2023 09:05:01.001 # Redis version=6.2.13, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 25 Jul 2023 09:05:01.001 # Configuration loaded
redis_1    | 1:M 25 Jul 2023 09:05:01.002 * Increased maximum number of open files to 10032 (it was originally set to 1024).
redis_1    | 1:M 25 Jul 2023 09:05:01.002 * monotonic clock: POSIX clock_gettime
redis_1    | 1:M 25 Jul 2023 09:05:01.004 * Running mode=standalone, port=6379.
redis_1    | 1:M 25 Jul 2023 09:05:01.004 # Server initialized
redis_1    | 1:M 25 Jul 2023 09:05:01.005 * Loading RDB produced by version 6.2.13
redis_1    | 1:M 25 Jul 2023 09:05:01.005 * RDB age 315 seconds
redis_1    | 1:M 25 Jul 2023 09:05:01.005 * RDB memory usage when created 0.77 Mb
redis_1    | 1:M 25 Jul 2023 09:05:01.005 # Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1    | 1:M 25 Jul 2023 09:05:01.005 * DB loaded from disk: 0.001 seconds
redis_1    | 1:M 25 Jul 2023 09:05:01.005 * Ready to accept connections
redis_1    | 1:signal-handler (1690275917) Received SIGTERM scheduling shutdown...
redis_1    | 1:M 25 Jul 2023 09:05:17.242 # User requested shutdown...
redis_1    | 1:M 25 Jul 2023 09:05:17.242 * Saving the final RDB snapshot before exiting.
redis_1    | 1:M 25 Jul 2023 09:05:17.248 * DB saved on disk
redis_1    | 1:M 25 Jul 2023 09:05:17.248 # Redis is now ready to exit, bye bye...
redis_1    | 1:C 25 Jul 2023 09:05:21.901 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 25 Jul 2023 09:05:21.902 # Redis version=6.2.13, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 25 Jul 2023 09:05:21.902 # Configuration loaded
redis_1    | 1:M 25 Jul 2023 09:05:21.902 * Increased maximum number of open files to 10032 (it was originally set to 1024).
redis_1    | 1:M 25 Jul 2023 09:05:21.902 * monotonic clock: POSIX clock_gettime
redis_1    | 1:M 25 Jul 2023 09:05:21.902 * Running mode=standalone, port=6379.
redis_1    | 1:M 25 Jul 2023 09:05:21.902 # Server initialized
redis_1    | 1:M 25 Jul 2023 09:05:21.903 * Loading RDB produced by version 6.2.13
redis_1    | 1:M 25 Jul 2023 09:05:21.903 * RDB age 4 seconds
redis_1    | 1:M 25 Jul 2023 09:05:21.903 * RDB memory usage when created 0.77 Mb
redis_1    | 1:M 25 Jul 2023 09:05:21.903 # Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1    | 1:M 25 Jul 2023 09:05:21.903 * DB loaded from disk: 0.000 seconds
redis_1    | 1:M 25 Jul 2023 09:05:21.903 * Ready to accept connections
redis_1    | 1:signal-handler (1690276703) Received SIGTERM scheduling shutdown...
redis_1    | 1:M 25 Jul 2023 09:18:24.048 # User requested shutdown...
redis_1    | 1:M 25 Jul 2023 09:18:24.048 * Saving the final RDB snapshot before exiting.
redis_1    | 1:M 25 Jul 2023 09:18:24.056 * DB saved on disk
redis_1    | 1:M 25 Jul 2023 09:18:24.056 # Redis is now ready to exit, bye bye...
redis_1    | 1:C 25 Jul 2023 09:22:05.373 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 25 Jul 2023 09:22:05.373 # Redis version=6.2.13, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 25 Jul 2023 09:22:05.373 # Configuration loaded
redis_1    | 1:M 25 Jul 2023 09:22:05.373 * Increased maximum number of open files to 10032 (it was originally set to 1024).
redis_1    | 1:M 25 Jul 2023 09:22:05.373 * monotonic clock: POSIX clock_gettime
redis_1    | 1:M 25 Jul 2023 09:22:05.374 * Running mode=standalone, port=6379.
redis_1    | 1:M 25 Jul 2023 09:22:05.374 # Server initialized
redis_1    | 1:M 25 Jul 2023 09:22:05.375 * Loading RDB produced by version 6.2.13
redis_1    | 1:M 25 Jul 2023 09:22:05.375 * RDB age 221 seconds
redis_1    | 1:M 25 Jul 2023 09:22:05.375 * RDB memory usage when created 0.77 Mb
redis_1    | 1:M 25 Jul 2023 09:22:05.375 # Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1    | 1:M 25 Jul 2023 09:22:05.375 * DB loaded from disk: 0.000 seconds
redis_1    | 1:M 25 Jul 2023 09:22:05.375 * Ready to accept connections
redis_1    | 1:signal-handler (1690277002) Received SIGTERM scheduling shutdown...
redis_1    | 1:M 25 Jul 2023 09:23:22.840 # User requested shutdown...
redis_1    | 1:M 25 Jul 2023 09:23:22.840 * Saving the final RDB snapshot before exiting.
redis_1    | 1:M 25 Jul 2023 09:23:22.847 * DB saved on disk
redis_1    | 1:M 25 Jul 2023 09:23:22.847 # Redis is now ready to exit, bye bye...
redis_1    | 1:C 25 Jul 2023 09:27:21.884 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 25 Jul 2023 09:27:21.884 # Redis version=6.2.13, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 25 Jul 2023 09:27:21.884 # Configuration loaded
redis_1    | 1:M 25 Jul 2023 09:27:21.885 * Increased maximum number of open files to 10032 (it was originally set to 1024).
redis_1    | 1:M 25 Jul 2023 09:27:21.885 * monotonic clock: POSIX clock_gettime
redis_1    | 1:M 25 Jul 2023 09:27:21.885 * Running mode=standalone, port=6379.
redis_1    | 1:M 25 Jul 2023 09:27:21.885 # Server initialized
redis_1    | 1:M 25 Jul 2023 09:27:21.885 * Loading RDB produced by version 6.2.13
redis_1    | 1:M 25 Jul 2023 09:27:21.885 * RDB age 239 seconds
redis_1    | 1:M 25 Jul 2023 09:27:21.885 * RDB memory usage when created 0.77 Mb
redis_1    | 1:M 25 Jul 2023 09:27:21.885 # Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1    | 1:M 25 Jul 2023 09:27:21.885 * DB loaded from disk: 0.000 seconds
redis_1    | 1:M 25 Jul 2023 09:27:21.885 * Ready to accept connections
redis_1    | 1:signal-handler (1690277910) Received SIGTERM scheduling shutdown...
redis_1    | 1:M 25 Jul 2023 09:38:30.693 # User requested shutdown...
redis_1    | 1:M 25 Jul 2023 09:38:30.693 * Saving the final RDB snapshot before exiting.
redis_1    | 1:M 25 Jul 2023 09:38:30.700 * DB saved on disk
redis_1    | 1:M 25 Jul 2023 09:38:30.700 # Redis is now ready to exit, bye bye...
livekit_1  | 2023-07-25T09:05:01.727Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | 2023-07-25T09:05:22.362Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:05:43.550Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:06:04.789Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp: i/o timeout
livekit_1  | 2023-07-25T09:06:26.008Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:06:47.422Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | 2023-07-25T09:06:50.431Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:07:11.839Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp: i/o timeout
livekit_1  | 2023-07-25T09:07:33.149Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:07:54.639Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:08:15.984Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:08:37.309Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:08:58.606Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:09:19.916Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:09:41.484Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:10:02.952Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:10:24.443Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:10:45.852Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp: i/o timeout
livekit_1  | 2023-07-25T09:11:07.245Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp: i/o timeout
livekit_1  | 2023-07-25T09:11:28.769Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp: i/o timeout
livekit_1  | 2023-07-25T09:11:50.172Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp: i/o timeout
livekit_1  | 2023-07-25T09:12:11.540Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:12:32.881Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:12:54.308Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:13:15.656Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:13:37.962Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:13:59.219Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:14:20.648Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:14:42.082Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:15:03.610Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:15:25.090Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:15:46.523Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:16:07.940Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:16:29.751Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:16:51.204Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:17:12.650Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:17:34.084Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:17:55.748Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:18:17.201Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | 2023-07-25T09:21:34.477Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:21:55.878Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:22:17.369Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:22:38.901Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:23:00.431Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:23:21.962Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | 2023-07-25T09:27:22.347Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:27:43.533Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:28:04.961Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:28:26.214Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:28:47.685Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:29:09.142Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:29:30.425Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:29:51.681Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:30:13.156Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:30:34.513Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:30:55.819Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:31:17.222Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:31:38.571Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:31:59.935Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:32:21.269Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:32:42.655Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:33:04.089Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:33:25.503Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:33:46.842Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:34:08.176Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:34:29.588Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:34:50.950Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:35:12.100Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:35:33.494Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:35:55.140Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:36:16.499Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:36:38.067Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:36:59.422Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:37:20.899Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:37:42.798Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:38:04.450Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}
livekit_1  | unable to connect to redis: dial tcp 3.64.163.50:6379: i/o timeout
livekit_1  | 2023-07-25T09:38:25.770Z	INFO	livekit	service/wire_gen.go:132	using multi-node routing via redis	{"addr": "redis.host:6379"}

**Comment by davidzhao** [comment]
Please make sure you can connect to Redis through the livekit container. This is an issue with your environment.

**Comment by salmanqasim67** [comment]
how to setup environment

**Comment by salmanqasim67** [comment]
> Please make sure you can connect to Redis through the livekit container. This is an issue with your environment.

how to setup its environment
