### ISSUE TITLE
SSH Tunnel

### ISSUE THREAD

**Issue by tmtong** [livekit/livekit#1903]
I got computer A on the internet and anothert computer B behind firewall that only allow outward traffic. I would like to have clients connect to computer A, and clients (without internet access, and also behind firewall) to connect to computer B
What I am trying to do is to have the server run on computer B and use SSH tunnel to create a port tunnel the traffic to computer B by doing this
computer b> /usr/local/bin/livekit-server --config /etc/livekit.yaml --bind 0.0.0.0

Here is my livekit.yaml
```
port 7880
rtc:
  # UDP ports to use for client traffic.
  # this port range should be open for inbound traffic on the firewall
  # port_range_start: 50000
  # port_range_end: 60000

  # when set, LiveKit enable WebRTC ICE over TCP when UDP isn't available
  # this port *cannot* be behind load balancer or TLS, and must be exposed on the node
  # WebRTC transports are encrypted and do not require additional encryption
  # only 80/443 on public IP are allowed if less than 1024
  tcp_port: 7881
```

On computer b>  livekit-cli --verbose join-room --room room01 --identity user03 --publish-demo --api-key APIKEY --api-secret SECRET --url ws://localhost:7880
2023/07/25 21:28:38 "level"=0 "msg"="received offer for subscriber"
2023/07/25 21:28:38 "level"=0 "msg"="ICE connected"
2023-07-25T21:28:38.867+0800    INFO    livekit-cli     livekit-cli/join.go:124 connected to room       {"room": "room01"}
2023/07/25 21:28:38 "level"=0 "msg"="published simulcast track" "name"="demo" "source"="CAMERA"
2023/07/25 21:28:39 "level"=0 "msg"="successfully set publisher answer"

computer b> ssh computerA -R 7880:localhost:7880 -R 7881:localhost:7881

On computer a> netstat -an | grep LISTEN
It listed 7880 and 7881

On computer a>  livekit-cli --verbose join-room --room room01 --identity user03 --publish-demo --api-key APIKEY --api-secret SECRET --url ws://localhost:7880

2023/07/25 20:20:36 "level"=0 "msg"="received offer for subscriber"
could not connect after timeout

Here is the server
[server.txt](https://github.com/livekit/livekit/files/12161594/server.txt)

From the server logs, it seems that the server did respond, there are packets getting through, but something failed. 

If I use the livekit tester on computer a
Connecting to signal connection via WebSocket
Connected to server, version 1.4.3.
Warning: Server is insecure, clients may block connections to it
Establishing WebRTC connection
Warning: ports need to be open on firewall in order to connect.
Error: could not establish pc connection
SKIPPED: Can connect via TURN
Warning: No TURN servers configured.
Can publish audio
Error: could not establish pc connection
Can publish video
Error: could not establish pc connection
Resuming connection after interruption
Warning: could not establish pc connection

Funny thing is that if I use a simple HTTP server on the same port, it works. Is there other ports I need to open?

Any idea?

**Comment by davidzhao** [comment]
this approach likely won't work because computer B (that is running livekit server) would not be able to advertise computer A's IP address.

Instead you should do the following:
* Run a TURN server on computer A (i.e. CoTURN)
* Specify that TURN server in livekit config on computer B
  * Also ensure use_external_ip is false, to ensure it selects an internal IP

this way clients will all connect through TURN on computer A
