### ISSUE TITLE
 ScalabilityMode is not defined (when publishing track with VP9 codec)

### ISSUE THREAD

**Issue by onthegit** [livekit/livekit#1922]
**Describe the bug**
When publishing screen track with VP9 codec an error occurs:
```
ReferenceError: ScalabilityMode is not defined
    at videoLayersFromEncodings (LocalVideoTrack.ts:486:1)
    at LocalParticipant.<anonymous> (LocalParticipant.ts:711:1)
    at Generator.next (<anonymous>)
    at fulfilled (DefaultReconnectPolicy.ts:33:1)
```
**Server**
- Version: 1.4.4
- Environment: DEV (Google Chrome Version 110.0.5481.177,  Linux )
- any other information about your deployment setup
command:
```
server --dev
```

**Client**
- SDK:  Javascript 
- Version: 1.12.2

**To Reproduce**
Publish screen track with VP9 codec.

```javascript
this.room.localParticipant.publishTrack(screenTrack, {
            simulcast: false,
            scalabilityMode: "L3T3",
            source: Track.Source.ScreenShare,
            videoCodec: "vp9",
})
```

**Comment by davidzhao** [comment]
Hey @onthegit, this was reported in the JS repo [here](https://github.com/livekit/client-sdk-js/issues/814) and has been fixed.

The update is released in 1.12.3

While I have you here, do you mind taking a look at the CLA on your PR [here](https://github.com/livekit/egress/pull/437) so we can get it merged?
