### ISSUE TITLE
Turn server setup

### ISSUE THREAD

**Issue by tmtong** [livekit/livekit#1926]
I have a server A that is open to internet. And server B under a strict firewall that only allow outbound connection with a HTTP proxy. Clients on the same network on server B can only connect to server B, there is no internet connection.

Based on documentation and discussion, I can setup a TURN server on server A. Expose 3478. I can also setup a livekit server on server A and server B. The config file of both livekit server will point to the TURN server .

Is there some other ports I need to open on server A ? Other than 3478 , 7880, 7881 ?  Is this setup right ?

**Comment by tmtong** [comment]
Or the turn server should be run inside server A. livekit server on server B. Livekit server points to turn server on server A via port 3478
Client connect to server A via TURN. 
But how to specify the turn server on client?

there is a lack of documentation on how to connect via turn server

**Comment by davidzhao** [comment]
external TURN servers are configured [here](https://github.com/livekit/livekit/blob/master/config-sample.yaml#L58).

you are asking for a very specific use case that we do not officially support. you are welcome to still try to make it work though! but do keep in mind that this is the road less traveled, and you'd likely not find docs to guide you through.

Also, LiveKit cannot be used as a standalone TURN server.
