### ISSUE TITLE
Lack of Livekit documentation for deployment on linux virtual without using docker

### ISSUE THREAD

**Issue by Kellykinyama12** [livekit/livekit#1967]
The livekit documentation is silent on deploying on linux virtual machines without using docker.

**Comment by davidzhao** [comment]
Docker is our official recommendation when deploying the builds. We also provide installation steps [here](https://github.com/livekit/livekit#install). 

Do you have any suggestions on how we could improve the docs? Feel free to include links and/or screenshots
