### ISSUE TITLE
ingress issue

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/livekit#1987]
**Describe the bug**
when i create ingress, server return code: “unauthenticed”  “permission denied”
1  I do getToken with room and identity params
2 I createIngress then return error  “ permission denied”

**Comment by davidzhao** [comment]
How are you creating the Ingress? You'll need `ingressAdmin` in the [grant](https://docs.livekit.io/realtime/concepts/authentication/#video-grant) in order to interact with Ingress

**Comment by Hollymingyi** [comment]
also that param ImputType = IngressInput_RTMP_INPUT

**Comment by Hollymingyi** [comment]
Mr zhao ,below is the ingress logs ...
time="2023-08-22T08:28:18Z" level=info msg="Change state: From = <Unknown>, To = NotConnected(Server)" logger=ingress nodeID=NE_nWWwtmTa3sdT state="NotConnected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg=Connect logger=ingress nodeID=NE_nWWwtmTa3sdT state="NotConnected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg="Set win ack size: Size = 2147483647" logger=ingress nodeID=NE_nWWwtmTa3sdT state="NotConnected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg="Set peer bandwidth: Size = 786432, Limit = 0" logger=ingress nodeID=NE_nWWwtmTa3sdT state="NotConnected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg="Stream Begin: ID = 0" logger=ingress nodeID=NE_nWWwtmTa3sdT state="NotConnected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg="Connect: ResponseBody = &message.NetConnectionConnectResult{Properties:message.NetConnectionConnectResultProperties{FMSVer:\"GO-RTMP/0,0,0,0\", Capabilities:31, Mode:1}, Information:message.NetConnectionConnectResultInformation{Level:\"status\", Code:\"NetConnection.Connect.Success\", Description:\"Connection succeeded.\", Data:amf0.ECMAArray{\"type\":\"go-rtmp\", \"version\":\"master\"}}}" logger=ingress nodeID=NE_nWWwtmTa3sdT state="NotConnected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg=Connected logger=ingress nodeID=NE_nWWwtmTa3sdT state="NotConnected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg="Change state: From = NotConnected(Server), To = Connected(Server)" logger=ingress nodeID=NE_nWWwtmTa3sdT state="Connected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg="Handle WinAckSize: Msg = &message.WinAckSize{Size:786432}" logger=ingress nodeID=NE_nWWwtmTa3sdT state="Connected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg="Stream creating...: &message.NetConnectionCreateStream{}" logger=ingress nodeID=NE_nWWwtmTa3sdT state="Connected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg="Change state: From = <Unknown>, To = Inactive(Server)" logger=ingress nodeID=NE_nWWwtmTa3sdT state="Inactive(Server)" stream_id=1
time="2023-08-22T08:28:18Z" level=info msg="Stream created...: NewStreamID = 1" logger=ingress nodeID=NE_nWWwtmTa3sdT state="Connected(Server)" stream_id=0
time="2023-08-22T08:28:18Z" level=info msg="Player is comming: &message.NetStreamPlay{CommandObject:interface {}(nil), StreamName:\"livestream\", Start:-2000}" logger=ingress nodeID=NE_nWWwtmTa3sdT state="Inactive(Server)" stream_id=1
time="2023-08-22T08:28:18Z" level=info msg="Player accepted" logger=ingress nodeID=NE_nWWwtmTa3sdT state="Inactive(Server)" stream_id=1
time="2023-08-22T08:28:18Z" level=info msg="Change state: From = Inactive(Server), To = Play(Server)" logger=ingress nodeID=NE_nWWwtmTa3sdT state="Play(Server)" stream_id=1
