### ISSUE TITLE
Screen Share Audio

### ISSUE THREAD

**Issue by wasif2mehmood** [livekit/livekit#1989]
Screen Sharing Screen is not capturing audio despite setting capturescreenaudio to true

Livekit

Flutter

**To Reproduce**
whenever i share my screen and play a video its audio is not transfered

**Expected behavior**
I raised the issue before but response was that it will be solved shortly but it is not solved please resolve the screen audio share problem.

**Comment by davidzhao** [comment]
Please DO NOT duplicate issues across repos. Instead follow [the issue](https://github.com/livekit/client-sdk-flutter/issues/316) for updates.

**Comment by wasif2mehmood** [comment]
oki sorry sir
