### ISSUE TITLE
sharing images for all users

### ISSUE THREAD

**Issue by Hazem-Ben-Abdelhafidh** [livekit/livekit#2014]
Is there a way to share an image for all participants to see? 

**Client**
- SDK: [js,nextjs]

I have a video conference app that have all the basic functionalities. I'm now trying to add a feature where users can upload images and then by clicking one of them it gets shared to all users(kind of screen sharing but instead of your screen you share the image you clicked on). Is it possible to do this using livekit and nextjs? I've tried to change the video track but I was not able to figure it out.

**Comment by davidzhao** [comment]
You'd have to do roughly the following:
* Load the image into a `<canvas>`
* Create a MediaStreamTrack from canvas ([blog](https://blog.livekit.io/streaming-video-from-a-canvas-with-webrtc-and-react/))
* Publish MediaStreamTrack to LiveKit

On the receiver side, it would become a Video Track and can be rendered.

**Comment by Hazem-Ben-Abdelhafidh** [comment]
@davidzhao,  thanks for the reply, i've tried this and it worked only on firefox and not on chrome. this is my code : 
```
const handleBroadcast = async (img: string) => {
		const canvas = document.createElement("canvas");
		const ctx = canvas.getContext("2d");
		const image = new Image();
		image.src = img;
		image.onload = () => {
			canvas.width = image.width;
			canvas.height = image.height;
			ctx?.drawImage(image, 0, 0);
		};
		room.localParticipant.publishTrack(canvas.captureStream(30).getVideoTracks()[0], {
			name: "test hazmz",
			source: Track.Source.ScreenShare,
		});
	};
```
on firefox the image gets shared for all users as if i'm sharing my screen but on chrome it doesn't work and i get nothing when listening for published tracks. Also if another user tries to share an image it doesn't get focused automatically for other users (any idea how to solve this) I'm kind of new to livekit and the documentation isn't really helpful
