### ISSUE TITLE
Error write: broken pipe

### ISSUE THREAD

**Issue by kientv** [livekit/livekit#2020]
I see many error logs as below on caddy:

`{"level":"error","ts":1693430388.3006966,"logger":"layer4.handlers.proxy","msg":"upstream connection","local_address":"10.148.0.2:56074","remote_address":"10.148.0.2:5349","error":"write tcp 10.148.0.2:443->197.39.144.13:45603: write: broken pipe"}`

**Comment by davidzhao** [comment]
these are logged by Caddy layer4. they are not related to LiveKit.

This is happening due to clients abruptly disconnecting their TURN/TLS sessions.
