### ISSUE TITLE
RAW audio

### ISSUE THREAD

**Issue by naziur604** [livekit/livekit#2027]
we are testing livekit but the audio quality is too bad. can you help me to make it same like agora . we want mp3 quality.
please let me know how we can get it thanks in advance.

**Comment by cnderrauber** [comment]
Which client and encoding parameters are you using?  Livekit support up to 510kbps stereo high quality Opus encoding.

**Comment by davidzhao** [comment]
@naziur604, which platform/SDKs are you building for?

**Comment by naziur604** [comment]
> Which client and encoding parameters are you using? Livekit support up to 510kbps stereo high quality Opus encoding. If you are using client-sdk-js in browser, you can use `AudioCaptureOptions` and `TrackPublishOptions` like this:
> 
> ```
> {
>   channelCount: 2,
>   echoCancellation: false,
>   noiseSuppression: false,
> }
> 
> {
>   audioPreset: AudioPresets.musicHighQualityStereo,
>   dtx: false,
>   red: false,
> }
> ```

**thank you for your quick reply.**
**right now i am using android SDK with this config**
i dont know how to change config i try to get it but i dint find any doc about it


  val options = RoomOptions(
  audioTrackCaptureDefaults = LocalAudioTrackOptions(
    noiseSuppression = true,
    echoCancellation = true,
    autoGainControl = true,
    highPassFilter = true,
    typingNoiseDetection = true,
  ),
  videoTrackCaptureDefaults = LocalVideoTrackOptions(
    deviceId = "",
    position = CameraPosition.FRONT,
    captureParams = VideoPreset169.HD.capture,
  ),
  audioTrackPublishDefaults = AudioTrackPublishDefaults(
    audioBitrate = 96_000,
    dtx = true,
  ),

**Comment by naziur604** [comment]
> @naziur604, which platform/SDKs are you building for?

right now i am using android SDK

**Comment by cnderrauber** [comment]
@naziur604 The bitrate looks good, you can check the subscriber's track bitrate to see if the track is encoding to 96kbps correctly, but you need to change the audio capture options to disable `noiseSuppression`, `echoCancellation`, `autoGainControl`, `highPassFilter`, `dtx` that the webrtc's APM(audio process module) would downsample the audio as it can't process 48KHz sample rate / stereo audio samples and will hurt the quality because it is designed to use by conference. Hence, you need to close those options for high quality music.

**Comment by naziur604** [comment]
> @naziur604 The bitrate looks good, you can check the subscriber's track bitrate to see if the track is encoding to 96kbps correctly, but you need to change the audio capture options to disable `noiseSuppression`, `echoCancellation`, `autoGainControl`, `highPassFilter`, `dtx` that the webrtc's APM(audio process module) would downsample the audio as it can't process 48KHz sample rate / stereo audio samples and will hurt the quality because it is designed to use by conference. Hence, you need to close those options for high quality music.

how can i check the subscriber's track bitrate to see if the track is encoding to 96kbps ?
also is there any way to check Codec ?

also do i need to change anything on livekit server code or only android SDK
please let me know

**Comment by davidzhao** [comment]
Please avoid filing duplicate tickets. Since you've filed https://github.com/livekit/client-sdk-android/issues/259, I'm going to close this one.
