### ISSUE TITLE
No nuget package provided to apply to .net projects

### ISSUE THREAD

**Issue by mikea6688** [livekit/livekit#2084]
**Describe the bug**
I want to use liveKit in my .net project, but it seems that there is no relevant nuget package to use it. I looked through your documents and it seems that there is no relevant httpclient to generate tokens, so I want to know how I can apply it. to my project, hope to get your reply, thank you

**Expected behavior**
In my .net project, I can get the livekit token to use some functions for meetings.

**Comment by davidzhao** [comment]
We don't yet have a SDK for .NET today. While this may be built in the future, it's not currently on the roadmap.

You have two options:
* Use livekit-cli
* Use any JWT library to create one. Here are [additional docs](https://docs.livekit.io/realtime/concepts/authentication/) about the token format.
