### ISSUE TITLE
There are still people in the room, but the room will self-destruct

### ISSUE THREAD

**Issue by ghostshangxue** [livekit/livekit#2090]
**Describe the bug**
A create a room, B join the room, then B exit the room again, A is still in the room, but after about 30 seconds, if no one else enters the room, A often leave the room automatically. Looking at the server side, the room A just created is no longer there.Why? Is there something wrong with my configuration?

**Server**
- Version: [1.4.5]
- Environment: [dev]
- any other information about your deployment setup

**Client**
https://example.livekit.io/

**To Reproduce**
1. client A  is connected to room
2. client B  is connected to room
3. client B leaves the room
4. About 30 seconds later，See error：client A  leave the room automatically

**Expected behavior**

**Screenshots**

**Additional context**
my-token：
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTUxMjM0MTAsImlzcyI6IkFQSTZVWFhKNFJ1eGVUbyIsIm1ldGFkYXRhIjoie1wicm9vbV9pZFwiOlwiODg0YmE1ZjQwYzg2MDZhMDE0NmIxOGNhMmYxOThkNzRcIixcImlkZW50aXR5XCI6NixcIm5pY2tuYW1lXCI6XCJ0ZXN0NVwiLFwicm9vbUFkbWluXCI6dHJ1ZSxcInJvb21Kb2luXCI6dHJ1ZSxcInJvb21SZWNvcmRcIjp0cnVlLFwiY2FuUHVibGlzaFwiOnRydWUsXCJjYW5TdWJzY3JpYmVcIjp0cnVlLFwiY2FuUHVibGlzaERhdGFcIjp0cnVlLFwiY2FuVXBkYXRlT3duTWV0YWRhdGFcIjp0cnVlLFwiY2FuUmVjb3JkaW5nU2NyZWVuXCI6dHJ1ZSxcImNhblNoYXJlU2NyZWVuXCI6dHJ1ZSxcImNhblNoYXJlV2hpdGVib2FyZFwiOnRydWUsXCJjYW5DaGF0XCI6dHJ1ZSxcImluZ3Jlc3NBZG1pblwiOnRydWUsXCJoaWRkZW5cIjpmYWxzZSxcInJlY29yZGVyXCI6dHJ1ZSxcImNsb3NlQXVkaW9cIjpmYWxzZSxcImNsb3NlVmVkaW9cIjpmYWxzZSxcInByb3Zpc2lvbmFsU3RhdHVzXCI6ZmFsc2V9IiwibmJmIjoxNjk1MTE5ODEwLCJzdWIiOiI2IiwidmlkZW8iOnsiY2FuUHVibGlzaCI6dHJ1ZSwiY2FuUHVibGlzaERhdGEiOnRydWUsImNhblN1YnNjcmliZSI6dHJ1ZSwiY2FuVXBkYXRlT3duTWV0YWRhdGEiOnRydWUsImluZ3Jlc3NBZG1pbiI6dHJ1ZSwicmVjb3JkZXIiOnRydWUsInJvb20iOiJSb29tODg3QTQxMkFBN0RCNDFFQzQ1ODk4MDIxMEFGQTRDMUYiLCJyb29tQWRtaW4iOnRydWUsInJvb21DcmVhdGUiOnRydWUsInJvb21Kb2luIjp0cnVlLCJyb29tTGlzdCI6dHJ1ZSwicm9vbVJlY29yZCI6dHJ1ZX19.NL5tVLKBxUBtE6dbiek7RXr4vNnzR8pLwQbtN3Yzf_A

**Comment by davidzhao** [comment]
closing due to insufficient information.
