### ISSUE TITLE
poor video and audio quality and lagging

### ISSUE THREAD

**Issue by TheEhsanSarshar** [livekit/livekit#2093]
I'm using gather.town which internally uses livekit. recently I've been experiencing poor video quality and lagging, and it seems it doesn't use my full internet speed. 
didn't have this issue before and I've started to experience this issue since a month ago.

**Comment by davidzhao** [comment]
Hey @ TheEhsanSarshar, could you provide more information? What is the URL to your space? Feel free to send it to us via email: support at livekit.io
