### ISSUE TITLE
qustion:when i use 711A，it not works well

### ISSUE THREAD

**Issue by czk630597526** [livekit/livekit#2098]
![image](https://github.com/livekit/livekit/assets/88134686/ad9016d5-294e-4b87-979e-9bdd9c9e9222)
thats my config for audio and video，
i cannot get audio when i use client-js-sdk/example,and use opus i can get audio,i just want to use 711 to transport the stream to freeswitch

**Comment by davidzhao** [comment]
Hi there, we do not support 711 right now. currently LiveKit supports only Opus
