### ISSUE TITLE
OperationError Failed to execute 'setLocalDescription' on 'RTCPeerConnection'

### ISSUE THREAD

**Issue by hyc242828** [livekit/livekit#2099]
**Describe the bug**
On on windows PC (Other PCS don't have this problem), the first subscribtion succeed, but when participant unpublish, and republish, 
future subscription always failed. createAndSetAnswer happen error :

error1:
not able to set answer, falling back to unmodified sdp 
OperationError Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local answer sdp: Failed to set local video description recv parameters for m-section with mid='2'.

error2:
unable to set answer 
Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set local video description recv parameters for m-section with mid='2'..

**Server**
- Version: master, checkout at 2023-08-21

**Client**
- SDK: [client-sdk-js]
- Version: [1.13.1]
- windows 10
- chrome & ms edge (version 117)

**1. first subscribtion**

**setRemoteDescription:**

v=0
o=- 1093155362684281412 1695346357 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 F4:14:B6:D6:DC:22:88:67:D7:F7:2F:21:91:DC:A5:DA:B0:32:C8:4C:40:25:D3:27:85:1F:70:A6:B2:9E:C8:2F
a=extmap-allow-mixed
a=group:BUNDLE 0 1 2
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=sendrecv
a=sctp-port:5000
a=ice-ufrag:rkRXEnnXRbPIGXbt
a=ice-pwd:dBKCKKdCfzReMIUloBmizFXZpLtvDxEF
a=candidate:1181739742 1 udp 2130706431 119.91.119.236 12044 typ host
a=candidate:1181739742 2 udp 2130706431 119.91.119.236 12044 typ host
a=end-of-candidates
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:1
a=ice-ufrag:rkRXEnnXRbPIGXbt
a=ice-pwd:dBKCKKdCfzReMIUloBmizFXZpLtvDxEF
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 nack 
a=ssrc:2538325626 cname:PA_VnCLagm3RHv2|TR_AMmvZS9XLNMwLA
a=ssrc:2538325626 msid:PA_VnCLagm3RHv2|TR_AMmvZS9XLNMwLA TR_AMmvZS9XLNMwLA
a=ssrc:2538325626 mslabel:PA_VnCLagm3RHv2|TR_AMmvZS9XLNMwLA
a=ssrc:2538325626 label:TR_AMmvZS9XLNMwLA
a=msid:PA_VnCLagm3RHv2|TR_AMmvZS9XLNMwLA TR_AMmvZS9XLNMwLA
a=sendrecv
m=video 9 UDP/TLS/RTP/SAVPF 125 108 123
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:2
a=ice-ufrag:rkRXEnnXRbPIGXbt
a=ice-pwd:dBKCKKdCfzReMIUloBmizFXZpLtvDxEF
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack 
a=rtcp-fb:125 nack pli
a=rtcp-fb:125 goog-remb 
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack 
a=rtcp-fb:108 nack pli
a=rtcp-fb:108 goog-remb 
a=rtpmap:123 H264/90000
a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack 
a=rtcp-fb:123 nack pli
a=rtcp-fb:123 goog-remb 
a=extmap:1 https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=ssrc:2022424137 cname:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR
a=ssrc:2022424137 msid:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR TR_VC6rBycwiNSLrR
a=ssrc:2022424137 mslabel:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR
a=ssrc:2022424137 label:TR_VC6rBycwiNSLrR
a=msid:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR TR_VC6rBycwiNSLrR
a=sendrecv

**createAndSetAnswer:**

v=0
o=- 4548584011864156046 3 IN IP4 127.0.0.1
s=-
t=0 0
a=extmap-allow-mixed
a=msid-semantic:  WMS
a=group:BUNDLE 0 1 2
m=application 55168 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 10.200.200.3
a=setup:active
a=mid:0
a=ice-ufrag:ri+R
a=ice-pwd:pZZwnfYGZ5qxvQlGyQi+mJuW
a=fingerprint:sha-256 97:86:BB:1A:DF:33:02:A3:A0:53:D0:BB:02:13:61:E8:E5:67:84:CC:0F:0F:80:2C:58:E4:84:A1:B9:1F:48:D4
a=candidate:3701753514 1 udp 2122260223 10.200.200.3 55168 typ host generation 0 network-id 1 network-cost 50
a=candidate:375067632 1 udp 2122194687 10.1.45.115 55169 typ host generation 0 network-id 2
a=ice-options:trickle
a=sctp-port:5000
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:111 nack
a=setup:active
a=mid:1
a=recvonly
a=ice-ufrag:ri+R
a=ice-pwd:pZZwnfYGZ5qxvQlGyQi+mJuW
a=fingerprint:sha-256 97:86:BB:1A:DF:33:02:A3:A0:53:D0:BB:02:13:61:E8:E5:67:84:CC:0F:0F:80:2C:58:E4:84:A1:B9:1F:48:D4
a=ice-options:trickle
a=rtcp-mux
m=video 9 UDP/TLS/RTP/SAVPF 125 108
c=IN IP4 0.0.0.0
a=rtpmap:125 H264/90000
a=rtpmap:108 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:1 https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension
a=setup:active
a=mid:2
a=recvonly
a=ice-ufrag:ri+R
a=ice-pwd:pZZwnfYGZ5qxvQlGyQi+mJuW
a=fingerprint:sha-256 97:86:BB:1A:DF:33:02:A3:A0:53:D0:BB:02:13:61:E8:E5:67:84:CC:0F:0F:80:2C:58:E4:84:A1:B9:1F:48:D4
a=ice-options:trickle
a=rtcp-mux
a=rtcp-rsize

**2. the second subscribution:**

**setRemoteDescription:**

v=0
o=- 1093155362684281412 1695346359 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 F4:14:B6:D6:DC:22:88:67:D7:F7:2F:21:91:DC:A5:DA:B0:32:C8:4C:40:25:D3:27:85:1F:70:A6:B2:9E:C8:2F
a=extmap-allow-mixed
a=group:BUNDLE 0 1 2
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=sendrecv
a=sctp-port:5000
a=ice-ufrag:rkRXEnnXRbPIGXbt
a=ice-pwd:dBKCKKdCfzReMIUloBmizFXZpLtvDxEF
a=candidate:1181739742 1 udp 2130706431 119.91.119.236 12044 typ host
a=candidate:1181739742 2 udp 2130706431 119.91.119.236 12044 typ host
a=end-of-candidates
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:1
a=ice-ufrag:rkRXEnnXRbPIGXbt
a=ice-pwd:dBKCKKdCfzReMIUloBmizFXZpLtvDxEF
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 nack 
a=recvonly
m=video 9 UDP/TLS/RTP/SAVPF 125 108 123
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:2
a=ice-ufrag:rkRXEnnXRbPIGXbt
a=ice-pwd:dBKCKKdCfzReMIUloBmizFXZpLtvDxEF
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack 
a=rtcp-fb:125 nack pli
a=rtcp-fb:125 goog-remb 
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack 
a=rtcp-fb:108 nack pli
a=rtcp-fb:108 goog-remb 
a=rtpmap:123 H264/90000
a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack 
a=rtcp-fb:123 nack pli
a=rtcp-fb:123 goog-remb 
a=extmap:1 https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=ssrc:729125716 cname:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR
a=ssrc:729125716 msid:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR TR_VC6rBycwiNSLrR
a=ssrc:729125716 mslabel:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR
a=ssrc:729125716 label:TR_VC6rBycwiNSLrR
a=msid:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR TR_VC6rBycwiNSLrR
a=sendrecv

**createAndSetAnswer:**

**error1:**
not able to set answer, falling back to unmodified sdp 
OperationError Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local answer sdp: Failed to set local video description recv parameters for m-section with mid='2'.

**munged sdp:**
v=0
o=- 4548584011864156046 5 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS
m=application 55168 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 10.200.200.3
a=candidate:3701753514 1 udp 2122260223 10.200.200.3 55168 typ host generation 0 network-id 1 network-cost 50
a=candidate:375067632 1 udp 2122194687 10.1.45.115 55169 typ host generation 0 network-id 2
a=ice-ufrag:ri+R
a=ice-pwd:pZZwnfYGZ5qxvQlGyQi+mJuW
a=ice-options:trickle
a=fingerprint:sha-256 97:86:BB:1A:DF:33:02:A3:A0:53:D0:BB:02:13:61:E8:E5:67:84:CC:0F:0F:80:2C:58:E4:84:A1:B9:1F:48:D4
a=setup:active
a=mid:0
a=sctp-port:5000
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ri+R
a=ice-pwd:pZZwnfYGZ5qxvQlGyQi+mJuW
a=ice-options:trickle
a=fingerprint:sha-256 97:86:BB:1A:DF:33:02:A3:A0:53:D0:BB:02:13:61:E8:E5:67:84:CC:0F:0F:80:2C:58:E4:84:A1:B9:1F:48:D4
a=setup:active
a=mid:1
a=inactive
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 nack
a=fmtp:111 minptime=10;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 125 108 123
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ri+R
a=ice-pwd:pZZwnfYGZ5qxvQlGyQi+mJuW
a=ice-options:trickle
a=fingerprint:sha-256 97:86:BB:1A:DF:33:02:A3:A0:53:D0:BB:02:13:61:E8:E5:67:84:CC:0F:0F:80:2C:58:E4:84:A1:B9:1F:48:D4
a=setup:active
a=mid:2
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:1 https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:123 H264/90000
a=rtcp-fb:123 goog-remb
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f

**error2:**
unable to set answer 
Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set local video description recv parameters for m-section with mid='2'..

**remote sdp:**
v=0
o=- 1093155362684281412 1695346359 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR
m=application 12044 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 119.91.119.236
a=candidate:1181739742 1 udp 2130706431 119.91.119.236 12044 typ host generation 0
a=candidate:1181739742 2 udp 2130706431 119.91.119.236 12044 typ host generation 0
a=candidate:1181739742 1 udp 2130706431 119.91.119.236 12044 typ host generation 0
a=ice-ufrag:rkRXEnnXRbPIGXbt
a=ice-pwd:dBKCKKdCfzReMIUloBmizFXZpLtvDxEF
a=fingerprint:sha-256 F4:14:B6:D6:DC:22:88:67:D7:F7:2F:21:91:DC:A5:DA:B0:32:C8:4C:40:25:D3:27:85:1F:70:A6:B2:9E:C8:2F
a=setup:actpass
a=mid:0
a=sctp-port:5000
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:rkRXEnnXRbPIGXbt
a=ice-pwd:dBKCKKdCfzReMIUloBmizFXZpLtvDxEF
a=fingerprint:sha-256 F4:14:B6:D6:DC:22:88:67:D7:F7:2F:21:91:DC:A5:DA:B0:32:C8:4C:40:25:D3:27:85:1F:70:A6:B2:9E:C8:2F
a=setup:actpass
a=mid:1
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 nack
a=fmtp:111 minptime=10;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 125 108 123
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:rkRXEnnXRbPIGXbt
a=ice-pwd:dBKCKKdCfzReMIUloBmizFXZpLtvDxEF
a=fingerprint:sha-256 F4:14:B6:D6:DC:22:88:67:D7:F7:2F:21:91:DC:A5:DA:B0:32:C8:4C:40:25:D3:27:85:1F:70:A6:B2:9E:C8:2F
a=setup:actpass
a=mid:2
a=extmap:1 https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=msid:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR TR_VC6rBycwiNSLrR
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=rtcp-fb:125 goog-remb
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:108 H264/90000
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=rtcp-fb:108 goog-remb
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:123 H264/90000
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=rtcp-fb:123 goog-remb
a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=ssrc:729125716 cname:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR
a=ssrc:729125716 msid:PA_VnCLagm3RHv2|TR_VC6rBycwiNSLrR TR_VC6rBycwiNSLrR

**original sdp:**
v=0
o=- 4548584011864156046 5 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS
m=application 55168 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 10.200.200.3
a=candidate:3701753514 1 udp 2122260223 10.200.200.3 55168 typ host generation 0 network-id 1 network-cost 50
a=candidate:375067632 1 udp 2122194687 10.1.45.115 55169 typ host generation 0 network-id 2
a=ice-ufrag:ri+R
a=ice-pwd:pZZwnfYGZ5qxvQlGyQi+mJuW
a=ice-options:trickle
a=fingerprint:sha-256 97:86:BB:1A:DF:33:02:A3:A0:53:D0:BB:02:13:61:E8:E5:67:84:CC:0F:0F:80:2C:58:E4:84:A1:B9:1F:48:D4
a=setup:active
a=mid:0
a=sctp-port:5000
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ri+R
a=ice-pwd:pZZwnfYGZ5qxvQlGyQi+mJuW
a=ice-options:trickle
a=fingerprint:sha-256 97:86:BB:1A:DF:33:02:A3:A0:53:D0:BB:02:13:61:E8:E5:67:84:CC:0F:0F:80:2C:58:E4:84:A1:B9:1F:48:D4
a=setup:active
a=mid:1
a=inactive
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 nack
a=fmtp:111 minptime=10;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 125 108 123
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ri+R
a=ice-pwd:pZZwnfYGZ5qxvQlGyQi+mJuW
a=ice-options:trickle
a=fingerprint:sha-256 97:86:BB:1A:DF:33:02:A3:A0:53:D0:BB:02:13:61:E8:E5:67:84:CC:0F:0F:80:2C:58:E4:84:A1:B9:1F:48:D4
a=setup:active
a=mid:2
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:1 https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:123 H264/90000
a=rtcp-fb:123 goog-remb
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f

**Comment by davidzhao** [comment]
This issue has been fixed in [v1.5.0](https://github.com/livekit/livekit/releases/tag/v1.5.0). Fixed in #1997
