### ISSUE TITLE
Feature Request Supabase

### ISSUE THREAD

**Issue by Martin-Hausleitner** [livekit/livekit#2108]
A Supabase implementation would be great :)

**Comment by davidzhao** [comment]
What do you mean by this? How does Supabase, a DB, related to LiveKit?

**Comment by Martin-Hausleitner** [comment]
I mean with Supabase auth

**Comment by davidzhao** [comment]
I see. this is out of scope for LiveKit. It's already possible to use the two together today. Your application, after authenticating the user, would generate a LiveKit JWT token with the desired permissions for that participant.
