### ISSUE TITLE
SEND DATA CAN'T SEND BUT NO ERROR - Go SDK

### ISSUE THREAD

**Issue by refaldyrk** [livekit/livekit#2113]
**Describe the bug**
i try to send data using golang sdk but data where? i can;t get and my fe can't  get data, and this my code
``go payloadLivekit := &livekit.SendDataRequest{
		Room: roomID,
		Data: payloadByteLivekit,
		Kind: livekit.DataPacket_RELIABLE,
	}
	resp, err := l.roomClient.SendData(ctx, payloadLivekit)``

	
	

**Server**
- Version: [1.4]
- Environment: [Prod, Docker]

**Client**
- SDK: [Javascript]

How To I Send Data? And I Can Get The Data, Thanks

**Comment by davidzhao** [comment]
Incomplete report, closing.  If you wish to get help, the slack community is a good place to ask usage questions.
