### ISSUE TITLE
Stream key not removed from Redis hash {ingress}_stream_key when deleting ingress

### ISSUE THREAD

**Issue by gridbox** [livekit/livekit#2124]
**Describe the bug**
I am currently evaluating LiveKit for self-hosted integration into our platform and am familiarizing myself with its internals.  During my prototyping I was working with ingress endpoints for RTMP/WHIP and inspecting Redis to see what data was being stored there.  I happened to notice that upon deletion of an ingress, the hash `{ingress}_stream_key` still has an entry for the key and id of the ingress I just deleted.  While the amount of data leftover is small, this could eventually lead to unnecessary memory consumption by Redis for keys that are no longer used and presumably have no way of accessing or cleaning up.

**Server**
- Version: 1.4.5 (brew install on MacOS)
- Environment: Local Dev
- Redis: 7.2.1

**Client**
- SDK: livekit-cli
- Version: 1.2.10

**To Reproduce**
1. Create an ingress with `livekit-cli create-ingress`
2. Observe data created in Redis
3. Get ingress id with `livekit-cli list-ingress`
4. Delete ingress with `livekit-clit delete-ingress --id <ID FROM STEP 3>`
5. Observe data removed from Redis with the exception of the ingress stream key and id value in `{ingress}_stream_key`

**Expected behavior**
Entry is removed from `{ingress}_stream_key` on delete of the ingress

**Screenshots**

**Additional context**

**Comment by gridbox** [comment]
It appears this may have been addressed already but not released.  I decided to clone the repo and build from source.  When building from `master` I am observing the expected behavior and the keys are cleaned up in `{ingress}_stream_key`.  Any idea when this update will make it to a stable release?

**Comment by davidzhao** [comment]
It's released as part of 1.5.0
