### ISSUE TITLE
how to i can deploy on my own server already have server and public ip

### ISSUE THREAD

**Issue by bagusandrewijaya** [livekit/livekit#2142]
anyone have step by step deploy and run production livekit without docker ?
i tried this cert and pem
![image](https://github.com/livekit/livekit/assets/103176578/afc581b5-49de-4abd-bb28-0d2182ba772f)

**Comment by davidzhao** [comment]
you need to supply a config file. See: `livekit-server --help`

**Comment by bagusandrewijaya** [comment]
> you need to supply a config file. See: `livekit-server --help`

i already tried create  --config-body and create config.yaml but i always get one of key-file or keys must be provided but im sure my cert and key is valid 


![image](https://github.com/livekit/livekit/assets/103176578/0fe68d02-80f7-47bb-a49f-002368da03e5)

**Comment by davidzhao** [comment]
you need to fill in the `keys` section
