### ISSUE TITLE
Can't see participant's video in NextJS

### ISSUE THREAD

**Issue by DezyNation** [livekit/livekit#2199]
**Describe the bug**

**Server**
I've deployed LiveKit on Ubuntu using latest docker builds. Since Caddy was having issues due to Nginx, I removed `caddy` service from `docker-compose.yaml`.

**Client**
- NextJS 13.4

**To Reproduce**
Start the docker containers without caddy and use Nginx to reverse proxy at port 7880.

**Expected behavior**
Audio is working fine but the participants are able to see their own video only, other participants' tiles are totally black.

**Additional context**
I saw that caddy was trying to start a TURN server, is it mandatory to start TURN server? If yes, I'll prefer starting it manually and use Nginx to reverse proxy to it's port. Honestly, I don't have any experience with Caddy and it's facing conflict with Nginx since Nginx is already listening to port 443 and many of my existing apps are already connected through Nginx.

**Comment by davidzhao** [comment]
Sorry, given the diverse deployment options, we cannot support every combination. Closing.
