### ISSUE TITLE
TransportManager keeps waiting for SUBSCRIBER PeerConnection even if canSubscribe == false for the participant

### ISSUE THREAD

**Issue by gustavo-lighttwist** [livekit/livekit#2222]
Some use cases will have applications that only connect to LiveKit to publish streams (joining with grant canSubscribe = false). These applications shouldn't be required to establish a second "SUBSCRIBER" PeerConnection as they aren't even allowed to subscribe anyway.

**Comment by boks1971** [comment]
Which version of server are you using @gustavo-lighttwist ?

**Comment by gustavo-lighttwist** [comment]
1.5.0

**Comment by gustavo-lighttwist** [comment]
After some more debugging found out the issue wasn't with the SUBSCRIBER PeerConnection - the issue was that the PUBLISHER PeerConnection is not switching the Participant from JOINED to ACTIVE until a data channel is opened

Discussion here: https://livekit-users.slack.com/archives/C04G4GE0RGX/p1699043115683039

I'll close this issue as it's invalid.
