### ISSUE TITLE
How to config username and password for turn server

### ISSUE THREAD

**Issue by farsunset** [livekit/livekit#2255]
turn:
  enabled: true
  domain: <turn.myhost.com>
  tls_port: 3478

I can't find username password config

**Comment by davidzhao** [comment]
if you want to use an external TURN, refer to https://github.com/livekit/livekit/blob/master/config-sample.yaml#L58

**Comment by farsunset** [comment]
Or i want get inner turn server username password

**Comment by davidzhao** [comment]
that's not supported
