### ISSUE TITLE
Live meeting crashing randomly

### ISSUE THREAD

**Issue by heyarviind** [livekit/livekit#2259]
**Describe the bug**
We encountered an unexpected issue during a live session utilizing Livekit. The incident resulted in a sudden crash, leading to the abrupt termination of the meeting for all participants involved.

Our setup involves the utilization of Livekit across 15 separate servers, each operating independently without interconnection. This occurrence marks the first instance of such an issue transpiring within approximately 30 days of continuous usage.

To provide further insight into the matter, I have attached relevant logs capturing the event. These logs distinctly highlight the automatic closure and subsequent restart of the room.

We appreciate your prompt attention to this matter and look forward to any guidance or assistance you can provide in resolving this unexpected incident.

**Server**
- Version: [1.5.1]
- Environment: [running on EC2]
- any other information about your deployment setup

**Client**
- SDK: [e.g. js, ios]
- Version: [0.x.x]

**To Reproduce**
1. Just join a live meeting
2. at very random time, it will crash

**Expected behavior**
It should not crash/end without us ending it manually

**Screenshots**
![Screenshot 2023-11-21 at 7 02 34 PM](https://github.com/livekit/livekit/assets/21043614/0ff48610-d972-4a04-b59d-e213f2512d28)
![Screenshot 2023-11-21 at 7 02 57 PM](https://github.com/livekit/livekit/assets/21043614/25370bfd-8efd-4b2c-9c66-8eac76d195f2)

**Comment by boks1971** [comment]
Screen shots are hard to read. Can you attach server logs? Also, were there any panics in the logs? Usually, server crash would be due to a panic or maybe OOM (out-of-memory). Have you check for memory issues in your deployment? Maybe, there is a slow leak which accumulates over a month and hits OOM.

**Comment by heyarviind** [comment]
There were a few errors as I checked the logs (attached the log file for your reference). 
[logs.txt](https://github.com/livekit/livekit/files/13435512/logs.txt)

I think there isn't any memory leak because we shut down the server when the meeting ended and restarted it again when it was about to start. It restarts the Livekit as well.

**Comment by boks1971** [comment]
Thank you for the logs. I can see several instances of `peer connection failed`. Looks like clients lost network connectivity to the server? The ICE connection disconnection/failure happens when the media connection cannot see packets on that link for a while.

**Comment by heyarviind** [comment]
You mean livekit server lost its connectivity for some time?
