### ISSUE TITLE
 'LocalParticipant' is not exported from 'livekit-client

### ISSUE THREAD

**Issue by HuuThongg** [livekit/livekit#2278]
Import trace for requested module:
./node_modules/@livekit/components-core/dist/index.mjs
./node_modules/@livekit/components-react/dist/index.mjs
./app/room/page.tsx
 ⨯ ./node_modules/@livekit/components-core/dist/index.mjs
Attempted import error: 'LocalParticipant' is not exported from 'livekit-client' (imported as 'LocalParticipant').

im testing livekit with next14.
Thank you

**Comment by davidzhao** [comment]
this is an issue with Next 14, see: https://github.com/livekit/client-sdk-js/issues/938
