### ISSUE TITLE
Flutter Egress?

### ISSUE THREAD

**Issue by jtkeyva** [livekit/livekit#2296]
i don't see anywhere in the docs that flutter supports egress? How about flutter web?
thanks

**Comment by davidzhao** [comment]
Yup, Egress works with audio and video published from any SDK, including Flutter.

**Comment by jtkeyva** [comment]
@davidzhao great to hear. can you point me to the documentation or some examples? specifically for flutter web. the docs don't include dart/flutter.
thanks!

**Comment by davidzhao** [comment]
Egress works with the server directly, and does not need to interface with the SDKs themselves. there's no difference between a flutter publisher vs a JS publisher. 

Please refer to the docs [here](https://docs.livekit.io/egress-ingress/) for how Egress works.
