### ISSUE TITLE
Revoke token or completely destroy the room?

### ISSUE THREAD

**Issue by RShadowhand** [livekit/livekit#2307]
Greetings,
I'm using latest version of livekit, and I can't seem to find a way to revoke tokens or completely destroy a room so no one can enter.
Are there plans for this, or any examples as to how to handle this use case?

Thank you in advance.

**Comment by davidzhao** [comment]
you cannot revoke existing tokens. To close the room and disconnect everyone, see [DeleteRoom](https://docs.livekit.io/realtime/server/managing-rooms/#delete-a-room)

**Comment by RShadowhand** [comment]
Closing the room does not prevent people from joining again, though. Is there really no way to completely prevent the room from being used again?

**Comment by davidzhao** [comment]
you can prevent users from joining when closed, would just need to turn off `auto_create` from config (or Project settings in Cloud)
