### ISSUE TITLE
RoomMetadataChanged does not fire after RoomServiceClient.UpdateRoomMetadata

### ISSUE THREAD

**Issue by jsnimda** [livekit/livekit#2356]
**Describe the bug**
As title.

**Server**
- Version: 1.5.2
- Environment: local dev
- any other information about your deployment setup

**Client**
- SDK: js, golang
- Version: js 1.15.5, golang lksdk 1.1.1

**To Reproduce**
1. Client connected to room
2. Server call RoomServiceClient.UpdateRoomMetadata
3. RoomMetadataChanged did not fire
4. `room.metadata` is still the old one

**Expected behavior**
1. RoomMetadataChanged should fire
2. `room.metadata` should update

**Comment by boks1971** [comment]
Unable to reproduce this failure with that ☝️  combination of server version and JS client version.

Is the API to update room metadata succeeding?

**Comment by jsnimda** [comment]
I create a minimal example. https://github.com/jsnimda/room-metadata-demo

I expected that when you click the increment button, the client should receive the RoomMetadataChanged event, but it does not.
(But very rarely the RoomMetadataChanged event did fire, only once, I do not know why, most of time it didn't fire)

Here is screenshot, I clicked 3 times increment, 1 time reconnect. As you can see `room.metadata` didn't change.
<img width="693" alt="image" src="https://github.com/livekit/livekit/assets/7615255/40a8b5cc-d66d-4697-88a8-25e2c9d99e49">

Client code located at: client/src/app/folder/folder.page.ts
And server code located at: server/main.go

**Comment by boks1971** [comment]
I am able to reproduce this with the example you provided. Thank you so much @jsnimda . Will take a look.
