### ISSUE TITLE
package too big

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/livekit#2359]
dear author,
    when i try to send vp8 rtp packege via func ,
**videoTrack, err := webrtc.NewTrackLocalStaticSample(webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264}, "video", "pion2")
videoTrack.WriteSample(media.Sample{Data: data, Duration: sampleDur}), the livekit server logs like below,**  

###livekit.pub.sfu	buffer/rtpstats_base.go:502	first packet time adjustment too big, ignoring {"room": "66159352", "roomID": "RM_7qQroiKXdmq8", "participant": "Phone 1008", "pID": "PA_fSqRQrcZpGKf", "remote": false, "trackID": "TR_VCY2tbnj4uJMco", "relayed": false, "mime": "video/h264", "layer": 0, "startTime": "2024-01-04 02:23:06.482151168 +0000 UTC m=+5307.321445124", "nowTime": "2024-01-04 02:24:39.210770204 +0000 UTC m=+5400.050064172", "before": "2024-01-04 01:15:56.209897846 +0000 UTC m=+1277.049191814", "after": "2024-01-03 20:10:05.174814649 +0000 UTC m=-17073.985891383", "adjustment": "5h5m51.035083197s", "nowTS": 1595358808, "startTS": 3867662868}

what should i do to resolve the problem? thank u very much

**Comment by boks1971** [comment]
This relies on RTP time stamps. You can see that `nowTS` (the RTP time stamp in RTCP packet processed when this log was displayed) is lesser compared to `startTS` (RTP time stamp of first packet). It seems like the RTCP sender reports are not setting the correct RTP time stamps.

**Comment by Hollymingyi** [comment]
ok,i will capture the rtp package and check the timestamp
