### ISSUE TITLE
egress error : no response from servers

### ISSUE THREAD

**Issue by keaipeng123** [livekit/livekit#2362]
![image](https://github.com/livekit/livekit/assets/90554992/1518ed25-3977-4633-90f7-97b3195afe71)

livekit-server:v1.5.2
egress:v1.7.5

**Comment by AntonioliBenjamin** [comment]
@keaipeng123 hey, i have the same issue, do you have some news ?

**Comment by AntonioliBenjamin** [comment]
@shoyu666 hi for me the fix was to update the versions of livekit server and livekit egress to the very latest

**Comment by shoyu666** [comment]
@AntonioliBenjamin hi,i hava already update the version,but same error .....
livekit verson：1.7
egress version：1.8

**Comment by shoyu666** [comment]
@AntonioliBenjamin 
I just realized there's a new version,i will try,thanks

**Comment by sahilk01** [comment]
I am also getting the same issue
