### ISSUE TITLE
Access Recording on LiveKit VM

### ISSUE THREAD

**Issue by hazhayder** [livekit/livekit#2375]
I have successfully installed LiveKit along with egress following the guide at https://docs.livekit.io/realtime/self-hosting/vm/. However, I couldn't find information regarding the location of recordings. The provided recording details seem to be for development or connecting with S3. Could you please guide me on how to locate the recordings?

**Server**
- Version: latest
- Environment: VM

**Comment by davidzhao** [comment]
it doesn't record locally. the recordings are designed to be put on storage. If you'd like to make it work locally, take a look at [minio](https://github.com/minio/minio)
