### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by refaldyrk** [livekit/livekit#2394]
**Describe the bug**
JWT Token Is Invalid, And I See The Log, And The Ouput Is Here: 

error handling request  {"status": 401, "error": "invalid token: ****************** error: square/go-jose/jwt: validation failed, token not valid yet (nbf)"}

**Server**
- Version: latest
- Environment: ubuntu -> vps
- Livekit Server Latest Version And Egress Version 1.7.5

**Client**
- SDK: Server -> Go & Client -> Svelte
- Version: github.com/livekit/server-sdk-go v1.0.7
 -> "livekit-client": "^1.12.1",

**To Reproduce**
1. join room 
2. backend generate token ->
```go
canPublish := true
	canSubscribe := true
	canPublishData := true

	at := auth.NewAccessToken(apiKey, apiSecret)
	grant := &auth.VideoGrant{
		RoomJoin:       true,
		Room:           room,
		RoomCreate:     false,
		CanPublish:     &canPublish,
		CanSubscribe:   &canSubscribe,
		CanPublishData: &canPublishData,
	}

	at.AddGrant(grant).
		SetName(name).
		SetIdentity(identity).
		SetMetadata(metadata).
		SetValidFor(time.Hour * 6)

	return at.ToJWT()
```
3. and client consume

**Expected behavior**
Join Room

**Screenshots**
<img width="581" alt="image" src="https://github.com/livekit/livekit/assets/88225369/660861da-3a0c-4f81-95d2-51f475e6086c">
<img width="309" alt="image" src="https://github.com/livekit/livekit/assets/88225369/87bc9d1d-7846-4f53-b778-264cff30d8a1">

**Comment by davidzhao** [comment]
be sure to synchronize the clock on your servers.

**Comment by refaldyrk** [comment]
umm, after I checked, i was sure that the livekit server and my app were the same

**Comment by davidzhao** [comment]
what about the server running Go SDK? where it generates tokens

**Comment by refaldyrk** [comment]
is the same as the time on the server running livekit

**Comment by davidzhao** [comment]
there's only one way for this error to come up.. it's when the server that is generating the token has a clock that's further ahead of livekit-server.

**Comment by refaldyrk** [comment]
OK, I'll check again, thanks for the response
