### ISSUE TITLE
Close rooms in a consistent, predictable manner

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit#241]
Rooms auto-closes after the last participant leaves the room. Currently this timer fires sometimes around ~20s after. For certain use cases, this means that the webhook notifications that we are delivering also delayed. It also impacts recording use cases where there can be a long gap between when the last participant left and when recording finishes.

**Comment by nitedani** [comment]
The room close event is delayed after everyone leaves the room. That causes the room started event to not trigger when someone joins the empty room.
