### ISSUE TITLE
VM Deploy Requires Domain

### ISSUE THREAD

**Issue by colingoodman** [livekit/livekit#2433]
**Describe the bug**
According to [this ticket](https://github.com/livekit/livekit/issues/1604) from April 2023, LiveKit does not require use of a domain name. However, the VM deploy script provided by the docker image `livekit/generate` (documentation [here](https://docs.livekit.io/realtime/self-hosting/vm/)) requires one.

**Server**
Latest version of livekit/generate

**Expected behavior**
If https/ssl and domain names are not required, then the livekit/generate docker image should make domain names optional and thus _optionally_ include any certificate generation.

**Comment by davidzhao** [comment]
The VM deploy script is designed to automate the setup of a secure installation that a user could connect to from browsers and other clients. We do not intend to support setting up an insecure install; though you may do so yourself by reading through what the script does.
