### ISSUE TITLE
Share screen functionality not working while building a client application using livekit

### ISSUE THREAD

**Issue by Prajwal6394** [livekit/livekit#2436]
I have using electron JS to build a client application for virtual meeting and collaboration. I have used react livekit frame work build the application. 

On using control bar component which provide video, audio, leave and share-screen functionality by default. Share screen feature is not working inside client application. And some how I not be able to customise the logic behind share screen. 
In browser share screen is working fine not on client appication its not.

**Comment by davidzhao** [comment]
This repo contains livekit server and it sounds like the issue you are reporting is related with the client SDK.

For Electron, you will need to use [desktopCapturer](https://www.electronjs.org/docs/latest/api/desktop-capturer) APIs to accomplish this.
