### ISSUE TITLE
Docker hub has incorrect tag v1.10.6 published

### ISSUE THREAD

**Issue by vchernin** [livekit/livekit#2444]
I noticed docker hub has [livekit/livekit-server with tag `v1.10.6`](https://hub.docker.com/layers/livekit/livekit-server/v1.10.6/images/sha256-ddbc840c68925e1a9d011c94c52f718057efc73d6b47dc3c93d5ecd12e06890b) published 2 years ago, even though there is no `v1.10.6` in this repo. Because `v1.10.6` is a "greater" semver version than `v1.5.2` (the current latest release), tools like renovate will offer `v1.10.6` as an update instead of `v1.5.2`. 

So assuming `v1.10.6` was just a typo and not meant to be published, there are some solutions:

- I'm sure there's renovate syntax to simply ignore this version, but such workarounds are annoying to have in downstream renovate configs.
- One can probably delete the `v1.10.6` tag from docker hub, but that is frowned upon (even if the version is completely broken). Generally there is an expectation that tags/versions are immutable or at least never breaking.
- Make a new release e.g. `v1.10.7` or newer. A new release would solve the issue, but will make for somewhat strange version history in this repo (`v1.5.2`, then jumps to `v1.10.7`).

**Comment by davidzhao** [comment]
Thank you for bringing this to our attention. `v1.10` and `v1.10.6` were incorrectly tagged. I've gone ahead and deleted the tags now. While it does break the "immutability" promise, we do not want users to be on a two year old (and potentially broken) version.
