### ISSUE TITLE
How to get remote is not presenting?

### ISSUE THREAD

**Issue by raphaelalkamim** [livekit/livekit#2447]
**Describe the bug**
In a call I want to know when a remote participants is not with the video track enabled, to present an image instead of the video. But, when the remote participant turns off the video, I only get the last frame frozen.

I tried getting the last track information from remote participant delegates, but none of them bring me this kind of information.

**Server**
- Version: v1.4.5
- Environment: AWS EC2 single instance

**Client**
- SDK: iOS
- Version: 1.1.4

**To Reproduce**
1. two clients are connected to room with open cameras
2. 2nd client turns of the camera 
3. 1st client get the frozen video from 2nd client

**Expected behaviour**
When 2nd client turns off the camera, the 1st gets by delegate the information that the 2nd client video track is disabled.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by davidzhao** [comment]
you'd need to check `RemoteParticipant.isCameraEnabled()`, also listen to the events `Muted`.
