### ISSUE TITLE
Could not fetch region settings: livekit

### ISSUE THREAD

**Issue by ghost** [livekit/livekit#2470]
**Describe the bug**
Hello dear friends, im trying to create a video room but i have two erros:
1st: I run the server.js app, to get a valid token and it works great. 
Server.js code:
![image](https://github.com/livekit/livekit/assets/128114702/118dd805-a409-4052-8042-1058b7aa49a0)
execution 
![image](https://github.com/livekit/livekit/assets/128114702/ae47e9d4-406c-46e5-a4c9-a2fcefb40dbe)

Then i run the client.js app and i get an error message: 18179.
![image](https://github.com/livekit/livekit/assets/128114702/49540343-7c13-4f35-a347-48e3433e726b)
execution
![image](https://github.com/livekit/livekit/assets/128114702/41c1564f-b944-410c-b4ed-5a4ac29a8395)

I check on google but no lucky...can you help me or send me instructions please 
**Server**
- Version: [node js 18.13.0]
- Environment: [cloud]
- any other information about your deployment setup

**Client**
- SDK: [js]
- Version: [0.x.x]

**Expected behavior**

**Screenshots**

**Additional context**
i tried genering the token by node.js and by the website

**Comment by davidzhao** [comment]
The issue here is that your token has already expired when it's used against the server.

For testing, you can create a token with a longer expiration.

**Comment by julianMobia** [comment]
Thank you for your quickly answer,  i tried with a longer  time token, but i have the same result 
1. i generate the token
![image](https://github.com/livekit/livekit/assets/128114702/070dd366-b787-4135-9133-5b30f5e9f028)
![image](https://github.com/livekit/livekit/assets/128114702/3f1488aa-df36-4590-8d6d-25725d8e2f1c)
![image](https://github.com/livekit/livekit/assets/128114702/9d269a88-aed5-470c-9a62-0a7eb1651cef)
2. i paste the token in the client.js file
![image](https://github.com/livekit/livekit/assets/128114702/36e7fdb7-af9e-49aa-8713-d6539c8d697f)
3. run client.js
![image](https://github.com/livekit/livekit/assets/128114702/9f79ebb7-c1c2-4a79-acfb-186e8d3f58c2)
 ERROR: ConnectionError: Could not fetch region settings: Unauthorized
 Is i missing something? what that region settings mean?

thank you for helping

**Comment by mahfuz0001** [comment]
I am also having the same issue

**Comment by davidzhao** [comment]
you are not using the right server URL for that token. your token is generated for `mobiademo-***`, but in your code it's showing `mobia-***`. Tokens are specific to the server URL.
