### ISSUE TITLE
Missing Change Speaker Functionality

### ISSUE THREAD

**Issue by pouyaafraz123** [livekit/livekit#2473]
There is no function provided for changing audio output device when user is joined the room

**Comment by davidzhao** [comment]
Closing for two reasons:
1. it's not the responsibility of livekit server to deal with input/output devices
2. this functionality *is* provided by some of our SDKs. Please refer to the docs or ask for help in our [Slack community](https://livekit.io/join-slack)

**Comment by byshb** [comment]
Where is this function in the sdk

**Comment by byshb** [comment]
@davidzhao 这个函数在sdk中的什么位置
