### ISSUE TITLE
1.5.3 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [livekit/livekit#2490]
👋 looks like 1.5.3 release was not completed, ie the release did not published, raise this issue for some awareness. Thanks! cc @davidzhao 

relates to https://github.com/Homebrew/homebrew-core/pull/163188

**Comment by davidzhao** [comment]
Thanks for the heads up @chenrui333! Just released it now.

**Comment by chenrui333** [comment]
Thanks @davidzhao!
