### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by comelec-ems** [livekit/livekit#2509]
Can you support the new cloud storage and affordable 
[https://wasabi.com/cloud-storage-pricing/#cost-estimates](Wasabi)

**Comment by davidzhao** [comment]
It has an S3 compatible API so you should already be able to use it.

**Comment by moshOntong-IT** [comment]
> It has an S3 compatible API so you should already be able to use it.

Do you have idea on how to connect my livekit console to that wasabi?
