### ISSUE TITLE
Broken Flutter UI on older version of Chrome

### ISSUE THREAD

**Issue by develocode777** [livekit/livekit#2554]
When running the example flutter app on an older version of chrome [(104.0.5112.102 from here, 2022-05-30 which is not that old)](https://www.slimjet.com/chrome/google-chrome-old-version.php) in the prejoin page if the camera is on the ui becomes broken like in the picture 

![Screenshot 2024-03-07 133517](https://github.com/livekit/livekit/assets/37084958/67cd1015-992a-451b-a867-de531b6543df)

This is on Win 11, haven't tested on macos or linux

**Comment by davidzhao** [comment]
this looks like an issue with the example app, rather than any of the core framework components.
