### ISSUE TITLE
When the publisher exits directly on the mobile browser, it takes a long time for the PC-based subscribers to receive the exit message.

### ISSUE THREAD

**Issue by klk2x** [livekit/livekit#2561]
**Describe the bug**
The subscriber opens it on the PC segment, and the publisher directly closes the web page or tab after joining the room on the mobile terminal.
If directly close the tab to exit instead of clicking hang up, the subscriber's screen will freeze, and it will take >5-10 seconds before the subscriber is considered to have left the meeting.

There is no problem if you close the tab directly on PC

I tried to use html5 `pagehide` and `beforeunload` events to handle it and close it manually, but it had no effect

It can also be reproduced in "https://meet.livekit.io/"

**Server**
- Version: [1.5.2]
- Environment: ubuntu 20

**Client**
- SDK: @livekit/components-core, @livekit/components-react client-sdk-js
- Version: latest

**To Reproduce**
1. two clients are connected to room
2. One of the publishers opens in a mobile browser, Safari or Chrome or in APP web
3. close publish mobile page or tab

log in pc close tab ：
`
rtc/signalhandler.go:58	client leaving room
`

log in mobile close tab ：
`
service/rtcservice.go:379	exit ws read loop for closed connection	
service/rtcservice.go:266	finishing WS connection
connectionquality/scorer.go:405	quality drop
rtc/transport.go:644	ice connection state change unexpected
rtc/transport.go:644	ice connection state change unexpected
`

Why is this situation not considered as leaving the room?
Subscribers will see a paused screen for a long time, which is a very bad experience.

**Comment by davidzhao** [comment]
this is expected, mobile browsers don't fire the right DOM events for us to know that they've left. if you need a more timely notification, please check ConnectionQuality.Lost event. As that will be fired within a few seconds.
