### ISSUE TITLE
How to implement push to talk?

### ISSUE THREAD

**Issue by denis-obukhov** [livekit/livekit#2571]
Hello! Could you suggest how to implement Walkie-Talkie functionality? When a speaker starts speaking a connection to the room is established. But listeners need some time to connect to listen to upon receiving a notification. Thus, they can miss the beginning. Every listener should be able to listen to the message from the very beginning regardless of the time needed to connect to the stream. Could you suggest how to implement this using LiveKit?

**Comment by davidzhao** [comment]
it's definitely possible to implement walkie-talkie. in fact one of the most popular walkie talkie apps in the store is using LiveKit.

However, you likely need a bit more coordination by using push notifications to wake up your app and join the call.

Closing the issue as the specific application behavior is outside of what the framework would be providing.

**Comment by ChrisFeldmeier** [comment]
Cool! With which func I can make VAD Silero silent or let to wait to commit the users speech?
