### ISSUE TITLE
How to host a production LiveKit server *without* WSS?

### ISSUE THREAD

**Issue by arnitdo** [livekit/livekit#2575]
Hey there! I'm currently working on a project where HTTPS or TLS security is not required for client-server connections, and could do just fine with a insecure ws:// URL. I do have a domain as well as reserved IP acquired.

The documentation over at [https://docs.livekit.io/realtime/self-hosting/deployment](https://docs.livekit.io/realtime/self-hosting/deployment/) doesn't really cover hosting a plain WS server. Is there any documentation regarding that? Would simply not including TURN in the config YAML work?

**Comment by davidzhao** [comment]
we do not cover it because it wouldn't be useful. browsers and other clients will not allow you to:
1. acquire media devices
2. connect to an insecure WebSocket
