### ISSUE TITLE
LiveKit Server Startup Error: Secret Key Length and Redis Connection Issues

### ISSUE THREAD

**Issue by cubxxw** [livekit/livekit#2582]
Hello LiveKit team,

I'm encountering a couple of issues when trying to start the LiveKit server on my environment. Below are the error logs and details regarding the issues:

1. **Secret Key Length Error**
   - During the startup, the LiveKit server logs an error related to the secret key length being too short. The exact log message is as follows:
     ```
     2024-03-17T04:59:09.818Z ERROR livekit config/config.go:668 secret is too short, should be at least 32 characters for security {"apiKey": "apioenimkey"}
     ```
   - It seems that the validation step for the secret/API key requires it to be at least 32 characters long. However, I'm unsure if this requirement has changed recently or if there's a specific format the key needs to follow.

2. **Redis Connection Refused**
   - Following the secret key length error, there's also an issue with connecting to Redis. The log indicates that the connection is refused:
     ```
     2024-03-17T04:59:09.820Z INFO livekit redis/redis.go:133 connecting to redis {"simple": true, "addr": "172.20.189.167:6379"}
     unable to connect to redis: dial tcp 172.20.189.167:6379: connect: connection refused
     ```
   - This issue occurs despite the Redis server being up and running, and accessible from other services within the same network.

I would appreciate any guidance or recommendations on resolving these issues. Specifically, I'm looking for:

- Confirmation on the secret/API key length requirement and any format it needs to comply with.
- Suggestions on troubleshooting the Redis connection issue, considering the server is operational and there haven't been recent changes to its configuration or network access rules.

**Comment by susanto-tm** [comment]
@cubxxw Did you figure out what went wrong in your setup for Redis connection?

**Comment by godlovegeekin** [comment]
same problem with you, got " connection refused" error even if my redis is accessible in the same network.

**Comment by davidzhao** [comment]
what is the network setup for Redis? which OS? and are you running livekit via Docker?

**Comment by davidzhao** [comment]
> i setup my redis standalone server in my own os x and running livekit via docker.

that is the problem, Redis by default only alllows localhost connections. Any application running within a docker container will not appear as localhost to Redis. You'll need to edit Redis configs to allow it to connect. This is not a livekit-specific issue.
