### ISSUE TITLE
BitrateScore is always MaxScore

### ISSUE THREAD

**Issue by holzgeist** [livekit/livekit#2585]
**Describe the bug**
We are not seeing any decrease in MOS even when the frame rate drops from 30 to 3 FPS. This is because the corresponding `AddBitrateTransition` is not called anywhere outside of tests.

**Server**
- Version: 1.5.3
- Environment: local dev

**Client**
- SDK: js
- Version: 2.0.6

**To Reproduce**
1. Setup a call
2. observe call statistics (e.g. by adding log output in `scorer.go:125 calculateBitrateScore`)

**Expected behavior**
MOS depends on bitrate/framerate and better reflects the observed call quality

**Screenshots**
N/A

**Additional context**
We added code to access data in the analytics service to monitor our setup in grafana.

**Comment by itzloop** [comment]
Hi, Any updates on this?

**Comment by boks1971** [comment]
Merged the ☝️ PR to provide an option to enable bit rate based scoring.

You can enable it
- [Here](https://github.com/livekit/livekit/blob/45581433ccf9500cfb2a672defbc878fa3453528/pkg/sfu/receiver.go#L225) for upstream/publisher side.
- [Here](https://github.com/livekit/livekit/blob/45581433ccf9500cfb2a672defbc878fa3453528/pkg/sfu/downtrack.go#L330) for downstream/subscriber side.

**Comment by holzgeist** [comment]
Awesome, thanks!

Do you have a rough idea when the next release is planned?

**Comment by boks1971** [comment]
Sorry for the delay on this. There is a v1.6.0 release now - https://github.com/livekit/livekit/releases/tag/v1.6.0
