### ISSUE TITLE
Disconnected without doing anything

### ISSUE THREAD

**Issue by frozenproof** [livekit/livekit#2610]
**Describe the bug**
LiveKitRoom/VideoConference simply stuck at Disconnected without throwing errors in either server orclient side in NextJs 14

**Server**
- Version: [^2.1.2]
- Environment: localhost
- NextJs 14 App Router

**Client**
- SDK: livekit-client
- Version: [^2.0.10]

**To Reproduce**
1. Create LIVEKIT_API_KEY, LIVEKIT_API_SECRET,NEXT_PUBLIC_LIVEKIT_URL as instructed by https://docs.livekit.io
2. Create TokenEndPoint Api Routes ,
3. Create a page which used fetch from api to get token and useeffect to save tokens
4. The API call works and send a readable token 
5. The client side doesn't throw any error 
6. The default video conference component simply show disconnected .
7. The example video conference component demo doesn't even show it's disconnected ?

**Expected behavior**
The room call should be running with proper token .
If token is incorrect / server refused the authorization then there would be a respond of unauthorized .

**Screenshots**
The token from server API 
![image](https://github.com/livekit/livekit/assets/118890894/40264d41-12b2-4ad8-9b4d-dcf69cdc6cb1)
The client side render
![image](https://github.com/livekit/livekit/assets/118890894/8111610e-0d3d-4a56-a555-56b7aced36ce)
The front end console log to see if token is indeed received 
![image](https://github.com/livekit/livekit/assets/118890894/77a2032d-f441-4ed0-b922-48b0798718bb)

**Additional context**
The guide is made for nextjs 13 , so I guess issue can come from here . But in such cases , an error would have been detected by the client sdk or server sdk and showed up .

**Comment by frozenproof** [comment]
![image](https://github.com/livekit/livekit/assets/118890894/470979d7-3b41-4814-aaa4-949810caa5f3)
I have checked and added await but still doesn't work .

**Comment by Mohammedyaseen29** [comment]
Make sure Your Api-keys are correct!!
it will work or re-create new keys

**Comment by frozenproof** [comment]
@Mohammedyaseen29 I checked if my keys were correct using the example app so I knew it's running . But it just suddenly run again so I don't know what happened . Probably an API choke happened for several days due to outdated packages .
