### ISSUE TITLE
If deploy on server, how many people can support at same time on a 4GB memory server?

### ISSUE THREAD

**Issue by OpenJarvisAI** [livekit/livekit#2620]
If deploy on server, how many people can support at same time on a 4GB memory server?

**Comment by davidzhao** [comment]
that depends on what your application is pushing through to the server. please perform your own benchmarks.

**Comment by OpenJarvisAI** [comment]
Can u just give me some estimations? ...... What's the minial requirements to setup the server and how many connections does can have per GB mem...

As a lib maintainer don't just close user's puzzels without any useful information....
