### ISSUE TITLE
What is a `Track` as Mentioned in the React Documentation?

### ISSUE THREAD

**Issue by thecherrie** [livekit/livekit#2642]
I'm reading (https://docs.livekit.io/realtime/quickstarts/react/) but I cannot see where `Track` in _`Track.Source.Camera`_ is found? What is `Track`? It is not exported from `from "@livekit/components-react"`. Is this a typo in the documentation?

<img width="543" alt="image" src="https://github.com/livekit/livekit/assets/14931384/c3918265-7e0a-4860-81bb-9597f91fcdf1">

**Comment by jamealg** [comment]
It's apparently exported from `livekit-client`. I'm also running into some issues trying to follow the next.js quickstart but it might be worth [taking a look at that one](https://docs.livekit.io/realtime/quickstarts/nextjs-13/) for some reference.

**Comment by davidzhao** [comment]
Thanks for pointing this out! we'll get the docs fixed shortly.

**Comment by jamealg** [comment]
Thanks @davidzhao . FWIW the issues I was running into with the next.js quickstart is that `RoomAudioRenderer`, `Controlbar`, and `useTracks` weren't imported. I'm not sure if this is the best place to report docs issues but let me know if you'd like me to open a separate ticket for that.

**Comment by davidzhao** [comment]
this is great. I'll take care of those as well. Thanks @jamealg!

**Comment by davidzhao** [comment]
all fixed, closing.
