### ISSUE TITLE
How to add third party participants with a single "sendrecv" PeerConnection

### ISSUE THREAD

**Issue by ypedegroot** [livekit/livekit#2645]
I am currently using LiveKit SFU to implement various scenarios, including one where I need to connect a third party that only allows a **single** `PeerConnection` to be used, with a `sendrecv` offer (or answer). I have no control over the workings of this third party WebRTC client.

I understand that in the LiveKit SFU architecture, **two** `PeerConnections` are used: one for publishing and one for subscribing. How would I proceed with connecting a third party client as described above to a LiveKit `Room`? I use the client protocol (protobuf) to communicate with the LiveKit SFU server using websockets. Any help is greatly appreciated.

**Comment by cnderrauber** [comment]
The sfu don't support a single `sendrecv` peerconnection, but I think you can use the [server sdk](https://github.com/livekit/server-sdk-go) to build a bridge to help the third party client to access sfu like this:
