### ISSUE TITLE
How to distinguish different audio tracks?

### ISSUE THREAD

**Issue by denis-obukhov** [livekit/livekit#2651]
Hello! How to distinguish different audio tracks between publications? The LiveKit server returns the same publication/track sid every time.

**Comment by davidzhao** [comment]
It's not clear what you are asking.. please provide additional information including steps to demonstrate your use case.

**Comment by denis-obukhov** [comment]
@davidzhao  [This is ](https://github.com/livekit/client-sdk-swift/commit/bbfe82466d66e11b5fdb64c0a909a576c239e56c)what I've done to implement my goal. Not sure, if it's useful for everyone. But the idea is to have different remote track id for every publication

**Comment by davidzhao** [comment]
I see, I understand you are trying to disable the same track SID being returned during multiple attempts of publish & unpublish sequences.

This is a reasonable workaround. Thanks for sharing!

Closing this issue for now.
