### ISSUE TITLE
Participant counting API returns negative values

### ISSUE THREAD

**Issue by youngSSS** [livekit/livekit#2679]
**Describe the bug**
- Participant count bug
- A bug in version 1.6.0 returns negative values while collecting a matrix via API to get the number of participants from Grafana. 

**Server**
- Version: [1.6.0]
- Environment: [EKS]

**Expected behavior**
- To be fixed

**Screenshots**
<img width="1889" alt="image" src="https://github.com/livekit/livekit/assets/48302757/29a3f900-f72d-4fb7-aeae-eac12b4e82c5">

**Comment by davidzhao** [comment]
this is fixed by #2672, we'll cut a new build shortly.
