### ISSUE TITLE
how to reduce noise and echo

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/livekit#2707]
dear author,
    when i try to use huawei pad to join a livekit room,the echo and noise is very loudly . Is there any funcion to solve the issue by code in the livekit_server? thanks anyway!

**Comment by davidzhao** [comment]
Hey @Hollymingyi, as an SFU, this isn't something livekit-server would be responsible for. Mobile SDKs should have solid echo cancellation. You just have to put the device in communication mode using methods provided by our SDK. Please reference the docs for the appropriate SDK for details.

**Comment by Hollymingyi** [comment]
ok，thank u，i will have a try
