### ISSUE TITLE
Wrong connnectionQuality state

### ISSUE THREAD

**Issue by AurimasG12** [livekit/livekit#2716]
### Describe the bug

As user, I want to see correct network indicators.
Now as a local user, I can see my network indicator as having excellent connection quality, but others see three gray bars (unknown state).
<img width="1440" alt="image" src="https://github.com/livekit/client-sdk-js/assets/51153447/4a3eefbd-fefb-48ce-b345-5cfe95ab6458">

### Reproduction

1. Join meet.livekit.io meeting with participant A (turn off camera and microphone)
2. Join meet.livekit.io meeting with participant B (with camera on, mic on)
3. Check network indicators

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1
    Memory: 136.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.207
    Edge: 124.0.2478.105
    Safari: 17.1
```

### Severity

blocking an upgrade

**Comment by lukasIO** [comment]
@AurimasG12 you closed the issue, did the issue go away for you?

**Comment by Stogas** [comment]
@lukasIO it seems he re-opened it at https://github.com/livekit/livekit/issues/2717
