### ISSUE TITLE
Distributed multi-region

### ISSUE THREAD

**Issue by bigmoveus** [livekit/livekit#2720]
Hi i want to setup livekit server in 3 different location (VPS Servers) and i could install them separately  but  document has not more detail information for this ability . 

https://docs.livekit.io/home/self-hosting/distributed/

Could you please write more information ? and also i ready to pay for this ability i sent several emails but no one answer at all . 

hope can get answer ! Thank you .

**Comment by cnderrauber** [comment]
Do you have redis configured in your config?

**Comment by bigmoveus** [comment]
HI , I did but could not manage it i am ready for pay to manage it . if possible send me your email my email is : m.sheikhian@ymail.com 

Thank you .

**Comment by cnderrauber** [comment]
If you are ready to pay for it then I would suggest you try the livekit-cloud service since operating a multi-region service is hard if you don't have expertise in the domain.

**Comment by bigmoveus** [comment]
Hi , the subject is i need to use in our own server we have 3 location and cannnot use outside of our datacenter . we could install standalone but need use multi-region . if you can help me .

**Comment by leejiliang** [comment]
> Hi , the subject is i need to use in our own server we have 3 location and cannnot use outside of our datacenter . we could install standalone but need use multi-region . if you can help me . we already use with domain and also cloudflare . if you can help please do ,



> Hi , the subject is i need to use in our own server we have 3 location and cannnot use outside of our datacenter . we could install standalone but need use multi-region . if you can help me . we already use with domain and also cloudflare . if you can help please do ,

I'm facing the same problem

**Comment by leejiliang** [comment]
> Hi , the subject is i need to use in our own server we have 3 location and cannnot use outside of our datacenter . we could install standalone but need use multi-region . if you can help me . we already use with domain and also cloudflare . if you can help please do ,

I'm facing the same problem

**Comment by cnderrauber** [comment]
You need to make all sfu servers connect to same redis server/cluster and uncomment the `node_selector` setting in the config sample then use dns to resolve the domain to your sfu node's ip.

**Comment by bigmoveus** [comment]
@cnderrauber Please share your personal email or ... send me an email to m.sheikhian@ymail.com .

**Comment by davidzhao** [comment]
Please follow the instructions cnderrauber has provided. We cannot provide hands-on assistance for deployments
