### ISSUE TITLE
Egress for data messages?

### ISSUE THREAD

**Issue by hakotaco** [livekit/livekit#2727]
Hey! I'm building a web-app that uses the data messages bit quite heavily (along with audio conferencing). Although Egress for Audio was made pretty clear in the docs, I wanted to know if there's a way to listen to data messages published? I tried but couldn't find any documentation regarding it and it's something that would help me a lot. 

I want to save the data messages being published asynchronously in my database so just wanted to know if there's a way to listen to them because if not, then the only way would be to set up a separate websocket server which would otherwise seem redundant.

**Comment by davidzhao** [comment]
Currently Egress does not export data messages separately. Your best bet is to connect to LiveKit as a server-side participant and save the messages that way.
