### ISSUE TITLE
Build a standalone chat app with LiveKit?

### ISSUE THREAD

**Issue by iAbdulaziz93** [livekit/livekit#2777]
Hi,

Is it possible to build a standalone chat app using LiveKit without integrating audio and video? If yes, is LiveKit Room necessary here to use the chat service?

Also, can I use the **livekit_client** package for Flutter to build the chat app?

Thanks.

**Comment by iAbdulaziz93** [comment]
Hi @dennwc, @davidzhao.

Any idea about this?

**Comment by dennwc** [comment]
Hi! You mean regular text chat app?

Yes, it's possible via WebRTC Data Channel. You can send custom messages via LiveKit and do not publish any audio/video tracks. Flutter SDK should also support it. And yes, rooms are still necessary for this.

But I think requirements for chat apps are different comparing to real-time communication systems like LiveKit. For chat you probably want to persist and sync messages. LiveKit doesn't store these data messages, it only relays them between live participants.

Thus, if you to sync messages history it's better to pick Matrix, RocketChat or any other open-source chat system.

**Comment by iAbdulaziz93** [comment]
@dennwc Nice! One more question if you allow me, do you have any LiveKit chat apps only examples? Like open-source chat apps built using LiveKit, etc. So, I can take a look into them.
