### ISSUE TITLE
Run binary from source not working

### ISSUE THREAD

**Issue by sweatpotato13** [livekit/livekit#2780]
**Describe the bug**
I tried to build and running from source. 

building is fine, but running is not work

**Server**
- Version: https://github.com/livekit/livekit/commit/29614cd4a189306177f5b034225723cd3c2b7ed0
- Environment: Local, macOS 14.5
- any other information about your deployment setup: go version go1.22.4 darwin/arm64

**To Reproduce**
1. git clone https://github.com/livekit/livekit
2. ./bootstrap.sh
3. mage
4. ./bin/livekit-server --dev
and stock

**Expected behavior**
Working

**Screenshots**

* Terminal
![ss](https://i.imgur.com/PLF0BXz.png)

* Error log from livekit-meet
![ss](https://i.imgur.com/cDMASal.png)

**Comment by sweatpotato13** [comment]
```shell
./bin/livekit-server --dev
[1]    7554 killed     ./bin/livekit-server --dev
```

process killed immediately

**Comment by sweatpotato13** [comment]
Same process in Ubuntu 22.04 is working fine
does macOS have other build process?

**Comment by davidzhao** [comment]
The build process is the same, it's working for us here.. can you check system logs and/or dmesg to see why it was killed?

**Comment by sweatpotato13** [comment]
> The build process is the same, it's working for us here.. can you check system logs and/or dmesg to see why it was killed?

How can I get log from macOS?

**Comment by davidzhao** [comment]
seems like a code signing error.. it's not clear why this would happen. but maybe give [this](https://github.com/golang/go/issues/63997) a try?
