### ISSUE TITLE
The shared image is blurry

### ISSUE THREAD

**Issue by 277861535** [livekit/livekit#2783]
**Describe the bug**
The shared screen is a little more blurry than the original screen, and the rtmp stream screen exported from the egress service is even more blurry.I don't know if the encoding parameters set when the livekit sdk is docked on the push stream side are incorrect, or if the performance is insufficient due to the low configuration of the server where the egress is located..Why is it not possible to set VideoCodec.vp9 when exporting streams to EGress.Do you have any suggestions for improving the clarity of the image
![watch](https://github.com/livekit/livekit/assets/37997931/87c99c5d-2895-47aa-bf00-66b02011fe76)
![original](https://github.com/livekit/livekit/assets/37997931/aba661d7-8dbf-4d62-beb0-ccb749cf2a2c)

**Server**
livekit-1.5.1
egress-1.8.0

**Additional context**
1080p/30fps/3000Bitrate/VideoCodec.H264_HIGH

**Comment by Aktharnvdv** [comment]
try below configuration:                                                                                                                                video_options = rtc.TrackPublishOptions(
        source=rtc.TrackSource.SOURCE_CAMERA,
        simulcast=False,
        video_encoding=rtc.VideoEncoding(max_framerate=30, max_bitrate=3_000_000),
        video_codec=rtc.VideoCodec.H264,
    )
    video_options.source = rtc.TrackSource.SOURCE_CAMERA
