### ISSUE TITLE
Access token TTL does not work

### ISSUE THREAD

**Issue by AurimasG12** [livekit/livekit#2804]
**Describe the bug**
I have an access token, whose TTL is 5s. I connect to the room with that access token, and after 5s I turn off my network (to get into the reconnecting state), and since I am reconnecting with participant A, I kick him from the room and turn on my network back and he can reconnect successfully to the room, but token should be invalid at this time.

**Server**
- Version: [1.6.1]
- Environment: [e.g. local dev, EKS]
- any other information about your deployment setup

**Client**
- SDK: [e.g. js, ios] 
- Version: [2.0.10]

**To Reproduce**
1. two clients are connected to the room
2. One client turns off his network off
3. Remove the reconnecting participant from the room.
4. Turn the internet back on so removed participant is able to connect back

**Expected behavior**
Removed participant should not be able to connect back

**Comment by davidzhao** [comment]
This is expected. Tokens are refreshed with connected client automatically to ensure they can reconnect. [docs](https://docs.livekit.io/home/get-started/authentication/#Token-refresh)
