### ISSUE TITLE
The 'Pods-Vetcation' target has frameworks with conflicting names: webrtc.xcframework.

### ISSUE THREAD

**Issue by geoffcfchen** [livekit/livekit#2809]
**Describe the bug**
When building an Expo project with EAS, there is a conflict with the webrtc.xcframework included by both livekit-react-native and react-native-webrtc. This conflict prevents the build process from completing successfully. Note that I have already had react-native-webrtc installed before and use it for my calling function. 

SDK: Expo
Version: 50.0.19
Additional dependencies:
livekit-react-native: 2.2.0
react-native-webrtc: 118.0.3

**To Reproduce**
1. Add livekit-react-native and react-native-webrtc as dependencies in an Expo project.
2. Configure the project with the following plugins:
@livekit/react-native
@livekit/react-native-expo-plugin
@config-plugins/react-native-webrtc
....
3. Run the EAS build process (eas build).
4. See error related to conflicting webrtc.xcframework.

**Expected behavior**
The build process should complete successfully without conflicts, and both livekit-react-native and react-native-webrtc should work together seamlessly.

**Comment by davidzhao** [comment]
Unfortunately, this is unavoidable as LiveKit also bundles our own version of react-native-webrtc and WebRTC framework. The workaround is to use our copy of WebRTC framework, instead of also bundling in react-native-webrtc.

**Comment by khali70** [comment]
I have same problem but with flutter livekit_client
