### ISSUE TITLE
websocket: bad handshake

### ISSUE THREAD

**Issue by leejiliang** [livekit/livekit#2810]
**Describe the bug**
2024-06-21T19:57:52.182+0800    ERROR   livekit-cli     v2@v2.1.1/signalclient.go:146   error establishing signal connection    {"status": 500, "error": "websocket: bad handshake"}
github.com/livekit/server-sdk-go/v2.(*SignalClient).connect /home/runner/go/pkg/mod/github.com/livekit/server-sdk-go/v2@v2.1.1/signalclient.go:146
github.com/livekit/server-sdk-go/v2.(*SignalClient).Reconnect/home/runner/go/pkg/mod/github.com/livekit/server-sdk-go/v2@v2.1.1/signalclient.go:95
github.com/livekit/server-sdk-go/v2.(*RTCEngine).resumeConnection/home/runner/go/pkg/mod/github.com/livekit/server-sdk-go/v2@v2.1.1/engine.go:572
github.com/livekit/server-sdk-go/v2.(*RTCEngine).handleDisconnect.func1/home/runner/go/pkg/mod/github.com/livekit/server-sdk-go/v2@v2.1.1/engine.go:549
2024-06-21T19:57:52.187+0800    INFO    livekit-cli     v2@v2.1.1/signalclient.go:167   validate succeeded
2024-06-21T19:57:52.187+0800    ERROR   livekit-cli     v2@v2.1.1/engine.go:550 resume connection failed        {"error": "could not establish signal connection"}
github.com/livekit/server-sdk-go/v2.(*RTCEngine).handleDisconnect.func1/home/runner/go/pkg/mod/github.com/livekit/server-sdk-go/v2@v2.1.1/engine.go:550
2024-06-21T19:57:52.187+0800    INFO    livekit-cli     v2@v2.1.1/engine.go:548 resuming connection...  {"reconnectCount": 1}

**Server**
- Version: [1.6.1]
- Environment: [docker on ubuntu]
- any other information about your deployment setup

**Client**
- SDK: [server-sdk-go]
- Version: [v2.1.2]

**To Reproduce**
1. I have a server-side program that listens to the "room_started" event of the server-side through webhook and joins it. lksdk.ConnectToRoom (xx,yy,zz)
2. Run the CLI script to create a batch of rooms and join them. livekit-cli join-room --room xxx --identity yyy
3. When the number of times I loop is relatively small, such as creating 100 or less every 10 seconds or so, everything is normal, the room is normally created, and both client and server participants can normally join the room.
4. When I create more than 300 rooms in a single loop, the server starts reporting errors, stating error establishing signal connection {"status": 500, "error": "websocket: bad handshake"}

**Expected behavior**
The client and server can join the room normally

**Comment by davidzhao** [comment]
the likely cause is you are running out of filehandles or other resources. https://github.com/livekit/livekit-cli?tab=readme-ov-file#configuring-system-settings
