### ISSUE TITLE
[Question] LiveKit with local network and no internet connection.

### ISSUE THREAD

**Issue by DanielBerrioB** [livekit/livekit#2817]
Hi!

Hope you can give me any hint of the implementation I'm trying please.
I'm using LiveKit in a local network, it's a Windows app, sometimes with no internet connection but all the devices are connected to the same network. It turns out that when there's no internet connection LiveKit doesn't work and I get an error in `signal_client.dart` line 121.
I'd like to know if this approach is possible with the current version of LiveKit.

I'm using the following stack:
- Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)
- livekit_client: 2.1.5 (Flutter version).
- I'm using this LiveKit server version (1.6.1)

Thanks in advance. I'd really appreciate any hint or response. And any additional info I'll be willing to provide you.

**Comment by davidzhao** [comment]
Please do not file duplicate tickets across repos.
