### ISSUE TITLE
Serious issues - Black screen for local recording and external camera streaming failure

### ISSUE THREAD

**Issue by RXlung** [livekit/livekit#2824]
Thank you to everyone who helped me.

**Describe the bug**
I downloaded the android project and go deployment, both from the May 2023 version.
android: 1.2.0
go: 1.4.2
I didn't make any changes, just the url and token. Run sample-app-record-local, either push the stream, the other party can not see, or save the local is no picture only sound.
**To Reproduce**
1. Samsung android10 device can push the stream, but when saved locally, there is no picture only sound.
![image](https://github.com/livekit/client-sdk-android/assets/21995371/54f51afd-c5ea-4697-9fde-67b60387c29e)
![image](https://github.com/livekit/client-sdk-android/assets/21995371/dbe7fc9c-da76-4b45-bde0-1e8e993741de)
2. The Hongmeng 2 system can crash directly when pushing disconnectRoom, and there is no picture only sound when saved locally. When I combine room.disconnect() and videoFileRenderer? When the.release() lines were swapped, an error was reported, but the video was saved
![image](https://github.com/livekit/client-sdk-android/assets/21995371/57a980e1-0c88-4757-ac53-9547eaf5f453)
3. Customized devices based on android 12 use usb external camera, run sample-app, you can see the camera screen on the app page, and the other end (https://meet.livekit.io/? tab=custom) can not be seen, only see someone join, but the screen is black. And save local video is no picture only sound.
![image](https://github.com/livekit/client-sdk-android/assets/21995371/41524db4-eadb-4b4b-bc66-ab8a816cfade)
![image](https://github.com/livekit/client-sdk-android/assets/21995371/956f2795-492a-432f-8fd1-e54daaf48d57)

**Expected behavior**
Push the other party can see, save the video has a picture。I think the 8000 star project, demo should run directly without too much configuration can be learned. There shouldn't be so many problems.

**Screenshots**
The reproduction step corresponds to the screenshot

**Device Info:**
- Device: Three devices as described above
- LiveKit SDK version: [e.g. 1.4.2]     android demo [e.g:1.2.0]

**Comment by davidzhao** [comment]
please do NOT file dupe issues across repos
