### ISSUE TITLE
Support for other audio codecs, such as G.711 (PCMA, PCMU) or G.722

### ISSUE THREAD

**Issue by ypedegroot** [livekit/livekit#2828]
Since livekit is built with the amazing pion library, I wonder why audio codecs such as `G.711` (`PCMA`, `PCMU`) or `G.722` are not supported. The pion library supports all these codecs.

When I offer an SDP to a Room, I always get a response offering only `opus/48000` and `RED`. When working with some (legacy) participants (who do not offer `opus/48000` or `RED`), this immediately leads to a pion "unable to start track, codec is not supported by remote" error.

Is it possible to add support for other codecs? If not, what would be an alternative approach?

**Comment by davidzhao** [comment]
@ypedegroot it's definitely possible to add support for other audio codecs, we just have not prioritized them because Opus is supported everywhere and is a better choice for the vast majority of situations

What is your use case for other codecs?

**Comment by davidzhao** [comment]
codec support in an SFU system is quite tricky. as long as a single participant publishes a track with a certain codec to a session, *everyone* would need the ability to decode it.

when interacting with existing phone systems, we have a [dedicated service](https://github.com/livekit/sip) that acts as an MCU in order to mix all incoming audio into the same stream. This is necessary in order to support the use case of a single user dialing into a conference with multiple people. I don't believe it's possible to skip the media processing step here

are there other use cases for alternative audio codecs?

**Comment by davidzhao** [comment]
LiveKit server will not support MCU/transcoding capabilities.

**Comment by rohitkhatri** [comment]
@ypedegroot I'm also facing this problem, can you share your changes that you did to support G.711 or PCM codec?

**Comment by Flangad** [comment]
very interesting issue. Don't you think that the support for end to end PCM 8/16kHz in Livekit could allow to build much less CPU intensive applications? That's something very important for applications that manage thousands of concurrent calls. Isn't PCM16 to OPUS encoding/transcoding CPU intensive? In many cases, PCM 8/16kHz could be good enough!

**Comment by shahzaibaqeel** [comment]
@Flangad @davidzhao Hey Facing same issue, we are trying conqurrent calls but the sip service is exhausted under that transcoding computation. Is there any solution for that like livekit should use same codec no transcoding etc as on just 10 concurrent calls sip service get exausted on upto 80%. Like for telephony we are stuck in that sip service computation and like then scalling cost for that sip service.

**Comment by pedroslev** [comment]
hi there, we are also facing a similar problem. We are using livekit to handle incoming and outbound sip calls as well as videocalls via web. PSTN carriers mostly do PCMU PCMA at 8khz at LATAM. Would be great to have support to handle dynamic room configs

**Comment by tomimuso** [comment]
Hi! We're running into the same issue. We use LiveKit for both inbound and outbound SIP calls, as well as web-based video calls. In LATAM, most PSTN carriers only offer PCMU/PCMA at 8 kHz, so native support for these codecs, along with the ability to configure rooms dynamically, would be really helpful for us.

**Comment by german-segovia91** [comment]
We would also benefit from native support for G.711 codecs (PCMU and PCMA) at 8 kHz in LiveKit.

We are working with telephony systems where PCMU/PCMA at 8 kHz are commonly used, so having native support for these codecs would make integration much simpler and avoid the need for additional transcoding or workarounds.

+1 from our side for this feature request. Thanks!

**Comment by TomasBruzzesi** [comment]
+1 on this. We're in a similar situation: we use LiveKit for SIP calls and web-based calls, and most carriers we work with in LATAM only support PCMU/PCMA at 8 kHz.

Native G.711 support, plus the ability to set codec preferences per room (e.g. when creating the room or via the SIP dispatch rule), would let us avoid extra transcoding and reduce both latency and CPU usage on our side.

Happy to help test if there's a branch or preview available. Thanks!
