### ISSUE TITLE
Title: Camera Access Issue on iPhone 14 Pro in Telegram's Built-In Browser

### ISSUE THREAD

**Issue by OldSchool1705** [livekit/livekit#2846]
I'm experiencing a problem with camera access on iPhone 14 Pro when using the built-in browser in the Telegram app. The issue is that the phone continuously prompts for camera access, making it impossible to use the camera functionality.

Steps to Reproduce:

Open a link in the Telegram app on an iPhone 14 Pro.
Attempt to access the camera through the built-in browser.
Expected Behavior:
The browser should prompt for camera access once and then allow the user to use the camera.

Actual Behavior:
The browser repeatedly prompts for camera access without granting it, creating an endless loop.

Device Information:

Device: iPhone 14 Pro
iOS Version:  17.5.1

the project for the React

**Comment by davidzhao** [comment]
what you are describing is not an issue with livekit server. which client SDK are you using? I would suggest updating to the latest version of the SDK and filing the issue in the appropriate repo if it can be reproduced.

Please include repro steps with an application that we have access to (ideally something like [LiveKit Meet](https://meet.livekit.io)
