### ISSUE TITLE
Connection problems when working with redis

### ISSUE THREAD

**Issue by mbakumenkov** [livekit/livekit#2874]
**Describe the bug**
If livekit server runnig with configured redis setup under the load test it stops accepting new clients and drop old ones. Without redis configuration everything works fine

**Server**
- Version: 1.7.0
- Environment: remote servers
- Both servers are 10Gbps network, Intel(R) Xeon(R) Gold 6336Y CPU @ 2.40GHz, 240 GB RAM

**Client**
- Livekit-cli 2.0.4
- https://meet.livekit.io/

**To Reproduce**
Preconditions: 1 Livekit server configured with redis (redis on separated machine), 1 load test server.
1. Enter to the testroom with https://meet.livekit.io/
2. Start load testing from the test server to the livekit server by `livekit-cli load-test --room testroom --subscribers 750 --audio-publishers 1 --video-publishers 10`
3. Wait until the most participants entered
Got infinite "reconnecting" state until you stop stress testing

**Expected behavior**
All works fine, you can create new rooms, either join to the existed

**Screenshots**
Node exporter of Livekit server in problematic moments (1 test - got problem, stop test and 2nd one with problem too)
![image](https://github.com/user-attachments/assets/de005707-2329-4240-9d16-89afdc3d539f)

**Additional context**
Livekit server logs in that time
`Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.209+0300        INFO        livekit        rtc/participant.go:874        participant closing        {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "sendLeave": false, "reason": "SIGNAL_SOURCE_CLOSE", "isExpectedToResume": false}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.209+0300        INFO        livekit        rtc/room.go:590        removing participant without connection        {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "subscriberCandidates": ["[local] udp4 srflx 194.1.214.99:48511 related 0.0.0.0:48511", "[local] udp4 srflx 194.1.214.99:46193 related 0.0.0.0:46193", "[local] udp4 srflx 194.1.214.99:48508 related
0.0.0.0:48508"], "connectionType": "unknown", "reason": "NONE"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.213+0300        INFO        livekit.transport.pion.pc        v3@v3.2.40/peerconnection.go:498        peer connection state changed: closed        {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "transport": "PUBLISHER"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.214+0300        WARN        livekit.transport.pion.ice        v2@v2.3.24/gather.go:35        failed to get server reflexive address udp6 stun:stun1.l.google.com:19302: read udp6 [::]:42307: use of closed network connection        {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "transport": "SUBSCRIBER"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.214+0300        WARN        livekit.transport.pion.ice        v2@v2.3.24/gather.go:37        Failed to close connection: close udp6 [::]:42307: use of closed network connection
    {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "transport": "SUBSCRIBER"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.214+0300        WARN        livekit.transport.pion.ice        v2@v2.3.24/gather.go:35        failed to get server reflexive address udp6 stun:stun.l.google.com:19302: read udp6 [::]:40473: use of closed network connection        {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "transport": "SUBSCRIBER"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.214+0300        WARN        livekit.transport.pion.ice        v2@v2.3.24/gather.go:37        Failed to close connection: close udp6 [::]:40473: use of closed network connection
    {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "transport": "SUBSCRIBER"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.214+0300        WARN        livekit.transport.pion.ice        v2@v2.3.24/gather.go:114        Failed to set gatheringState to GatheringStateComplete: the agent is closed        {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "transport": "SUBSCRIBER"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.214+0300        INFO        livekit.transport.pion.pc        v3@v3.2.40/peerconnection.go:274        signaling state changed to have-local-offer        {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_759", "pID": "PA_yFhRLXmsccHh", "remote": false, "transport": "SUBSCRIBER"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.215+0300        INFO        livekit.transport.pion.ice        v2@v2.3.24/agent.go:517        Setting new connection state: Closed        {"room": "testroom", "roomID": "RM_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "transport": "SUBSCRIBER"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.215+0300        INFO        livekit.transport.pion.pc        v3@v3.2.40/peerconnection.go:498        peer connection state changed: closed        {"room": "testroom", "roomID": "RM
_hL4pD8rMErJ4", "participant": "lmlkm_739", "pID": "PA_Fqz2PLNQKdmA", "remote": false, "transport": "SUBSCRIBER"}
Jul 17 12:19:35 testserver livekit-server[1117703]: 2024-07-17T12:19:35.318+0300        ERROR        livekit        routing/localrouter.go:99        could not handle new participant        {"room": "testroom", "participant": "lmlkm_684", "connID": "CO_tXiFGWVgVEdy", "error": "request timed out"}
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/livekit/livekit-server/pkg/routing.(*LocalRouter).StartParticipantSignalWithNodeID
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.7.0/pkg/routing/localrouter.go:99
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).StartParticipantSignal
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.7.0/pkg/routing/redisrouter.go:172
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/livekit/livekit-server/pkg/service.(*RTCService).startConnection
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.7.0/pkg/service/rtcservice.go:543
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/livekit/livekit-server/pkg/service.(*RTCService).ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.7.0/pkg/service/rtcservice.go:230
Jul 17 12:19:35 testserver livekit-server[1117703]: net/http.(*ServeMux).ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2683
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/urfave/negroni/v3.(*Negroni).UseHandler.Wrap.func1
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:59
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/urfave/negroni/v3.HandlerFunc.ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:33
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/urfave/negroni/v3.middleware.ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51
Jul 17 12:19:35 testserver livekit-server[1117703]: net/http.HandlerFunc.ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/livekit/livekit-server/pkg/service.(*APIKeyAuthMiddleware).ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.7.0/pkg/service/auth.go:107
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/urfave/negroni/v3.middleware.ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/rs/cors.(*Cors).ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/rs/cors@v1.11.0/cors.go:324
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/urfave/negroni/v3.middleware.ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/urfave/negroni/v3.(*Recovery).ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/recovery.go:210
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/urfave/negroni/v3.middleware.ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51
Jul 17 12:19:35 testserver livekit-server[1117703]: github.com/urfave/negroni/v3.(*Negroni).ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:111
Jul 17 12:19:35 testserver livekit-server[1117703]: net/http.serverHandler.ServeHTTP
Jul 17 12:19:35 testserver livekit-server[1117703]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:3137
Jul 17 12:19:35 testserver livekit-server[1117703]: net/http.(*conn).serve
Jul 17 12:19:35 testserver livekit-server[1117703]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2039`

**Comment by zoujiaqing** [comment]
How to resolve this problem? @mbakumenkov 

Notice:
could not handle new participant

thanks.
