### ISSUE TITLE
next js server for agents implementation

### ISSUE THREAD

**Issue by echohive42** [livekit/livekit#2889]
Hi there livekit team,. 

Is there any code examples, or related docs for running a room with agents as an API route within a Next JS 14 application? or however else might be the next best solution to not having 2 separate servers for livekit(python server) + next js app

thank you for your time in advance

**Comment by davidzhao** [comment]
You'd want to run agents separately, the pattern there is background workers pulling for jobs instead of a HTTP server getting pushed requests
