### ISSUE TITLE
remote assist 

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/livekit#2894]
dear author ,
   can i do some extra assist to the remote participant video track ,the function like remote assist of microsoft HoloLens2.  The video url [HoloLens 2](https://learn.microsoft.com/zh-cn/hololens/hololens2-cloud-connected-overview).  Or do we have the plan to implement it.

**Comment by davidzhao** [comment]
you can add remote control yourself by sending control signals over data channels. we will not be adding this capability to livekit natively for now.
