### ISSUE TITLE
Use SIP to connect to zoom calls? 

### ISSUE THREAD

**Issue by aldrinjenson** [livekit/livekit#2897]
Hey, 
I went through the SIP quickstart (https://docs.livekit.io/sip/quickstart/ ) and was wondering if we could use this to connect to zoom calls which supports the ability to join by phone.

I was able to get an outbound call set up with normal phone numbers with livekit.

For zoom specifically, it needs people to join and then enter DTMF codes in a specific format (meeting Id, #, password #)
I did follow the example to set that up as given in the docs: 
https://docs.livekit.io/sip/sip-participant/#Making-a-call-with-extension-codes-DTMF-

though this did not work out. 
I even tried by adding wait times like the following:     

{
	"sip_trunk_id": "trunkId",
	"sip_call_to": "phone number given by zoom",
    "dtmf": "wwww\<meetingId\>#wwwww*\<password\>#",
	"room_name": "my-sip-room",
	"participant_identity": "sip-test",
	"participant_name": "Test Call",
         "play_ringtone": true
}

and ran it like `lk sip participant create sipParticipantWithDTMF.json`

This did not work at all, and I'm not sure how to debug this issue as well.

Please let me know if this approach is right or if there's something I'm majorly missing. And how does one usuallly debug these kinda DTMF tones as well?

**Comment by davidzhao** [comment]
We've made some improvements to our DTMF support in SIP. I believe this should work now. Please try the latest commit from https://github.com/livekit/sip, or test with LiveKit Cloud
