### ISSUE TITLE
call stopEgress return "no response from servers"

### ISSUE THREAD

**Issue by shoyu666** [livekit/livekit#2903]
**Describe the bug**
call stopEgress return "no response from servers",maybe egress or livekit bug
Why did this problem occur？
The differences between them ？see blow（EG_8rfZTZ3e7Hy3,EG_3FYXySRDz8qr,EG_3FYXySRDz8nn）
**To Reproduce**
just call stopEgress,sometimes return return no response from servers
```
EG_8rfZTZ3e7Hy3 exist
//k egress stop --id EG_8rfZTZ3e7Hy3 --url http://192.168.0.87:7880
Error stopping Egress EG_8rfZTZ3e7Hy3 twirp error unavailable: no response from servers
twirp error unavailable: no response from servers

EG_3FYXySRDz8qr exist
//lk egress stop --id EG_3FYXySRDz8qr --url http://192.168.0.87:7880 
Error stopping Egress EG_3FYXySRDz8qr twirp error failed_precondition: egress with status EGRESS_COMPLETE cannot be stopped
twirp error failed_precondition: egress with status EGRESS_COMPLETE cannot be stopped

EG_3FYXySRDz8nn It doesn't really exist，just mock
//lk egress stop --id EG_3FYXySRDz8nn --url http://192.168.0.87:7880
Error stopping Egress EG_3FYXySRDz8nn twirp error not_found: egress does not exist
twirp error not_found: egress does not exist
```

**Device Info:**
sdk version :io.livekit:livekit-server:0.6.1
egress version:1.8
livekit version:1.7
lk:2.0.4

**Additional context**
https://github.com/livekit/livekit/issues/2362
https://github.com/livekit/egress/issues/739
https://github.com/twitchtv/twirp/issues/395

**Comment by davidzhao** [comment]
please stop filing duplicates
