### ISSUE TITLE
NO Response from server when using Egrees

### ISSUE THREAD

**Issue by ParsaBordbar** [livekit/livekit#2904]
We have set up a server with livekit docker from the documents  ( self-hosting ).
The Services Run corectly on the server, But when start a new room, and generate it and pass token and secret token and server's url ( which starts with wss ) , using CLI, for sending an Egrees start composite, the recording does not start and returned 503, we tried to run it locally on an Ubuntu meachine but the same result. 
We are using the latest Version of livekit service with Egrees and ingress from the docker run command in the docs.

Thank you.

**Comment by davidzhao** [comment]
Please do not duplicate issues across repos

**Comment by ParsaBordbar** [comment]
Hi again Found That the Server cores where not meeting the required minimum so Yeah it is fixed.
