### ISSUE TITLE
Questions Regarding Server Ports and WebRTC Connections

### ISSUE THREAD

**Issue by yuemenglong** [livekit/livekit#2915]
Hello LiveKit team,

Firstly, thank you for the amazing work on LiveKit. I have a couple of questions regarding the server ports used in WebRTC connections:

For each client connection via WebRTC, how many ports does the server need to open?
In scenarios where the server cannot expose many ports, is it possible to handle a large number of user connections with a limited number of ports, possibly even just one?
I appreciate your guidance and look forward to your response.

Best regards

**Comment by cnderrauber** [comment]
You can enable `udpmux` by set `rtc.udp_port` and comment the `port_range_start` and `port_range_end` in config file, the `rtc.udp_port` can be set to a single port or a limited port range
