### ISSUE TITLE
h264 pub issue

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/livekit#2938]
dear author,
    when i develop sip project , i found a strange issue about different cell phone.  when i use xiaomi brand cell phone to communicate with livekit , it worked good ,  but when i change the cellphone to sumsung brand to call into livekit , it cannot display the video。  please help me to get rid of it,  i can pay for your help.  by the way,  i captured two net package about them. thanks anyway.
[netpackage.zip](https://github.com/user-attachments/files/16632397/netpackage.zip)

**Comment by davidzhao** [comment]
Since video SIP isn't officially supported yet. I'm afraid we aren't unable to help here.
