### ISSUE TITLE
[Question] Why livekit-server require internet connection for local developing?

### ISSUE THREAD

**Issue by dkarpov-w** [livekit/livekit#2944]
Hey, I am new in livekit infra.

Currently I am doing my first steps.
I notice strange for me behavior. I can not work with livekit-server with out internet connection. 

_Step for reproduce_:

1.  install livekit  - `brew install livekit`
2. run `livekit-server --dev`
3. clone and run locally [meet example](https://github.com/livekit-examples/meet)
4. turn off internet 

_Logs_:
[livekit-server_logs.json](https://github.com/user-attachments/files/16665028/livekit-server_logs.json)
[client-logs.json](https://github.com/user-attachments/files/16665095/client-logs.json)

_Versions_:
livekit-server version 1.7.0
meet example from  commit bcd855178204864fba47c727ee6e246a19147e06 Jul 20 11:57:07 2024

**Comment by cnderrauber** [comment]
the server doesn't receive any client candidates in the log, livekit-server doesn't require internet connection but the browser needs to connect to the stun server to gather candidates.

**Comment by MatriQ** [comment]
> the server doesn't receive any client candidates in the log, livekit-server doesn't require internet connection but the browser needs to connect to the stun server to gather candidates.

Can we customize the STUN server address to fully run LiveKit locally?

**Comment by Kesha005** [comment]
> > the server doesn't receive any client candidates in the log, livekit-server doesn't require internet connection but the browser needs to connect to the stun server to gather candidates.
> 
> Can we customize the STUN server address to fully run LiveKit locally?


You can use livekit's own turn server or other for example coturn. And you don't need internet connection
