### ISSUE TITLE
How can the GoSDK be used as a participant to obtain the audio streams?

### ISSUE THREAD

**Issue by keaipeng123** [livekit/livekit#2948]
Hello, I would like to ask how I can create a participant through the GoSDK and use this participant to subscribe to all the audio streams in a room, in order to obtain the PCM data of each audio stream. Do you have any relevant SDKs available?

**Comment by cnderrauber** [comment]
refer to [file saver example](https://github.com/livekit/server-sdk-go/blob/main/examples/filesaver/main.go), the go sdk don't  provide decoder to get PCM data, you need to receive opus encoding data and decode it yourself.
