### ISSUE TITLE
video h264 interrupted

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/livekit#2953]
dear author ,
     when put video  rtp stream into livekit room , sometimes the video got interrupted , the rtp transport at then same machine,  the webrtc api like below :

    videoRTCPFeedback := []webrtc.RTCPFeedback{{"ccm", "fir"}, {"ccm", "tmmbr"}, {"nack", ""}, {"nack", "pli"}}
	videoTrack, err := webrtc.NewTrackLocalStaticRTP(webrtc.RTPCodecCapability{
		MimeType:     webrtc.MimeTypeH264,
		ClockRate:    90000,
		SDPFmtpLine:  "level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f",
		RTCPFeedback: videoRTCPFeedback,
	}, "video", "pion2")

  could u give me some advice ,thank you !

**Comment by boks1971** [comment]
Please provide more details. Does it work initially and then stops? Does it resume some time later?

Which client are you using?

**Comment by davidzhao** [comment]
closing due to lack of response/details
