### ISSUE TITLE
could not parse "tcp://10.43.34.158:7881" as uint value from environment variable "LIVEKIT_PORT" for flag port: strconv.ParseUint: parsing "tcp://10.43.34.158:7881": invalid syntax

### ISSUE THREAD

**Issue by coyzeng** [livekit/livekit#2961]
**Describe the bug**
could not parse "tcp://10.43.34.158:7881" as uint value from environment variable "LIVEKIT_PORT" for flag port: strconv.ParseUint: parsing "tcp://10.43.34.158:7881": invalid syntax.

**Server**
- Version: [1.7.2]
- Environment: [e.g. local dev, EKS]
- any other information about your deployment setup

Actually LIVEKIT_PORT environment value not exist, what happened.

**Comment by davidzhao** [comment]
please provide additional information requested.

**Comment by cnderrauber** [comment]
it looks like a config error that the port should be an integer number, please provide the config you are using
