### ISSUE TITLE
pub error

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/livekit#2973]
dear author, 
    i found an error when i publish video into livekit room, below are my invoke function:
        videoRTCPFeedback := []webrtc.RTCPFeedback{{"ccm", "fir"}, {"ccm", "tmmbr"}, {"nack", ""}, {"nack", "pli"}}
	videoTrack, err := webrtc.NewTrackLocalStaticRTP(webrtc.RTPCodecCapability{
		MimeType:     webrtc.MimeTypeH264,
		ClockRate:    90000,
		SDPFmtpLine:  "level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f",
		RTCPFeedback: videoRTCPFeedback,
	}, "video", "pion2")

   and the livekit log as below:

   ERROR	livekit	supervisor/participant_supervisor.go:156	supervisor error on publication	{"room": "62316388", "roomID": "RM_jme3z4WDbQKp", "participant": "sip_19373086225", "pID": "PA_LUb4DHbZ3VtW", "remote": false, "trackID": "TR_AM2hbgHd8dvSzp", "error": "publish time out"}

 plus , the sip server and the livekit server at the same host, and the pcap attached is nothing wrong
 could u give me some advice to handle the issue, thanks very much!!! wait for your message .
[kadun.zip](https://github.com/user-attachments/files/16847489/kadun.zip)

**Comment by davidzhao** [comment]
track is not correctly published due to the server did not receive video packets. since you are trying something custom here, it's out of scope for this project.
