### ISSUE TITLE
LiveKit Server communicating with EC2 instance

### ISSUE THREAD

**Issue by DanielBerrioB** [livekit/livekit#2974]
Hi community!

I'm using the livekit server and when inspecting the network traffic I found that it was communicating with an instance of an EC2, does anyone know why that happens? I'm just using the dev server with the API key/secret pair suggested in the docs.

**Server**
![image](https://github.com/user-attachments/assets/3d1a3d12-6831-445f-98b0-3850fab1a4ce).

Thank you very much in advance!

**Comment by davidzhao** [comment]
by default livekit points to Twilio and Google's public STUN servers. I believe Twilio is hosted on AWS
