### ISSUE TITLE
How does livekit monitor the latency and bandwidth of push and pull streams?

### ISSUE THREAD

**Issue by RedCrazyGhost** [livekit/livekit#2976]
I noticed in the code that RTPStats includes relevant parameter, but this parameter is only used in AnalyticsEvent.  Additionally, in the output of livekit-server, I saw windowStat, which seems to contain related parameters.  Although Prometheus is used in the code, I prefer to avoid importing external services and instead seek a simpler way to handle this.

Looking forward to your response.
@davidzhao

**Comment by RedCrazyGhost** [comment]
I found during runtime that the `rtcp.Packet` used in `ReaderTrackWithRTCPHandler` can be asserted to be of type `*rtcp.ReceiverReport` to obtain the data I need.Hope doing this is feasible.

**Comment by davidzhao** [comment]
this is a question about the internals and outside of the scope of what we are able to support. closing the issue and hoping you've figured it out.
