### ISSUE TITLE
Is Custom Function Execution Available for LiveKit AI Agent via POST Request?

### ISSUE THREAD

**Issue by shwetd19** [livekit/livekit#2997]
#### **Summary**
We're inquiring about the capability to run custom functions on the LiveKit AI agent, such as capturing emails or booking appointments, using a POST request during a call. Is this feature currently available or planned for future implementation?

---

#### **Description**
We're interested in understanding if the LiveKit AI agent currently supports or has plans to support the execution of custom functions during a call. This capability would enable more dynamic and interactive experiences, like capturing user information or performing specific actions based on the conversation.

---

#### **Specific Inquiries**
- Is there a way for the existing agent to run an endpoint that accepts POST requests with custom function details?
- If available, how does the current implementation execute these custom functions within the AI agent's context?
- What security measures are in place for such functionality?

---

#### **Use Cases We're Interested In**
- Capturing email addresses from users
- Booking appointments based on conversation context
- Updating user preferences in real-time
- Triggering external actions (e.g., sending confirmation emails, updating databases)

---

#### **Technical Considerations**
If this feature is available or planned:
- What is the performance impact on call latency?
- How extensible is the system for various types of custom functions?

---

#### **Additional Information Request**
If this feature exists:
- Is there documentation available for usage instructions?
- Are there any example custom functions (e.g., email capture, appointment booking) provided?
- What error handling and logging mechanisms are in place?

---

#### **Closing Notes**
Understanding the availability and implementation details of this feature would greatly assist us in planning our integration with the LiveKit AI agent. If this functionality is not currently available, we would be interested in discussing the possibility of its future implementation.

**Comment by davidzhao** [comment]
What you are asking can be accomplished by function calling. There is full support for this in the Agents framework. Please reference the example here: https://github.com/livekit/agents/blob/main/examples/voice-assistant/function_calling_weather.py

**Comment by shwetd19** [comment]
Thank you for the information  @davidzhao  

I see that function calling is supported in the Agents framework. I'll review the example provided [here](https://github.com/livekit/agents/blob/main/examples/voice-assistant/function_calling_weather.py) to better understand how to implement custom functions such as capturing emails or booking appointments.

If possible, could you provide additional details on the following aspects?
1. **Integration Details**: Are there specific steps or configurations needed to integrate custom functions with the LiveKit AI agent using the provided framework?
2. **Security Measures**: What security measures are in place for executing custom functions to ensure data integrity and privacy?
3. **Performance Impact**: What is the performance impact on call latency when executing custom functions? Are there best practices to minimize latency?

Thank you again for your assistance!

**Comment by xuanyanwow** [comment]
The example url is changed , new one is : https://github.com/livekit/agents/blob/main/examples/voice-pipeline-agent/function_calling_weather.py
