### ISSUE TITLE
Error in an example

### ISSUE THREAD

**Issue by woozar** [livekit/livekit#3000]
On the page https://docs.livekit.io/reference/components/react/concepts/loops/ there is an example:

```
<ParticipantLoop participants={participants}>
  // ParticipantName is a LiveKit component that uses the ParticipantContext
  // to render the name of a participant.
  <ParticipantName />
<ParticipantLoop />
```

The last tag is wrong as it is a self-closing tag not a closing tag for the opening tag in the beginning.
Also the comment is not a valid react comment
It should look like this
```
<ParticipantLoop participants={participants}>
  {/* ParticipantName is a LiveKit component that uses the ParticipantContext
  to render the name of a participant. */}
  <ParticipantName />
</ParticipantLoop>
```

**Comment by paulwe** [comment]
thanks for catching this!
