### ISSUE TITLE
Draining Mode

### ISSUE THREAD

**Issue by leejiliang** [livekit/livekit#3021]
I hava a two nodes livekit cluster, I want these two nodes to take turns entering draining mode to achieve hot updates.
LiveKit Docs

Home -> Self Hosting -> Distributed Setup -> Downscaling-and-draining

Please tell me how to put a node into draining mode?
I have checked the relevant documentation and did not find the relevant API.

**Comment by davidzhao** [comment]
it's automatic. SIGTERM would start draining them
