### ISSUE TITLE
Is it possible to implement "end-to-end-encryption" with own algoritms?

### ISSUE THREAD

**Issue by shalom-aviv** [livekit/livekit#303]
Hi 

Is it possible to add "end-to-end-encryption"?
https://webrtchacks.com/true-end-to-end-encryption-with-webrtc-insertable-streams/

Does server support plugins to extend functionality?

**Comment by davidzhao** [comment]
Currently Insertable Streams is only supported on Chromium-based browsers. [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1631263) and Safari do not support it yet.

We do plan to support e2ee within LiveKit. Stay tuned.

**Comment by initpwn** [comment]
@davidzhao Hi,

Chrome, Firefox & Safari now supports Encoded-streams. :)
Any ETA or updates on E2EE support for LiveKit? 

Thanks

**Comment by davidzhao** [comment]
it's on our roadmap!

**Comment by aehlke** [comment]
Is there a link to this on the roadmap visible anywhere? Thanks

**Comment by ranthwar-vcloudx** [comment]
@davidzhao Is there Link to view RoadMap?? Thanks in advance

**Comment by davidzhao** [comment]
Tracking E2EE in #1035, closing this issue in favor of that
