### ISSUE TITLE
Question: Support KMP and Compose Multiplatform for Client SDK?

### ISSUE THREAD

**Issue by tamimattafi** [livekit/livekit#3030]
Hello! 
Thank you for this amazing project!

Are there any plans on supporting KMP and Compose Multiplatform for the client SDK? 
I believe your android library is already clean enough to make a smooth transition, at least for android, desktop and iOS targets.

There is already a [WebRTC library](https://github.com/shepeliev/webrtc-kmp) for KMP (Currently supports Android, iOS and JS), which works really well, I'm wondering if there's a way to integrate with your project which seems very promising in terms of performance and stability.

**Comment by davidzhao** [comment]
Hi there, thank you for the kind words!

KMP is not currently on the roadmap. we already support a wide range of SDKs for native platforms as well as cross-platform libraries such as Flutter, React Native, and Unity.

**Comment by tamimattafi** [comment]
Thank you for the quick answer, @davidzhao!
I hope in the future KMP will become one of your cross-platform targets since it's quickly gaining popularity.

**Comment by davidzhao** [comment]
We'll definitely keep an eye on it! Appreciate you bringing it to our attention.

**Comment by paderick** [comment]
Hi @davidzhao! All of us in the community see benevolent the range of SDKs you provide.

At [Google IO 2025 Google mentioned Kotlin Multiplatform](https://android-developers.googleblog.com/2025/05/android-kotlin-multiplatform-google-io-kotlinconf-2025.html) and already support with their own libraries (like datastore, room, etc.) KMP.

Please give us a short update about the roadmap and the idea to offer also an SDK for KMP (or better: CMP).

**Comment by tamimattafi** [comment]
@paderick I agree!
Since the creation of this issue, a lot has changed. CMP for iOS has made it to production (stable), wasm is becoming beta, and a lot of other libraries from Google, jetbrains, and other large and small communities already support KMP. 
This will be a great addition to LiveKit and Kotlin Multiplatform, in my opinion.

**Comment by zoujiaqing** [comment]
I created a KMP project for livekit:
https://github.com/zoujiaqing/livekit-kmp

**Comment by alexander-potemkin** [comment]
> I created a KMP project for livekit: https://github.com/zoujiaqing/livekit-kmp

@davidzhao , any chance this could be merged into the official SDK?

**Comment by zoujiaqing** [comment]
I think:
need have a new repo for livekit-kmp
