### ISSUE TITLE
When the number of rooms reaches a certain amount, about 700, all rooms will be closed, but the service status is good.

### ISSUE THREAD

**Issue by leejiliang** [livekit/livekit#3037]
**Describe the bug**
There are three participants and one agent in each room. When the number of rooms increases to a certain level, around 700, all rooms will suddenly be forcibly closed. I monitored the server through Prometheus, and every indicator was very low, including CPU, memory, disk, and network overhead. I have checked the server-side logs, which are all network timeout logs, and did not find any obvious prompt logs related to closing the room.

CPU: 12
MEM: 64GB
bandwidth： 200M

**Server**
- Version: [1.6.1]
- Environment: ubuntu
- any other information about your deployment setup

**Client**
- SDK: [e.g. js, ios]
- Version: [0.x.x]

**To Reproduce**
1. two clients are connected to room
2. 3rd client joins
3. 3rd client does '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by davidzhao** [comment]
Can you please try to reproduce on 1.7.2? we are unable to troubleshoot any older versions.

are you able to reproduce? If so can you indicate the specific steps to do so? what is in the server logs when this happens?

please provide all details requested by the issue template in order for us to investigate. the ticket will be closed if details are missing.

**Comment by leejiliang** [comment]
I'll try upgrading the version to 1.7.2 first

**Comment by leejiliang** [comment]
I changed the redis server to the node where the livekit server host is located. Everything is fine now. 
I do these because of I found some error log about redis ,like #2539

**Comment by leejiliang** [comment]
> Can you please try to reproduce on 1.7.2? we are unable to troubleshoot any older versions.
> 
> are you able to reproduce? If so can you indicate the specific steps to do so? what is in the server logs when this happens?
> 
> please provide all details requested by the issue template in order for us to investigate. the ticket will be closed if details are missing.

I can't reproduce it anymore , Thank you so much .
