### ISSUE TITLE
如何让ai语音助手拥有function calling功能

### ISSUE THREAD

**Issue by chen0321-max** [livekit/livekit#3046]
assistant = VoiceAssistant(
        vad=silero.VAD.load(),
        stt=deepgram.STT(),
        llm=openai.LLM(),
        tts=openai.TTS(),
        chat_ctx=initial_ctx,
    )
    我希望在与这个ai语音助手实时语音聊天的过程中，当我说出某些固定的话，比如说“agent”，它可以自动调用一个函数，你能帮帮我吗

**Comment by xuanyanwow** [comment]
我认为自行实现LLM驱动可能可以实现你的需求

**Comment by chen0321-max** [comment]
感谢，已经实现了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月26日(周二) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [livekit/livekit] 如何让ai语音助手拥有function calling功能 (Issue #3046)




 
我认为自行实现LLM驱动可能可以实现你的需求

**Comment by xuanyanwow** [comment]
~ O(∩_∩)O哈哈~   可以分享分享代码吗，学习一下
