### ISSUE TITLE
cant connect to my self hosted livekit server

### ISSUE THREAD

**Issue by arkodeep3404** [livekit/livekit#3076]
i have self hosted livekit server on a vm from azure but I cannot connect to it from my python agent 

please help

<img width="947" alt="Screenshot 2024-10-09 at 1 02 11 PM" src="https://github.com/user-attachments/assets/11750410-54aa-4174-b22b-c14c57e50bba">

**Comment by arkodeep3404** [comment]
i get this at the end 

```Get "https://api.github.com/repos/livekit/livekit-server/releases/latest": dial tcp: lookup api.github.com on 168.63.129.16:53: read udp 172.17.0.2:33938->168.63.129.16:53: read: no route to host

after running this 

```docker pull livekit/generate
docker run --rm -it -v$PWD:/output livekit/generate

**Comment by cnderrauber** [comment]
do you have the server side log? 401 means an unauthorized request, the token is incorrect.

**Comment by arkodeep3404** [comment]
i think i gave the correct token only 
how to get the logs??

**Comment by arkodeep3404** [comment]
will these help???


livekit-docker.service - LiveKit Server Container
     Loaded: loaded (/etc/systemd/system/livekit-docker.service; enabled; prese>
     Active: active (running) since Wed 2024-10-09 15:04:29 UTC; 2min 48s ago
    Process: 4060 ExecStartPre=/usr/local/bin/docker-compose -f docker-compose.>
   Main PID: 4069 (docker-compose)
      Tasks: 10 (limit: 9456)
     Memory: 16.5M (peak: 17.0M)
        CPU: 98ms
     CGroup: /system.slice/livekit-docker.service
             └─4069 /usr/local/bin/docker-compose -f docker-compose.yaml up

Oct 09 15:04:47 composio docker-compose[4069]: livekit-caddy-1    | {"level":"i>
Oct 09 15:06:01 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:01 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:02 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:02 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:05 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:05 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:08 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:08 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:10 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
lines 1-21/21 (END)...skipping...
● livekit-docker.service - LiveKit Server Container
     Loaded: loaded (/etc/systemd/system/livekit-docker.service; enabled; prese>
     Active: active (running) since Wed 2024-10-09 15:04:29 UTC; 2min 48s ago
    Process: 4060 ExecStartPre=/usr/local/bin/docker-compose -f docker-compose.>
   Main PID: 4069 (docker-compose)
      Tasks: 10 (limit: 9456)
     Memory: 16.5M (peak: 17.0M)
        CPU: 98ms
     CGroup: /system.slice/livekit-docker.service
             └─4069 /usr/local/bin/docker-compose -f docker-compose.yaml up

Oct 09 15:04:47 composio docker-compose[4069]: livekit-caddy-1    | {"level":"i>
Oct 09 15:06:01 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:01 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:02 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:02 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:05 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:05 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:08 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:08 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
Oct 09 15:06:10 composio docker-compose[4069]: livekit-caddy-1    | {"level":"e>
~
~
~
~
lines 1-21/21 (END)...skipping...
● livekit-docker.service - LiveKit Server Container
     Loaded: loaded (/etc/systemd/system/livekit-docker.service; enabled; preset: enabled)
     Active: active (running) since Wed 2024-10-09 15:04:29 UTC; 2min 48s ago
    Process: 4060 ExecStartPre=/usr/local/bin/docker-compose -f docker-compose.yaml down (code=exited, status=0/SUCCESS)
   Main PID: 4069 (docker-compose)
      Tasks: 10 (limit: 9456)
     Memory: 16.5M (peak: 17.0M)
        CPU: 98ms
     CGroup: /system.slice/livekit-docker.service
             └─4069 /usr/local/bin/docker-compose -f docker-compose.yaml up

Oct 09 15:04:47 composio docker-compose[4069]: livekit-caddy-1    | {"level":"info","ts":1728486287.686467,"logger":"tls.obtain","msg":"releasing lock","identifier":"lk-whip.orom.club"}
Oct 09 15:06:01 composio docker-compose[4069]: livekit-caddy-1    | {"level":"error","ts":1728486361.654524,"logger":"layer4","msg":"matching connection","remote":"104.164.173.109:57720","error":"EOF"}
Oct 09 15:06:01 composio docker-compose[4069]: livekit-caddy-1    | {"level":"error","ts":1728486361.6585264,"logger":"layer4","msg":"matching connection","remote":"104.164.173.149:17776","error":"EOF"}
Oct 09 15:06:02 composio docker-compose[4069]: livekit-caddy-1    | {"level":"error","ts":1728486362.9073205,"logger":"layer4","msg":"matching connection","remote":"104.164.173.38:57756","error":"EOF"}
Oct 09 15:06:02 composio docker-compose[4069]: livekit-caddy-1    | {"level":"error","ts":1728486362.9275699,"logger":"layer4","msg":"matching connection","remote":"104.164.173.239:52952","error":"EOF"}
Oct 09 15:06:05 composio docker-compose[4069]: livekit-caddy-1    | {"level":"error","ts":1728486365.5732822,"logger":"layer4","msg":"matching connection","remote":"104.164.173.180:43108","error":"EOF"}
Oct 09 15:06:05 composio docker-compose[4069]: livekit-caddy-1    | {"level":"error","ts":1728486365.577294,"logger":"layer4","msg":"matching connection","remote":"104.164.173.226:16030","error":"EOF"}
Oct 09 15:06:08 composio docker-compose[4069]: livekit-caddy-1    | {"level":"error","ts":1728486368.3850677,"logger":"layer4","msg":"matching connection","remote":"104.164.173.51:46426","error":"EOF"}
Oct 09 15:06:08 composio docker-compose[4069]: livekit-caddy-1    | {"level":"error","ts":1728486368.9394376,"logger":"layer4","msg":"matching connection","remote":"104.164.173.38:57764","error":"EOF"}
Oct 09 15:06:10 composio docker-compose[4069]: livekit-caddy-1    | {"level":"error","ts":1728486370.0391176,"logger":"layer4","msg":"matching connection","remote":"104.164.173.31:33652","error":"EOF"}
~

**Comment by cnderrauber** [comment]
it is not the sfu logs, you can try https://livekit.io/connection-test to test your deployment

**Comment by arkodeep3404** [comment]
hey it seems to be working alright now
thanks for your help
