### ISSUE TITLE
A panic error occurred causing the service to crash

### ISSUE THREAD

**Issue by zhanghan1995** [livekit/livekit#3115]
livekit version: v1.6.2
environment:  local  docker

error info:
livekit-livekit-1  | panic: runtime error: invalid memory address or nil pointer dereference
livekit-livekit-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xabef64]
livekit-livekit-1  |
livekit-livekit-1  | goroutine 24545750930 [running]:
livekit-livekit-1  | github.com/pion/dtls/v2.(*alertError).IsFatalOrCloseNotify(...)
livekit-livekit-1  |    /go/pkg/mod/github.com/pion/dtls/v2@v2.2.10/errors.go:116
livekit-livekit-1  | github.com/pion/dtls/v2.(*Conn).handshake.func3()
livekit-livekit-1  |    /go/pkg/mod/github.com/pion/dtls/v2@v2.2.10/conn.go:871 +0x164
livekit-livekit-1  | created by github.com/pion/dtls/v2.(*Conn).handshake in goroutine 24545742378
livekit-livekit-1  |    /go/pkg/mod/github.com/pion/dtls/v2@v2.2.10/conn.go:857 +0x3b1

**Comment by cnderrauber** [comment]
it looks like a pion/dtls issue, can you update livekit to 1.7.2 and retry? it uses dtls v2.2.12
