### ISSUE TITLE
High concurrent connections to rooms cause service unavailability

### ISSUE THREAD

**Issue by zhanghan1995** [livekit/livekit#3116]
**Describe the bug**

When many rooms exist (for example, 1000 rooms), using the server-sdk-go loop to connect each room will cause all rooms to fail to connect, and repeated reconnections will make the service unavailable.

Other SDKS can also cause the same problems as above when connecting a large number of rooms concurrently

**Server**
- Version: [1.6.2]
- Environment: docker
- Specs: 16C32G200MB

**Client**
- SDK: [go]
- Version: [v2.1.2]

**Comment by davidzhao** [comment]
this shouldn't be a problem, we've done extensive load testing with the service. please ensure you've increased the number of file handles on the machine of the server as well as the load tester. Docs here: https://github.com/livekit/livekit-cli?tab=readme-ov-file#configuring-system-settings
