### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'values')

### ISSUE THREAD

**Issue by fasilminale** [livekit/livekit#3130]
**Describe the bug**
I'm encountering an issue where room.participant is undefined when attempting to join a room in my existing project running on Node.js version 16. The same setup works flawlessly on a different project running on Node.js version 18 with Next.js. The error occurs during the join process, and room.participant remains undefined, leading to the following runtime error:

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'values')

Call Stack
getTrackReferences
node_modules/@livekit/components-core/dist/index.mjs (1588:0)
trackReferencesObservable
node_modules/@livekit/components-core/dist/index.mjs (1632:14)
eval
node_modules/@livekit/components-react/dist/index.mjs (1548:50)
commitHookEffectListMount
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (20004:0)
...

**Server**
- Version: 1.8
- Environment: Production (running on ubuntu)

**Client**
- SDK: js
- Version: 2.5.9
 "livekit-client": "^2.5.9",
"@livekit/components-react": "^1.5.3",
"@livekit/components-styles": "^1.0.9",

**To Reproduce**
 - a client tries to join, but the room.participant is undefined.
**Expected behavior**
a should successfully join the room and room.participant should not be undefined.

![Screen Shot 2024-10-23 at 8 39 43 AM](https://github.com/user-attachments/assets/ffbeb03f-58af-40cb-8998-cccbf942a9f4)

**Comment by fasilminale** [comment]
the error occurred when i add <VideoConference/>

**Comment by fasilminale** [comment]
the error occurred when i add `<VideoConference/>`

**Comment by davidzhao** [comment]
you are using incompatible versions of livekit-client and @livekit/components-js (1.x vs 2.x)

**Comment by sameerdas1** [comment]
@davidzhao running into a similar issue here with `Uncaught TypeError: Cannot read properties of undefined (reading 'length')`

And I have all the latest versions installed. 
├─┬ @livekit/components-react@2.9.4
│ ├─┬ @livekit/components-core@0.12.5
│ │ └── livekit-client@2.12.0 deduped
│ └── livekit-client@2.12.0 deduped
├── @livekit/components-styles@1.1.5
└── livekit-client@2.12.0

Am I missing something here?
