### ISSUE TITLE
h264 refresh issue

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/livekit#3132]
dear author,
   I found when i join the livekit meeting room use android cell phone,  and publish h264 stream via webrtc track writertp function , the video screen was blank. but if i shake the phone or switch the camera then the video screen was  displayed immediately .  
   so i tried to invoke the replaceTrack  function at the first  ,and it doesn't work,  could you give me some advice?

**Comment by davidzhao** [comment]
your publisher is not generating keyframes when clients are requesting them, and without keyframes, clients cannot render anything
