### ISSUE TITLE
trackSubscribed cannot be trigger：TrackSubscribed cannot listen to already published tracks after connecting

### ISSUE THREAD

**Issue by wxl17839938583** [livekit/livekit#3143]
Hello, my current usage scenario is when a user joins a room and the room displays real-time messages, which are the messages received by handleData Received. There is a video button that can be selectively subscribed to, and clicking it will subscribe to the video track, which is trackSubscribed and displayed. The problem now is that if I place the trackSubscribed track before Connect to listen, I can receive the video, but after Connect, I cannot trigger the tracksubscribed hook.

**Comment by davidzhao** [comment]
you always need to register listeners before connect. please refer to the right docs for the platform you are building for.

**Comment by wxl17839938583** [comment]
Okay,thanks
