### ISSUE TITLE
Long connection time to room (about 1s)

### ISSUE THREAD

**Issue by lklimkiewicz-tp** [livekit/livekit#3144]
I'm having an issue where connecting to the LiveKit room takes a long time, around one second. This happens both when connecting from the Python backend and the JavaScript frontend. Is this the expected behavior? How can I mitigate it?

---

### My setup 

**docker-compose.yml**
```dockerfile
services:
  livekit-server:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit/config.yaml
    volumes:
      - ./config.yaml:/etc/livekit/config.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50100:50000-50100/udp"
```

**config.yaml**
```yaml
port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
keys:
  ...
```

**Python connection code**
```python
async def connect(self, room_name, identity):
    token = (
        api.AccessToken(LIVEKIT_API_KEY, LIVEKIT_API_SECRET)
        .with_identity(identity)
        .with_name(identity)
        .with_grants(api.VideoGrants(room_join=True, room=room_name))
        .to_jwt()
    )
    room = rtc.Room()
    await room.connect(LIVEKIT_URL, token)
    self.room = room
    return room
```

**Comment by davidzhao** [comment]
make sure your ports are all open correctly. you can use the [connection tester](https://livekit.io/connection-test) to validate the connectivity.

this is a setup/networking issue on your end, closing issue
