### ISSUE TITLE
GPU support for encoding

### ISSUE THREAD

**Issue by George-Gi** [livekit/livekit#3208]
I would like to utilize my GPU for encoding a stream.
My understanding is that Livekit uses ffmpeg under the hood.
I have all the required drivers to use ffmpeg with my Intel GPU, however I can't find information if livekit exposes the configuration of how ffmpeg will be called (with what arguments).
Is there a way to configure how ffmpeg is called?

**Comment by cnderrauber** [comment]
The livekit sfu just forwards encoded media packets, there is no decoding/encoding process on the server side.
