### ISSUE TITLE
could not connect: could not establish pc connection 

### ISSUE THREAD

**Issue by zoujiaqing** [livekit/livekit#3219]
I used livekit-sdk-js example to connect my livekit-server.

example log:

```

prewarmed connection in 69ms 
signal connection established in 206ms 
tracks published in 1631ms 
could not connect: could not establish pc connection 

```

livekit-server log:

{"level":"info","ts":1732883553.5135393,"logger":"livekit","caller":"redis/redis.go:142","msg":"connecting to redis","simple":true,"addr":"172.17.0.1:6379"}
{"level":"info","ts":1732883553.5815828,"logger":"livekit","caller":"service/turn.go:145","msg":"Starting TURN server","turn.relay_range_start":30000,"turn.relay_range_end":40000,"turn.portTLS":5349,"turn.externalTLS":false,"turn.portUDP":3478}
{"level":"info","ts":1732883553.5829022,"logger":"livekit","caller":"service/server.go:258","msg":"starting LiveKit server","portHttp":7880,"nodeID":"ND_5x5wMW9xe6T7","nodeIP":"172.19.57.11","version":"1.8.0","bindAddresses":["0.0.0.0"],"rtc.portTCP":7881,"rtc.portUDP":{"Start":7882,"End":0}}

{"level":"info","ts":1732884281.1688092,"logger":"livekit","caller":"service/roomallocator.go:164","msg":"selected node for room","room":"room001","selectedNodeID":"ND_5x5wMW9xe6T7"}
{"level":"info","ts":1732884281.171236,"logger":"livekit","caller":"service/roommanager.go:404","msg":"starting RTC session","room":"room001","roomID":"RM_qg5aBa5i4vXY","participant":"user003","pID":"PA_PBixZpGrGEZS","remote":false,"room":"room001","nodeID":"ND_5x5wMW9xe6T7","clientInfo":{"sdk":"JS","version":"2.7.0","protocol":15,"os":"Mac OS X","osVersion":"10.15.7","deviceModel":"Mac","browser":"Edge","browserVersion":"130.0.0","address":"211.90.236.179"},"reconnect":false,"reconnectReason":"RR_UNKNOWN","adaptiveStream":true,"numParticipants":0,"kind":"STANDARD"}
{"level":"info","ts":1732884281.1724594,"logger":"livekit","caller":"service/roommanager.go:938","msg":"created TURN password","username":"TpVRHJ3RwpFeSTIoeVQQxXeKbN4gLM","password":"7QxNnCowStWN4p9PyRU2WeAmiTEtTPxlwrDgdyazghK"}
{"level":"info","ts":1732884296.2373123,"logger":"livekit","caller":"rtc/participant.go:956","msg":"participant closing","room":"room001","roomID":"RM_qg5aBa5i4vXY","participant":"user003","pID":"PA_PBixZpGrGEZS","remote":false,"sendLeave":false,"reason":"SIGNAL_SOURCE_CLOSE","isExpectedToResume":false}
{"level":"info","ts":1732884296.2377548,"logger":"livekit","caller":"rtc/room.go:698","msg":"removing participant without connection","room":"room001","roomID":"RM_qg5aBa5i4vXY","participant":"user003","pID":"PA_PBixZpGrGEZS","remote":false,"publisherCandidates":["[local][trickle] udp4 host 172.19.57.11:7882","[local][trickle] udp4 host 172.17.0.1:7882","[local][trickle] tcp4 host 172.19.57.11:7881","[local][trickle] tcp4 host 172.17.0.1:7881","[local][trickle] udp4 srflx 139.224.9.21:59685 related 0.0.0.0:59685","[local][trickle] udp4 srflx 139.224.9.21:56373 related 0.0.0.0:56373","[local][trickle] udp4 srflx 139.224.9.21:48107 related 0.0.0.0:48107"],"subscriberCandidates":["[local][trickle] udp4 host 172.19.57.11:7882","[local][trickle] udp4 host 172.17.0.1:7882","[local][trickle] tcp4 host 172.19.57.11:7881","[local][trickle] tcp4 host 172.17.0.1:7881","[local][trickle] udp4 srflx 139.224.9.21:35457 related 0.0.0.0:35457","[local][trickle] udp4 srflx 139.224.9.21:51277 related 0.0.0.0:51277","[local][trickle] udp4 srflx 139.224.9.21:48415 related 0.0.0.0:48415"],"connectionType":"unknown","reason":"NONE"}
{"level":"info","ts":1732884297.583718,"logger":"livekit.room","caller":"rtc/room.go:911","msg":"closing room","room":"room001","roomID":"RM_qg5aBa5i4vXY"}
{"level":"info","ts":1732884297.5839431,"logger":"livekit","caller":"service/roommanager.go:168","msg":"deleting room state","room":"room001"}
{"level":"info","ts":1732884297.5845253,"logger":"livekit.room","caller":"service/roommanager.go:626","msg":"room closed","room":"room001","roomID":"RM_qg5aBa5i4vXY"}

**Comment by VitoTyutikov** [comment]
I have the same problem. Did you find the solution?

**Comment by VitoTyutikov** [comment]
> I have the same problem. Did you find the solution?

I find my solution. I tried run livekit on WSL2. When i tried run livekit on windows instead WSL2 it works fine.

**Comment by boks1971** [comment]
Do you have connectivity to the server from outside world? The server side addresses in the log are private IPs.

**Comment by davidzhao** [comment]
closing due to lack of response/information
