### ISSUE TITLE
Can't connect to Fireworks.ai for LLM inference. Streaming error.

### ISSUE THREAD

**Issue by BrightLyf** [livekit/livekit#3230]
**Describe the bug**

**Server**
- Version: [0.x.x]
- Environment: [e.g. local dev, EKS]
- any other information about your deployment setup

**Client**
- SDK: [e.g. js, ios]
- Version: [0.x.x]

**To Reproduce**
1. two clients are connected to room
2. 3rd client joins
3. 3rd client does '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by boks1971** [comment]
Please provide more information about what the error is.

Also, please file an issue in https://github.com/livekit/agents once you have more details/logs of what the issue is
