### ISSUE TITLE
error on Chrome: could not establish pc connection

### ISSUE THREAD

**Issue by Emotibot5** [livekit/livekit#3236]
**Describe the bug**
see error in browser : "could not establish pc connection" 

**Server**
- Version:  0.12.1
- Environment: local dev

**Client**
- SDK: js

**To Reproduce**

use playground (https://github.com/livekit/agents-playground.git)
 
click the connect button. 

**Expected behavior**
start to chat in voice

**Screenshots**

![image](https://github.com/user-attachments/assets/a8e4041b-5963-4ffc-90f7-53585136cb38)
›

![image](https://github.com/user-attachments/assets/fd64f096-a468-4fbc-9df3-bd2e970edbbf)

the tcp port: 7881
udp port : 50000 - 60000 is open well

**Comment by boks1971** [comment]
How/where are you running the server? Can you please attach server logs?

**Comment by davidzhao** [comment]
closing due to lack of response/information
