### ISSUE TITLE
Livekit Integration with Telnyx

### ISSUE THREAD

**Issue by yanicechong** [livekit/livekit#3238]
Hi, I am currently working on integrating LiveKit with Telnyx, following the tutorials below:
- [Accepting Calls with LiveKit SIP](https://docs.livekit.io/sip/quickstarts/accepting-calls/)
- [Telnyx LiveKit Configuration Guide](https://developers.telnyx.com/docs/voice/sip-trunking/livekit-configuration-guide)
I encountered an issue while setting up the inbound trunk for accepting incoming calls. When dialing the purchased phone number, the system responds with: 'The phone number dialed cannot be reached at the moment.'

During testing, I noticed that the webhook URL attempts multiple retries before eventually failing with a SIP hangup cause code 408 (Request Timeout). How can I resolve this issue?

**Comment by davidzhao** [comment]
@yanicechong this is the repo for the core livekit server. It sounds like you have a configuration issue of some sort, versus reporting a bug.

Please join our Slack community and folks would be glad to help you there.
