### ISSUE TITLE
Live kit load testing

### ISSUE THREAD

**Issue by sridhard** [livekit/livekit#3285]
**Describe the bug**
We are benchmarking livekit performance, As per docs (https://docs.livekit.io/home/self-hosting/benchmark/) livekit support 1 publisher and 3000 subscriber in a 16 core machine on gcloud

We are using the same machine and the same command given in docs to do load test. But we are able to achieve only 1500 subscribers. We ae using a 720p video same as the one that is in the docs. Below command we used:

lk load-test \
  --url <YOUR-SERVER-URL> \
  --api-key <YOUR-KEY> \
  --api-secret <YOUR-SECRET> \
  --room load-test \
  --video-publishers 1 \
  --subscribers 3000 \

Can you pls tell use whether we need to do any tuning to achieve 3000 subscribers?

**Server**
- Version: Latest Docket images
- Environment: Docer + VM
- any other information about your deployment setup

**Client**
We are using load test tool

**To Reproduce**
Start livekit docker server and simulate load using below command
lk load-test \
  --url <YOUR-SERVER-URL> \
  --api-key <YOUR-KEY> \
  --api-secret <YOUR-SECRET> \
  --room load-test \
  --video-publishers 1 \
  --subscribers 3000 \

**Expected behavior**
We should be able to support 3000 subscribers on a  c2-standard-16 node

**Screenshots**
NA

**Additional context**
NA

**Comment by boks1971** [comment]
No special tuning should be needed. Quite possibly it is not as efficient as it used to be as we have added more features.

Can you please share result of your runs?

**Comment by davidzhao** [comment]
closing due to lack of response/details

**Comment by mahemouli-nu10** [comment]
Hi, how can we test for multi rooms for concurrent sessions of 3 participants, as iam trying to execute from lk binary but --num-rooms flags are not supported

**Comment by mahimairaja** [comment]
Hi @sridhard @mahemouli-nu10 did you guys test your self hosted server? if so what all did you test
