### ISSUE TITLE
How to get the speaker's volume in real time

### ISSUE THREAD

**Issue by boatt** [livekit/livekit#3289]
Expect to have a listener that can get the speaker's voice and then react on the Android UI

**Comment by davidzhao** [comment]
you'd need to use our Android SDK to analyze the audio track. for example, take a look at our Audio visualizer component: https://github.com/livekit/components-android/blob/main/livekit-compose-components/src/main/java/io/livekit/android/compose/ui/audio/AudioBarVisualizer.kt
