### ISSUE TITLE
Local audio recording

### ISSUE THREAD

**Issue by adarsh-technocrat** [livekit/livekit#577]
Hi everyone I have made a web app using livekit similar to https://zencastr.com/   but right now I am figuring out is it possible to record the individual voices of people in the room locally as https://zencastr.com/ do.

Thanks in advance :)

Cc : @davidzhao

**Comment by davidzhao** [comment]
individual track recording isn't possible today.. but it will be soon.

**Comment by dsa** [comment]
@adarsh-technocrat individual track recording is now available!

Blog post:
https://blog.livekit.io/livekit-universal-egress-launch/

Docs:
https://docs.livekit.io/guides/egress/

Repo:
https://github.com/livekit/egress
