### ISSUE TITLE
Recording support?

### ISSUE THREAD

**Issue by postacik** [livekit/livekit#59]
The server looks very promising since it's supported with mobile and web SDKs.

However I could not see any section about recording in the documentation. Do you plan to add support for recording + processing recordings?

**Comment by davidzhao** [comment]
LiveKit doesn't support recording yet. we are certainly looking at it though!

**Comment by rodrigo-brito** [comment]
A good way to implement this is:
- A external service that connects to the room as a viewer
- The service get each track and store it or merge the tracks and store a single stream.

**Comment by postacik** [comment]
You can check how Janus Webrtc Server does it. If you turn recording on in a room, the server saves video and audio streams of each participant as a raw recording file without any transcoding. Then it is your job to process and transcode those files in a single file.

**Comment by davidzhao** [comment]
we are working on this now, if folks are interested in beta testing this, please 👍 on this post. I'll add you to the repo.

**Comment by sibis** [comment]
@davidzhao interested in this and looking to contribute as well if anything required

**Comment by davidzhao** [comment]
hey all, we are ready for you to play with the recorder! Docs are here: https://docs.livekit.io/guides/recording/

Join us on [slack](https://join.slack.com/t/livekit-users/shared_invite/zt-rrdy5abr-5pZ1wW8pXEkiQxBzFiXPUg) and let us know what you think! would love to get your help in making this better.

**Comment by jibon57** [comment]
@davidzhao First of all thanks for excellent library. Do you have any plan/example to capture media using ffmpeg similar way `mediasoup` is doing? For my case I don't want to use screen recorder. Instated of that capture media & later process.

**Comment by davidzhao** [comment]
hey @jibon57, check out our [Go SDK](https://github.com/livekit/server-sdk-go) for this use case. It lets you sit in a room as a participant and save the tracks into whichever format that suits your needs.

**Comment by jibon57** [comment]
@davidzhao perfect! Thank you!

**Comment by mikhailbolshakov** [comment]
> @davidzhao perfect! Thank you!



> @davidzhao First of all thanks for excellent library. Do you have any plan/example to capture media using ffmpeg similar way `mediasoup` is doing? For my case I don't want to use screen recorder. Instated of that capture media & later process.

@jibon57 
I'm also interested in this. Could you pls share some code or ideas how it could be implemented using server api?

**Comment by jibon57** [comment]
@mikhailbolshakov I haven't implemented it yet. Just wanted to know the possible ways. Thanks @davidzhao

**Comment by jibon57** [comment]
@davidzhao I've tried another approach using `go sdk` (I never used go before :-D) following example: https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go

```
package main

import (
	"fmt"
	"strings"
	"time"

	lksdk "github.com/livekit/server-sdk-go"
	"github.com/pion/webrtc/v3"
	"github.com/pion/webrtc/v3/pkg/media"
	"github.com/pion/webrtc/v3/pkg/media/ivfwriter"
	"github.com/pion/webrtc/v3/pkg/media/oggwriter"
)

func saveToDisk(i media.Writer, track *webrtc.TrackRemote) {
	defer func() {
		if err := i.Close(); err != nil {
			panic(err)
		}
	}()

	for {
		rtpPacket, _, err := track.ReadRTP()
		if err != nil {
			panic(err)
		}
		if err := i.WriteRTP(rtpPacket); err != nil {
			panic(err)
		}
	}
}

func main() {
	host := "host"
	apiKey := "api-key"
	apiSecret := "api-secret"
	roomName := "myroom"
	identity := "botuser"
	room, err := lksdk.ConnectToRoom(host, lksdk.ConnectInfo{
		APIKey:              apiKey,
		APISecret:           apiSecret,
		RoomName:            roomName,
		ParticipantIdentity: identity,
	})
	if err != nil {
		panic(err)
	}

	room.Callback.OnTrackSubscribed = trackSubscribed

	time.Sleep(time.Second * 30) // testing
	room.Disconnect()
}

func trackSubscribed(track *webrtc.TrackRemote, publication lksdk.TrackPublication, rp *lksdk.RemoteParticipant) {

	codec := track.Codec()
	if strings.EqualFold(codec.MimeType, webrtc.MimeTypeOpus) {

		fileName := track.ID() + "_audio.ogg"
		fmt.Printf("Got Opus track, saving to disk as %s (48 kHz, 2 channels)", fileName)

		oggFile, err := oggwriter.New(fileName, 48000, 2)
		if err != nil {
			panic(err)
		}
		saveToDisk(oggFile, track)

	} else if strings.EqualFold(codec.MimeType, webrtc.MimeTypeVP8) {

		fileName := track.ID() + "_video.ivf"
		fmt.Printf("Got VP8 track, saving to disk as %s", fileName)

		ivfFile, err := ivfwriter.New(fileName)
		if err != nil {
			panic(err)
		}

		saveToDisk(ivfFile, track)
	}
}
```
It's working fine but video isn't good enough. Will be helpful if you have a look & give suggestions.

**Comment by Wallacy** [comment]
FWIW: I used the gstcefsrc ( https://github.com/centricular/gstcefsrc ) point  my own custom route instead of livekit recorder to gain some memory/cpu.

**Comment by lxShaDoWxl** [comment]
@Wallacy Hi! you run by cli or usage golang  wrapper gst?
it would be interesting to see an example using golang and gstcefsrc

**Comment by thusinh1969** [comment]
I can not get it working at all

1) Even with the basic example on guide, the video is not playable after recording
2) With standalone mode docker pose error on log and another is recorded although there are 2 persons chatting video in the same room using livekit-sdk-js example.

I filed an issue here: https://github.com/livekit/livekit-recorder/issues/34

Steve

**Comment by Wallacy** [comment]
> @Wallacy Hi! you run by cli or usage golang wrapper gst? it would be interesting to see an example using golang and gstcefsrc

I use the CLI; O build a docker image with everything that i need and just run.

**Comment by theleapofcode** [comment]
> @davidzhao I've tried another approach using `go sdk` (I never used go before :-D) following example: https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 	"strings"
> 	"time"
> 
> 	lksdk "github.com/livekit/server-sdk-go"
> 	"github.com/pion/webrtc/v3"
> 	"github.com/pion/webrtc/v3/pkg/media"
> 	"github.com/pion/webrtc/v3/pkg/media/ivfwriter"
> 	"github.com/pion/webrtc/v3/pkg/media/oggwriter"
> )
> 
> func saveToDisk(i media.Writer, track *webrtc.TrackRemote) {
> 	defer func() {
> 		if err := i.Close(); err != nil {
> 			panic(err)
> 		}
> 	}()
> 
> 	for {
> 		rtpPacket, _, err := track.ReadRTP()
> 		if err != nil {
> 			panic(err)
> 		}
> 		if err := i.WriteRTP(rtpPacket); err != nil {
> 			panic(err)
> 		}
> 	}
> }
> 
> func main() {
> 	host := "host"
> 	apiKey := "api-key"
> 	apiSecret := "api-secret"
> 	roomName := "myroom"
> 	identity := "botuser"
> 	room, err := lksdk.ConnectToRoom(host, lksdk.ConnectInfo{
> 		APIKey:              apiKey,
> 		APISecret:           apiSecret,
> 		RoomName:            roomName,
> 		ParticipantIdentity: identity,
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	room.Callback.OnTrackSubscribed = trackSubscribed
> 
> 	time.Sleep(time.Second * 30) // testing
> 	room.Disconnect()
> }
> 
> func trackSubscribed(track *webrtc.TrackRemote, publication lksdk.TrackPublication, rp *lksdk.RemoteParticipant) {
> 
> 	codec := track.Codec()
> 	if strings.EqualFold(codec.MimeType, webrtc.MimeTypeOpus) {
> 
> 		fileName := track.ID() + "_audio.ogg"
> 		fmt.Printf("Got Opus track, saving to disk as %s (48 kHz, 2 channels)", fileName)
> 
> 		oggFile, err := oggwriter.New(fileName, 48000, 2)
> 		if err != nil {
> 			panic(err)
> 		}
> 		saveToDisk(oggFile, track)
> 
> 	} else if strings.EqualFold(codec.MimeType, webrtc.MimeTypeVP8) {
> 
> 		fileName := track.ID() + "_video.ivf"
> 		fmt.Printf("Got VP8 track, saving to disk as %s", fileName)
> 
> 		ivfFile, err := ivfwriter.New(fileName)
> 		if err != nil {
> 			panic(err)
> 		}
> 
> 		saveToDisk(ivfFile, track)
> 	}
> }
> ```
> 
> It's working fine but video isn't good enough. Will be helpful if you have a look & give suggestions. I think need to implement this part: https://github.com/pion/webrtc/blob/979aefd702bfe50552cd830a084f9bc339e7d7df/examples/save-to-disk/main.go#L108 but I don't have idea how to do :-(

@jibon57 did you get this working properly?

**Comment by davidzhao** [comment]
We had just release Egress service. Check out our [announcement](https://blog.livekit.io/livekit-universal-egress-launch/) and [docs](https://docs.livekit.io/guides/egress/)
