### ISSUE TITLE
How to scale to 5000 users

### ISSUE THREAD

**Issue by shivanand3939** [livekit/livekit#671]
Hi, I would like a single livekit server instance to host about 5000 users... could you please speciffy how to do it

**Comment by anupriya17** [comment]
I would like to know as well

**Comment by davidzhao** [comment]
We've updated [benchmarks](https://docs.livekit.io/deploy/benchmark/) with information regarding performance considerations.

**Comment by shivanand3939** [comment]
> We've updated [benchmarks](https://docs.livekit.io/deploy/benchmark/) section with information regarding performance considerations.

I've checked for 500 publishers and 500 subscribers.. it worked pretty fine
