### ISSUE TITLE
[proposal] add docs how to deploy to gcp 

### ISSUE THREAD

**Issue by hmbenhaim** [livekit/livekit#695]
Hi,
I was very impressed by livekit, especially when I saw that you have an official client package for flutter,  I saw that you have guides on how to deploy the server to aws, I'm just wondering if you can add docs to deploy on Google cloud platform?
Thank you

**Comment by davidzhao** [comment]
Hi, we do have guides now on GCP deployment (using a config generator). You can either deploy via VMs or Kubernetes. See [docs](https://docs.livekit.io/deploy/vm/)
