### ISSUE TITLE
pc crash on generate key

### ISSUE THREAD

**Issue by IgorDePaula** [livekit/livekit#698]
**Describe the bug**
On run docker command to generate key my Pc crash

**Server**
Ryzen 5 5600g
16gb RAM DDR4
ubuntu 20.04

**To Reproduce**
1. Run ```docker run --rm -v$PWD:/output livekit/generate --local```

**Expected behavior**
Not make pc crash on generate key

**Comment by davidzhao** [comment]
which version of docker are you running?

**Comment by IgorDePaula** [comment]
![Captura de tela de 2022-05-25 17-22-17](https://user-images.githubusercontent.com/2833993/170360640-b9540d37-dc76-42d9-b1c4-701621977300.png)

**Comment by davidzhao** [comment]
Does running docker otherwise cause a crash?

`docker run --rm -it alpine ls`

**Comment by IgorDePaula** [comment]
![Uploading Captura de tela de 2022-05-25 18-58-15.png…]()

**Comment by davidzhao** [comment]
that's strange.. can you paste any crash logs that you've got?

**Comment by davidzhao** [comment]
closing due to stale issue.
