### ISSUE TITLE
setup and configure redis - help

### ISSUE THREAD

**Issue by MyNameIsAlaa** [livekit/livekit#737]
I'm just testing livekit on ec2 instance, just one question how I setup and configure redis? It's not mentioned in the documentation

**Comment by davidzhao** [comment]
Hi there, you can follow [these docs](https://docs.livekit.io/deploy/vm/) to set LiveKit up on an EC2 instance, redis-included.

If you wish to set up your own Redis instance outside of our generated scripts, you can follow [other](https://medium.com/@calvin.hsieh/spin-up-redis-with-aws-ec2-e71911c55d61) [tutorials](https://sysadminxpert.com/how-to-install-redis-on-amazon-linux-or-centos/) around Redis installation.

**Comment by MyNameIsAlaa** [comment]
redis is not mentioned in the documentation and it's not in the docket containers or the template files, do I need to setup redis in the server myself?

**Comment by davidzhao** [comment]
Ah, we had an older version of the docs deployed. I just updated it. The deployment generator will create a config that embeds Redis.

**Comment by MyNameIsAlaa** [comment]
Awesome 🙌 thanks @davidzhao
