### ISSUE TITLE
Issue with multiple participants when running the example app

### ISSUE THREAD

**Issue by fobos531** [livekit/livekit#750]
**Describe the bug**
Hello, I'm running into an issue with the example app where I cannot join a room as a second participant. I'm able to join a room whenever there are no participants in the room. However, as soon as I try to join as a second participant, I'm running into issue.

**Server**
- Version: latest image from docker
- Environment: local dev, docker

I'm running LiveKit from docker as described in the getting started steps: https://docs.livekit.io/guides/getting-started/#setting-up-the-server
And then using example.livekit.io to try and see the functionality. Do note that I'm attempting to join the room from two different browser windows on the same computer, I don't know if that matters.

**To Reproduce**
1. Pull the latest docker image
2. Start it up according to the getting started docs
3. Use example.livekit.io to join the docker instance
4. On the same computer, but in a different browser window, join the room again.

**Expected behavior**
I should be able to join the room from two different browser windows on the same computer

**Screenshots**
This is the error I get in the server logs when joining as a second participant: 
![CleanShot 2022-06-04 at 13 48 07](https://user-images.githubusercontent.com/19533289/171997617-02ca819f-9cf2-4cf7-a06a-b38908e001b1.png)

**Additional context**
Here's the entire log I got from the docker instance: https://gist.github.com/fobos531/26c83c31cd7be4dec3ee26d4dd052997

**Comment by davidzhao** [comment]
Hi, are you using the same token to join the room? Each token should only be used by a single user since Identity needs to be unique.

**Comment by fobos531** [comment]
> Hi, are you using the same token to join the room? Each token should only be used by a single user since Identity needs to be unique.

Yeah I am! I wasn't aware of this, thanks! I'll try that out.

**Comment by davidzhao** [comment]
Closing the issue, hope that worked for you :)

**Comment by frozenproof** [comment]
What if we have multiple user with the same display name , which is similar to discord ? Shouldn't we add a display name in the token , along with the secret name ?
