### ISSUE TITLE
Send data (pdf files) between Partecipants

### ISSUE THREAD

**Issue by irafunesta** [livekit/livekit#753]
Hello
I would like to know if there is an option to send files to a Partecipant. 
I saw the send data  in the documentation with LocalParticipant.publishData, but i am not sure if i can use that
to recieve and send an entire file like a pdf.

Thanks

**Comment by davidzhao** [comment]
You def can build something that sends file data across. Just be sure to confirm the receiver has joined and is ready to receive messages.
