### ISSUE TITLE
If the picture shakes too fast, the quality of the viewing end will be poor

### ISSUE THREAD

**Issue by echo-LuGuang** [livekit/livekit#761]
I use the latest version. My server is ubantu with a bandwidth of 6Mbps. Only one person can watch it. I am streaming my win10 desktop.

When I switch windows too fast, the picture quality of the viewing section suddenly becomes very poor

![a629675c841a9157e4cc0148717b391](https://user-images.githubusercontent.com/50095011/174035983-f205fef3-12fb-47c1-b944-1a3e7e8beac3.jpg)

The downstream (server received) traffic of the server is normal, which is about 500KB, but the upstream (server sent) traffic is only about 40KB, which makes the image quality viewed by the client very unclear. But after refreshing the browser, the customer's view will become very clear

![Snipaste_2022-06-16_17-03-41](https://user-images.githubusercontent.com/50095011/174036445-39190c97-77e0-4a06-b59e-6b6dabfbcdd0.png)

config-sample.yaml：
```text

port: 7880

rtc:
  node_ip: ********

  port_range_start: 50000
  port_range_end: 60000

  tcp_port: 7881

  use_external_ip: true

  udp_port: 7882

  packet_buffer_size: 5000


keys:
  keys1: keys1




# turn server
turn:

  enabled: true

  udp_port: 3478

```

**Comment by echo-LuGuang** [comment]
But his picture quality will gradually become normal after a period of time.
Is this a problem with my configuration or some other reason?

**Comment by davidzhao** [comment]
This is due to simulcast being used for screen share. You can disable it by setting simulcast to false in publish options.

**Comment by echo-LuGuang** [comment]
nice，Solved the problem perfectly，thank you
