### ISSUE TITLE
This  website is down about recording templates

### ISSUE THREAD

**Issue by nelsonkti** [livekit/livekit#791]
url : https://egress-composite.livekit.io/

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/58064299/175960182-e005216d-f337-45f5-b542-a1e46b3f990d.png">

**Comment by davidzhao** [comment]
The site is not designed to be used this way. unless it has the appropriate parameters, this is expected.

See [here](https://github.com/livekit/egress/tree/main/template-sdk#testing-your-templates) for instructions on testing your template
