### ISSUE TITLE
The resolution is unable to recover when network quality is back to good or excellent

### ISSUE THREAD

**Issue by benjamin658** [livekit/livekit#817]
**Describe the bug**
We are trying to use the [client-sdk-react-native](https://github.com/livekit/client-sdk-react-native) to build an Android app with 4G networking.

While the resolution seems ok at the beginning of the experiment (network state excellent), when the network quality dropped significantly to the poor state, the resolution also dropped, but when the network quality returned to excellent, the resolution did not increase.

Here is our setting:

```
const preset = VideoPresets.h720
  const [room] = useState(
    () =>
      new Room({
        dynacast: true,
        videoCaptureDefaults: {
          resolution: preset.resolution,

        },
        publishDefaults: {
          videoEncoding: preset.encoding,
          simulcast: false,
        },
      }),
  );
```

**Server**
- Version: 1.1.0
- Environment: eks
- any other information about your deployment setup

**Client**
- SDK: client-sdk-react-native
- Version: 0.1.0

**To Reproduce**
1. Mobile client create and join a room.
2. Publish by 4g network with excellent network state.
3. Drop the network quality significantly to poor state,  the resolution also dropped.
4. The network quality returned to excellent, the resolution did not increase.

**Expected behavior**
When the network quality returns to excellent, the resolution should increase again.

**Screenshots**
1. Excellent network state with good resolution.
<img width="309" alt="截圖 2022-07-07 下午6 26 25" src="https://user-images.githubusercontent.com/4233028/177752745-5c6d30f2-fe37-4094-b3d6-40dac633c38c.png">

2. Excellent network state with bad resolution.
<img width="298" alt="截圖 2022-07-07 下午6 25 11" src="https://user-images.githubusercontent.com/4233028/177752710-65d42c9b-db03-4e08-8f7f-87cd82130931.png">

**Additional context**

**Comment by echo-LuGuang** [comment]
`simulcast: false`，
When you publish the stream, try to give this parameter to ensure that the quality of the video stream is the image quality you set.

**Comment by echo-LuGuang** [comment]
![image](https://user-images.githubusercontent.com/50095011/177949655-d1eb5603-b759-4b06-9bf3-2392b0aa34fb.png)

**Comment by benjamin658** [comment]
Hi @echo-LuGuang ,

The `simulcast ` is already set to false.

**Comment by davidzhao** [comment]
@benjamin658 did you disable adaptive stream as well? It recovers fine from poor network conditions in our testing. 

What are you using as the publishing dimensions/resolution? The screenshot indicates it's much higher than 720p. (indicated by your code)

**Comment by benjamin658** [comment]
Hi @davidzhao, 

Yes, we disabled the adaptive stream from the subscriber, we also adjusted the framerate to 20, and codec to h264, it seems a little bit better.

We also suspect that our publisher device's power supply is not stable, it could influence the 4g connectivity and camera (maybe), let us do more testing.

Thanks.
