### ISSUE TITLE
Screenshare on HoloLens2 doesn't show holographics

### ISSUE THREAD

**Issue by rboorman** [livekit/livekit#824]
**Describe the bug**
When screensharing from HoloLens2 - the desktop user in the same room can't see the holographic images.

**Server**
- Version: [1.1]
- Environment: [ubuntu docker]
- 
**Client**
- SDK: [Web]

**Expected behavior**
When screensharing we should se everything the user sees not just the camera and os apps.   We are wanting to screenshare when in WebXR.

**Comment by davidzhao** [comment]
Hey @rboorman could you provide more information about this? I have not used HoloLens myself but would be happy to support the use case if possible.

Which browser are you running the client in? what does the client logs indicate when you attempt to share the screen?

**Comment by rboorman** [comment]
Sorry about the delay - after more testing - It ended up being resource issues when sharing video streams within three.js scene in WebXR - it was bringing our framerate down to a crawl causing a severe delay in processing screen sharing.  We are optimizing our process to handle the video streaming textures, however screen sharing with holograms do in fact work well.  This issue can be closed.
