### ISSUE TITLE
NDI

### ISSUE THREAD

**Issue by brunocalado** [livekit/livekit#825]
Hi.

Can you add support for NDI?

This feature let you grab a link of the audio/video and send it to another application.

**Use Case**
You get the link for each participant and add it to OBS, so you can control each user.

**Links**
https://www.ndi.tv/tools/
This application with skype+obs: https://www.thepolyglotdeveloper.com/2020/04/live-stream-guests-using-obs-skype-ndi/

**Comment by davidzhao** [comment]
hi, this is out of scope for LiveKit. We need to keep the SFU lean & focused in order to ensure performance. checkout [Egress](https://blog.livekit.io/livekit-universal-egress-launch/), our solution to exporting tracks from LiveKit
