### ISSUE TITLE
Question: what is the correct way to update the server version?

### ISSUE THREAD

**Issue by mmckegg** [livekit/livekit#838]
I have a livekit deployment running on a digital ocean droplet that I created using a generated startup script. 

Since deploying, I see there is a new release. Haven't been unable to find any documentation recommending a method to upgrade to the latest livekit version.

What is the best practice here?

- generate a new config and deploy a fresh server?
- or will it work to just run the new config on an existing server running livekit?
- is there a better way?

At this point, it's just a test setup but under single server production conditions. 

Very much enjoying building on this platform so far, awesome project!

**Comment by davidzhao** [comment]
hey @mmckegg, it's actually as simple as updating the image tag in the generated docker-compose.yaml file.

For example, setting it to `livekit/livekit-server:v1.1.2` and reboot the server. We should include this in the docs though. Glad you are enjoying it!
