### ISSUE TITLE
Egress docs incorrect

### ISSUE THREAD

**Issue by JacobSteelsmith** [livekit/livekit#851]
Sorry if I missed where this is supposed to go and what a great project! The page https://docs.livekit.io/guides/egress/ has an example:

const info = await egressClient.startTrackEgress('my-room', trackID, output); 

The arguments are backwards. It should be:

It should be const info = await egressClient.startTrackEgress('my-room', output, trackID);

Using the example you get a 400 error. Thanks!

**Comment by davidzhao** [comment]
Thanks for the note, just fixed the typo in docs.

Cheers 🍻
