### ISSUE TITLE
Max Video Tiles supported By LiveKit??

### ISSUE THREAD

**Issue by ranthwar-vcx** [livekit/livekit#878]
Hello Team,

Would like to know How many max Video Tiles supported in Browser Like Zoom has 49 tiles,Team has 49 tiles???

Regards
Krishna

**Comment by davidzhao** [comment]
LiveKit has no limits to how many videos a user could subscribe. The real limit is the amount of bandwidth required. With [adaptive stream](https://docs.livekit.io/guides/room/receive/#adaptive-stream), 49 video tracks at 100kbps roughly means 5Mbps.
