### ISSUE TITLE
Opus RED support

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit#943]
This issue tracks Opus RED support in LiveKit. LiveKit will enable Opus RED for Chromium based browsers and all native SDKs. Firefox and Safari currently do not support RED.

RED enables redundant transmission of audio data so that it can transmit smooth audio playback even in high (50%+) packet loss networks. LiveKit implements an optimistic forwarding of RED so that improvements will be audible when both publisher and subscriber support it. When a subscriber doesn't support RED, redundant encoding will be stripped out within the SFU.

| publisher | subscriber | SFU forwards |
| --------- | ---------- | ------------ |
| red       | red        | red          |
| red       | no red     | no red       |
| no red    | red        | no red       |
| no red    | no red     | no red       |

When a client supports RED, the SFU will prefer RED encoding over standard Opus by default. If you wish to disable RED, you can customize the list of allowed codecs [here](https://github.com/livekit/livekit/blob/c333b7a026fd85029b46cc9593146a049df117e5/config-sample.yaml#L121) to explicitly list the codecs without RED.

**Comment by dgillier** [comment]
Thanks a lot! 
Any idea if safari will support RED ?

**Comment by davidzhao** [comment]
@dgillier Yes, Safari 16 does support RED.  You can test for yourself [here](https://livekit.io/webrtc/browser-test)
