### ISSUE TITLE
Single server LiveKit deploying fails

### ISSUE THREAD

**Issue by oarsoy** [livekit/livekit#948]
Hello, we followed this documentation: https://docs.livekit.io/deploy/vm/

We are trying to deploy a single node LiveKit on DigitalOcean by using Docker but not success. Do we miss something?

1. Create Ubuntu Docker droplet
2. Run docker run --rm -it -v$PWD:/output livekit/generate
3. Enter domain info, choose internal redis, and latest version of LiveKit (it gives API key and access token at this point)
4. DNS configurations for main domain and subdomain are correct
5. Open ports in firewall config
6. Restart server

No success. When we run “systemctl start livekit-docker” it gives “Failed to start livekit-docker.service: Unit livekit-docker.service not found.” error. And it looks like /opt/livekit folder is missing.

Any ideas?

**Comment by davidzhao** [comment]
@oarsoy, the generator is meant to be ran on your dev machine. it'll generate a shell script (or cloud-init) that can be passed to the VM during bootup. Digital Ocean supports cloud-init, so you'll want to: (from [docs](https://docs.livekit.io/deploy/vm/#deploy-to-a-vm)):

```
When starting a VM, paste the contents of the file cloud-init.xxxx.yaml into the User data field.

That's it! When the machine starts up, it'll execute the cloud-init protocol and install LiveKit.
```
