### ISSUE TITLE
Audio tracks do not support stereo sound

### ISSUE THREAD

**Issue by bekriebel** [livekit/livekit#970]
**Describe the bug**
When using LiveKit, at least with the Javascript SDK, received audio tracks are always downsampled to mono, regardless of how they are sent.

I would like to use LiveKit for some higher-quality audio purposes. For this, I think some changes may be needed to allow the audio quality to be controlled either by server configurations, or preferably client-side.

**Server**
- Version: [1.2.0]
- Environment: Docker image VPS hosted & local dev

**Client**
- SDK: js
- Version: 1.3.0

**To Reproduce**
1. two clients are connected to room
2. One client publishes an audio track, specifying AudioCaptureOptions and TrackPublishOptions:
`<track>.mediaStreamTrack.getSettings()`
```ts
    AudioCaptureOptions = {
        autoGainControl: false,
        echoCancellation: false,
        noiseSuppression: false,
        channelCount: 2,
      }
      
      TrackPublishOptions = {
        audioBitrate: 256_000,
      };
```
4. 2nd client receives the track
5. Validate on the sending side that two channels are being captured:
`<track>.mediaStreamTrack.getSettings()`
```json
{
    "autoGainControl": false,
    "channelCount": 2,
    "deviceId": "web-contents-media-stream://2884:4",
    "echoCancellation": false,
    "latency": 0.042666,
    "noiseSuppression": false,
    "sampleRate": 48000,
    "sampleSize": 16
}
```
7. See that on the receiving side, only a single channel is received:
```json
{
    "channelCount": 1,
    "deviceId": "TR_Asstr5zE4jUefc",
    "latency": 0.01,
    "sampleRate": 48000,
    "sampleSize": 16
}
```

**Expected behavior**
If a track is published as stereo audio, it should also be received as such.

**Screenshots**
N/A

**Additional context**
I think at least part of this is coming from the fact that the `SDPFmtpLine` is not specifying `stereo=1` here: https://github.com/livekit/livekit/blob/1371108a46ac090d9ae24bea012650e70086ee10/pkg/rtc/mediaengine.go#L13, though there may be more changes needed, especially to support the new `opus/red` codec. It may also be helpful to add `maxaveragebitrate=510000` to ensure the maximum bitrate can be allowed.

**Comment by bdrtc** [comment]
is your mic device support stero capture ?

**Comment by bekriebel** [comment]
@cnderrauber Is there a test case for this working? I'm trying the same test case described here, and I'm still only seeing a single channel on the received mediaTrack. I'm testing with  LiveKit server v1.2.3 and JS Client v1.4.1. I'm trying to see if it is something wrong with my test case, or if #1013 isn't working as intended.

**Comment by cnderrauber** [comment]
@bekriebel are you test with a stereo mic and speaker?

**Comment by bekriebel** [comment]
> @bekriebel are you test with a stereo mic and speaker?

Yes. It shows as two channels on the publisher side, just not the receiver for some reason. In a client PR, someone confirmed it is working for them, so I'll do more testing on my side and see if I can figure out what's going on.

**Comment by mmckegg** [comment]
@bekriebel hey, I just tested this again now, and can confirm that stereo IS NOT working. I'm guessing I must have been running my other branch that I had manually patched by mistake :(

I poked around in the socket communication and it doesn't seem to be including the stereo=1 in the SDP at all.

FYI running latest Chrome on macOS 12.6

**Comment by mmckegg** [comment]
My previous screenshots above were on the receiving client. However, upon inspecting the transmitting side, I see that it does receive stereo=1 in the offer:

<img width="659" alt="Screen Shot 2022-09-30 at 3 00 14 AM" src="https://user-images.githubusercontent.com/66834/193052598-23f7e28d-e13a-4f4a-a7a6-06037876f463.png">

My own branch added the stereo=1 to all sides and that seemed to work. I wonder if this is important here.

**Comment by bekriebel** [comment]
> I just added `stereo=1` in down stream also. Can you please try this branch https://github.com/livekit/livekit/tree/raja_down_stereo @bekriebel @mmckegg

Unfortunately I get the same results. 
Publisher side: 
![image](https://user-images.githubusercontent.com/183779/193103101-07f4462f-9363-48fe-99dd-3fe7f50b67a6.png)

Receiver side:
![image](https://user-images.githubusercontent.com/183779/193102958-b553cd2a-5f50-4da5-a66c-fa0a0859213e.png)

**Comment by bekriebel** [comment]
I'm not sure what paths the different codecs take through the code. Does this apply to `audio/red` as well as `audio/opus`? Since I'm using chrome on both sides for my test, it's defaulting to the opus/red codec.

**Comment by boks1971** [comment]
Thank you for trying it out. `opus/red` is more of an envelope and in theory should just package up the underlying codec payload with redundancy. But, it is new and maybe it has some issues. Will dig further.

**Comment by boks1971** [comment]
Wow, interesting @bekriebel . Does that work in `master` also? Or do you need the change in my branch for it to work? I am guessing it should work in `master`?

**Comment by bekriebel** [comment]
> Wow, interesting @bekriebel . Does that work in `master` also? Or do you need the change in my branch for it to work? I am guessing it should work in `master`?

Yep, I was just about to add that update. I went back to master and checked. It also works there as long as the receiving end is Firefox. I don't think it is working if the sending side is Firefox, but I need to set up a better test because I can't do shared screens with audio from Firefox.

**Comment by boks1971** [comment]
Thank you @bekriebel . Good to know it is an `opus/red` issue. Have to dig into why it is not working with that.

**Comment by bekriebel** [comment]
At least I'm assuming it is an `opus/red` related issue. I just confirmed, Stereo tracks work from Chrome -> Firefox and Firefox -> Firefox, but not Firefox -> Chrome.

**Comment by bekriebel** [comment]
Yeah. The issue may just be that Chrome isn't receiving stereo.

If I set
```yaml
room:
  enabled_codecs:
    - mime: audio/opus
    - mime: video/vp8
 ```
 on the server, should that disable `opus/red`? If so, it isn't a `red` issue. I just tested that, and I get the same results.

**Comment by bekriebel** [comment]
@boks1971 and @cnderrauber, I've done in a lot deep to this issue. As @mmckegg pointed out in https://github.com/livekit/client-sdk-js/pull/450, SDP modification is actually needed. It seems that this is true because Chrome doesn't set `stereo=1` in the SDP answer when running `createAnswer()`. It seems to pull this from the default codec settings, seen by running `RTCRtpSender.getCapabilities("audio");` in the console. More verbosely, you can see this with a plain WebRTC session here: https://jsfiddle.net/5wzrejvh/3/. If you run that jsfiddle in Firefox, you can see that it turns stereo on by default; this is why receiving stereo on Firefox works.

I tested this by completely disabling `audio/red` on my test server, and Chrome still acts the same way.

I think something similar to https://github.com/livekit/client-sdk-js/pull/450 is the best route to go. It might even make sense to just default `stereo=1` to on. It looks like this is what Chrome Remote Desktop does, as well as increasing the bitrate on the codec offer: https://source.chromium.org/chromium/chromium/src/+/main:remoting/protocol/webrtc_transport.cc;l=102?q=webrtc_transport&ss=chromium

Should I open a new ticket under the JS client repo? Do you want to take https://github.com/livekit/client-sdk-js/pull/450 as is, or are there any changes you'd like to make?

**Comment by davidzhao** [comment]
reopening so we could take another look. if there isn't a way to accomplish this on the server side, then we can pursue the client path.

**Comment by bekriebel** [comment]
Anything I can do to help with this? I'm pretty confident that this will require the client-side change due to chromium limitations, but I'm happy to help test if someone has other server-side ideas. I can also make modifications to mmckeg's patch if that isn't implemented in a way that the team is comfortable with.

**Comment by mmckegg** [comment]
Just for reference, I've currently solved this issue in my own project by applying this nasty patch to the room whenever created:

https://gist.github.com/mmckegg/df597f95fa7b608fb2b232557ad1522f

All it does is add `stereo=1` to the subscriber when it sets the local description. Was the most unobtrusive way I could find for a temporary fix. Works like a charm in Chrome.

**Comment by bdrtc** [comment]
> Just for reference, I've currently solved this issue in my own project by applying this nasty patch to the room whenever created:
> 
> https://gist.github.com/mmckegg/df597f95fa7b608fb2b232557ad1522f
> 
> All it does is add `stereo=1` to the subscriber when it sets the local description. Was the most unobtrusive way I could find for a temporary fix. Works like a charm in Chrome.

yes, you must munging sdp to get stero audio, [there is a issue discussion this](https://github.com/w3c/webrtc-extensions/issues/63)

**Comment by cnderrauber** [comment]
@bekriebel @mmckegg I have tested screen share with a youtube stereo video (https://www.youtube.com/watch?v=6TWJaFD6R2s) and combine various conditions (with/without client patch / redcodec ), the receiver side still get a mono audio (use a stereo playback device), so the result confuse. Can you describe the steps that makes stereo work for you? If the publisher offer side munged sdp is required, I think client path would be a appropriate way for this

**Comment by cnderrauber** [comment]
@mmckegg @bekriebel Verified subscriber side munged sdp is required for chrome receive & playback stereo, it is not comply the spec, while ff works well without it. We need the client patch to fix it. Thank you!!
