### ISSUE TITLE
install livekit 

### ISSUE THREAD

**Issue by ATavanaei** [livekit/livekit#971]
hi 
i had many time try to install Livekit from source but at ,the nd I could not found any service for start or restart the service.

this is my command line actions:

root@stream3:~/livekit# ls
bin           CHANGELOG  config-sample.yaml  Dockerfile  go.sum              LICENSE      magefile_unix.go     pkg        renovate.json  tools
bootstrap.sh  cmd        deploy              go.mod      install-livekit.sh  magefile.go  magefile_windows.go  README.md  test           version
root@stream3:~/livekit# ./install-livekit.sh
Installing livekit 1.2.0
Downloading from https://github.com/livekit/livekit/releases/download/v1.2.0/livekit_1.2.0_linux_amd64.tar.gz...

livekit-server is installed to /usr/local/bin

I was flow by installation on Linux because I want a monitoring system based on the link below.

https://docs.livekit.io/deploy/test-monitor/

**Comment by davidzhao** [comment]
we currently don't have a service when installed from source. You could use [this template](https://github.com/livekit/deploy/blob/main/generate/templates/systemd.go) to create your own systemd service.
