### ISSUE TITLE
Crashed once during 25 people call, please add length check

### ISSUE THREAD

**Issue by anilkumarmeena** [livekit/livekit#980]
**this is the stack trace for the error**

panic: runtime error: index out of range [0] with length 0
goroutine 6038874 [running]:
livekit/pkg/sfu/buffer.(*VP8).MarshalTo(0xc00cbbfd40?, {0xc002d74600?, 0xc000140f90?, 0x11d7732?})
        livekit@v0.0.0-20220829095212-a2ba53600200/pkg/sfu/buffer/helpers.go:165 +0x1b6
livekit/pkg/sfu.(*DownTrack).translateVP8PacketTo(0xc000140f90?, 0xc001c99214?, 0x366?, 0xc01178f8c0?, 0x17110c63c652913b?)
        livekit@v0.0.0-20220829095212-a2ba53600200/pkg/sfu/downtrack.go:1379 +0xda
livekit/pkg/sfu.(*DownTrack).retransmitPackets(0xc010d19900, {0xc027f7f000?, 0xc027fc1cb0?, 0xc0024857b8?})
        livekit@v0.0.0-20220829095212-a2ba53600200/pkg/sfu/downtrack.go:1271 +0x665
created by livekit/pkg/sfu.(*DownTrack).handleRTCP
        livekit@v0.0.0-20220829095212-a2ba53600200/pkg/sfu/downtrack.go:1158 +0x715

**We can add a length check in marshal to function. can add this with if condition len(buf) == 0 ||**

<img width="648" alt="Screenshot 2022-09-03 at 11 04 02 AM" src="https://user-images.githubusercontent.com/32728998/188257399-027d65db-b213-4bd2-8487-1da7825b0b7f.png">

**Comment by davidzhao** [comment]
Please fill out a bug report in its entirety, including version number & platform.
