### ISSUE TITLE
Number of participant get out of sync in Cluster mode

### ISSUE THREAD

**Issue by EmrysMyrddin** [livekit/livekit#989]
**Describe the bug**
Num participant got out of sync in multi-node mode.

**Server**
- Version: 1.2.0
- Environment: Kubernetes
- Using cluster mode with Redis and only 1 node

**Client**
No client involved, only receiving webhooks

**To Reproduce**
I don't know how to reproduce this bug but I suppose it involve crashing the node, which will let Redis in a inconsistent state.
Restarting the node doesn't solve this, I had to wipe the redis database.

**Expected behavior**
The number of participant should always reflect the real number of participant.

**Additional context**
Perhaps this is caused by having only one node in my cluster, leading to inconsistent behaviour on failure.

**Comment by davidzhao** [comment]
Fixed in #992, released in 1.2.1
